/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from '../index.js';

const causticsShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform float uAspect;
in vec2 vUv;
out vec4 fragColor;
vec2 hash22(vec2 p) {
  vec2 k = vec2(dot(p, vec2(127.1, 311.7)), dot(p, vec2(269.5, 183.3)));
  return vec2(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
float voronoi2(vec2 p) {
  vec2 cell = vec2(floor(p.x), floor(p.y));
  vec2 f = p - cell;
  float minDist = 8.0;
  for (float i = -1.0; i <= 1.0; i = i + 1.0) {
    for (float j = -1.0; j <= 1.0; j = j + 1.0) {
      vec2 neighbor = vec2(i, j);
      vec2 feature = hash22(cell + neighbor);
      vec2 diff = neighbor + feature - f;
      minDist = min(minDist, length(diff));
    }
  }
  return minDist;
}
void main() {
  vec2 q = vec2(vUv.x * uAspect, vUv.y) * 5.0;
  vec2 drift1 = vec2(uTime * 0.25, uTime * 0.18);
  vec2 drift2 = vec2(uTime * -0.2, uTime * 0.12);
  float c1 = pow(1.0 - voronoi2(q + drift1), 4.0);
  float c2 = pow(1.0 - voronoi2(q * 1.7 + drift2), 4.0);
  float light = c1 * 0.8 + c2 * 0.45;
  vec3 deep = vec3(0.02, 0.18, 0.3);
  vec3 bright = vec3(0.6, 0.95, 1.0);
  fragColor = vec4(mix(deep, bright, light), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn hash22(p : vec2f) -> vec2f {
  let k = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return vec2f(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
fn voronoi2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  var minDist = 8.0;
  for (var i = -1.0; i <= 1.0; i = i + 1.0) {
    for (var j = -1.0; j <= 1.0; j = j + 1.0) {
      let neighbor = vec2f(i, j);
      let feature = hash22(cell + neighbor);
      let diff = neighbor + feature - f;
      minDist = min(minDist, length(diff));
    }
  }
  return minDist;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let q = vec2f(bm_in.vUv.x * bm_u.uAspect, bm_in.vUv.y) * 5.0;
  let drift1 = vec2f(bm_u.uTime * 0.25, bm_u.uTime * 0.18);
  let drift2 = vec2f(bm_u.uTime * -0.2, bm_u.uTime * 0.12);
  let c1 = pow(1.0 - voronoi2(q + drift1), 4.0);
  let c2 = pow(1.0 - voronoi2(q * 1.7 + drift2), 4.0);
  let light = c1 * 0.8 + c2 * 0.45;
  let deep = vec3f(0.02, 0.18, 0.3);
  let bright = vec3f(0.6, 0.95, 1.0);
  return vec4f(mix(deep, bright, light), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default causticsShader;
