/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from '../index.js';

const crtShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float'; uTex: 'sampler2D' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform sampler2D uTex;
in vec2 vUv;
out vec4 fragColor;
void main() {
  vec2 c = vec2(vUv.x - 0.5, vUv.y - 0.5);
  float r2 = dot(c, c);
  vec2 q = vec2(c.x * (1.0 + r2 * 0.28) + 0.5, c.y * (1.0 + r2 * 0.28) + 0.5);
  float inBounds = step(0.0, q.x) * step(q.x, 1.0) * step(0.0, q.y) * step(q.y, 1.0);
  float scan = 0.82 + 0.18 * sin(q.y * 700.0 + uTime * 8.0);
  float flicker = 0.96 + 0.04 * sin(uTime * 60.0);
  vec3 color = texture(uTex, q).xyz * (scan * flicker * inBounds);
  float vig = 1.0 - smoothstep(0.3, 0.62, r2);
  fragColor = vec4(color * vig, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let c = vec2f(bm_in.vUv.x - 0.5, bm_in.vUv.y - 0.5);
  let r2 = dot(c, c);
  let q = vec2f(c.x * (1.0 + r2 * 0.28) + 0.5, c.y * (1.0 + r2 * 0.28) + 0.5);
  let inBounds = step(0.0, q.x) * step(q.x, 1.0) * step(0.0, q.y) * step(q.y, 1.0);
  let scan = 0.82 + 0.18 * sin(q.y * 700.0 + bm_u.uTime * 8.0);
  let flicker = 0.96 + 0.04 * sin(bm_u.uTime * 60.0);
  let color = textureSample(uTex, uTex_sampler, q).xyz * (scan * flicker * inBounds);
  let vig = 1.0 - smoothstep(0.3, 0.62, r2);
  return vec4f(color * vig, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float', uTex: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2}],"uniformBlockSize":16},
};

export default crtShader;
