/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from '../index.js';

const easingShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform float uAspect;
in vec2 vUv;
out vec4 fragColor;
float easeOutBounce(float t) {
  float n1 = 7.5625;
  float d1 = 2.75;
  float result = 0.0;
  if (t < 0.36363636) {
    result = n1 * t * t;
  } else {
    if (t < 0.72727272) {
      float t2 = t - 0.54545454;
      result = n1 * t2 * t2 + 0.75;
    } else {
      if (t < 0.9090909) {
        float t3 = t - 0.81818181;
        result = n1 * t3 * t3 + 0.9375;
      } else {
        float t4 = t - 0.95454545;
        result = n1 * t4 * t4 + 0.984375;
      }
    }
  }
  return result;
}
float easeOutElastic(float t) {
  float c4 = 2.0943951;
  float result = pow(2.0, -10.0 * t) * sin((t * 10.0 - 0.75) * c4) + 1.0;
  if (t <= 0.0) {
    result = 0.0;
  }
  if (t >= 1.0) {
    result = 1.0;
  }
  return result;
}
float easeInOutCubic(float t) {
  float result = 4.0 * t * t * t;
  if (t >= 0.5) {
    float inv = 2.0 - 2.0 * t;
    result = 1.0 - inv * inv * inv * 0.5;
  }
  return result;
}
float sdCircle(vec2 p, float radius) {
  return length(p) - radius;
}
float fillAA(float d, float softness) {
  return 1.0 - smoothstep(0.0, softness, d);
}
void main() {
  vec2 p = vec2(vUv.x * uAspect, vUv.y);
  float t = fract(uTime * 0.5);
  float bounceY = 0.15 + easeOutBounce(t) * 0.6;
  float elasticY = 0.15 + easeOutElastic(t) * 0.6;
  float cubicY = 0.15 + easeInOutCubic(t) * 0.6;
  float third = uAspect / 3.0;
  float b1 = fillAA(sdCircle(p - vec2(third * 0.5, bounceY), 0.05), 0.005);
  float b2 = fillAA(sdCircle(p - vec2(third * 1.5, elasticY), 0.05), 0.005);
  float b3 = fillAA(sdCircle(p - vec2(third * 2.5, cubicY), 0.05), 0.005);
  vec3 color = vec3(0.98, 0.45, 0.2) * b1 + vec3(0.3, 0.82, 0.44) * b2 + vec3(0.55, 0.6, 1.0) * b3;
  fragColor = vec4(color, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn easeOutBounce(t : f32) -> f32 {
  let n1 = 7.5625;
  let d1 = 2.75;
  var result = 0.0;
  if (t < 0.36363636) {
    result = n1 * t * t;
  } else {
    if (t < 0.72727272) {
      let t2 = t - 0.54545454;
      result = n1 * t2 * t2 + 0.75;
    } else {
      if (t < 0.9090909) {
        let t3 = t - 0.81818181;
        result = n1 * t3 * t3 + 0.9375;
      } else {
        let t4 = t - 0.95454545;
        result = n1 * t4 * t4 + 0.984375;
      }
    }
  }
  return result;
}
fn easeOutElastic(t : f32) -> f32 {
  let c4 = 2.0943951;
  var result = pow(2.0, -10.0 * t) * sin((t * 10.0 - 0.75) * c4) + 1.0;
  if (t <= 0.0) {
    result = 0.0;
  }
  if (t >= 1.0) {
    result = 1.0;
  }
  return result;
}
fn easeInOutCubic(t : f32) -> f32 {
  var result = 4.0 * t * t * t;
  if (t >= 0.5) {
    let inv = 2.0 - 2.0 * t;
    result = 1.0 - inv * inv * inv * 0.5;
  }
  return result;
}
fn sdCircle(p : vec2f, radius : f32) -> f32 {
  return length(p) - radius;
}
fn fillAA(d : f32, softness : f32) -> f32 {
  return 1.0 - smoothstep(0.0, softness, d);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = vec2f(bm_in.vUv.x * bm_u.uAspect, bm_in.vUv.y);
  let t = fract(bm_u.uTime * 0.5);
  let bounceY = 0.15 + easeOutBounce(t) * 0.6;
  let elasticY = 0.15 + easeOutElastic(t) * 0.6;
  let cubicY = 0.15 + easeInOutCubic(t) * 0.6;
  let third = bm_u.uAspect / 3.0;
  let b1 = fillAA(sdCircle(p - vec2f(third * 0.5, bounceY), 0.05), 0.005);
  let b2 = fillAA(sdCircle(p - vec2f(third * 1.5, elasticY), 0.05), 0.005);
  let b3 = fillAA(sdCircle(p - vec2f(third * 2.5, cubicY), 0.05), 0.005);
  let color = vec3f(0.98, 0.45, 0.2) * b1 + vec3f(0.3, 0.82, 0.44) * b2 + vec3f(0.55, 0.6, 1.0) * b3;
  return vec4f(color, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default easingShader;
