/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from '../index.js';

const edgesShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float'; uTex: 'sampler2D' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform sampler2D uTex;
in vec2 vUv;
out vec4 fragColor;
float luminance(vec3 color) {
  return dot(color, vec3(0.2126, 0.7152, 0.0722));
}
void main() {
  float e = 0.0016;
  float gx = luminance(texture(uTex, vUv + vec2(e, 0.0)).xyz) - luminance(texture(uTex, vUv - vec2(e, 0.0)).xyz);
  float gy = luminance(texture(uTex, vUv + vec2(0.0, e)).xyz) - luminance(texture(uTex, vUv - vec2(0.0, e)).xyz);
  float mag = sqrt(gx * gx + gy * gy) * 5.0;
  fragColor = vec4(mag * 0.4, mag * 0.9, mag, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn luminance(color : vec3f) -> f32 {
  return dot(color, vec3f(0.2126, 0.7152, 0.0722));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let e = 0.0016;
  let gx = luminance(textureSample(uTex, uTex_sampler, bm_in.vUv + vec2f(e, 0.0)).xyz) - luminance(textureSample(uTex, uTex_sampler, bm_in.vUv - vec2f(e, 0.0)).xyz);
  let gy = luminance(textureSample(uTex, uTex_sampler, bm_in.vUv + vec2f(0.0, e)).xyz) - luminance(textureSample(uTex, uTex_sampler, bm_in.vUv - vec2f(0.0, e)).xyz);
  let mag = sqrt(gx * gx + gy * gy) * 5.0;
  return vec4f(mag * 0.4, mag * 0.9, mag, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float', uTex: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2}],"uniformBlockSize":16},
};

export default edgesShader;
