/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from '../index.js';

const glitchShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float'; uTex: 'sampler2D' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform sampler2D uTex;
in vec2 vUv;
out vec4 fragColor;
float hash11(float p) {
  return fract(sin(p * 127.1) * 43758.5453);
}
void main() {
  float frame = floor(uTime * 7.0);
  float row = floor(vUv.y * 28.0);
  float gate = step(0.82, hash11(row * 3.7 + frame * 17.0));
  float shift = (hash11(row + frame * 100.0) - 0.5) * 0.25 * gate;
  vec2 q = vec2(fract(vUv.x + shift), vUv.y);
  float split = 0.012 * gate + 0.002;
  float r = texture(uTex, vec2(fract(q.x + split), q.y)).x;
  float g = texture(uTex, q).y;
  float b = texture(uTex, vec2(fract(q.x - split), q.y)).z;
  fragColor = vec4(r, g, b, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn hash11(p : f32) -> f32 {
  return fract(sin(p * 127.1) * 43758.5453);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let frame = floor(bm_u.uTime * 7.0);
  let row = floor(bm_in.vUv.y * 28.0);
  let gate = step(0.82, hash11(row * 3.7 + frame * 17.0));
  let shift = (hash11(row + frame * 100.0) - 0.5) * 0.25 * gate;
  let q = vec2f(fract(bm_in.vUv.x + shift), bm_in.vUv.y);
  let split = 0.012 * gate + 0.002;
  let r = textureSample(uTex, uTex_sampler, vec2f(fract(q.x + split), q.y)).x;
  let g = textureSample(uTex, uTex_sampler, q).y;
  let b = textureSample(uTex, uTex_sampler, vec2f(fract(q.x - split), q.y)).z;
  return vec4f(r, g, b, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float', uTex: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2}],"uniformBlockSize":16},
};

export default glitchShader;
