/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from '../index.js';

const halftoneShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float'; uTex: 'sampler2D' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uAspect;
uniform sampler2D uTex;
in vec2 vUv;
out vec4 fragColor;
float luminance(vec3 color) {
  return dot(color, vec3(0.2126, 0.7152, 0.0722));
}
vec2 rotate2(vec2 p, float angle) {
  float c = cos(angle);
  float s = sin(angle);
  return vec2(p.x * c - p.y * s, p.x * s + p.y * c);
}
float fillAA(float d, float softness) {
  return 1.0 - smoothstep(0.0, softness, d);
}
void main() {
  float lum = luminance(texture(uTex, vUv).xyz);
  vec2 grid = rotate2(vec2(vUv.x * uAspect, vUv.y), 0.6) * 70.0;
  vec2 cell = vec2(fract(grid.x) - 0.5, fract(grid.y) - 0.5);
  float radius = (1.0 - lum) * 0.68;
  float ink = fillAA(length(cell) - radius, 0.08);
  vec3 paper = vec3(0.96, 0.94, 0.88);
  vec3 inkColor = vec3(0.12, 0.1, 0.2);
  fragColor = vec4(mix(paper, inkColor, ink), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn luminance(color : vec3f) -> f32 {
  return dot(color, vec3f(0.2126, 0.7152, 0.0722));
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn fillAA(d : f32, softness : f32) -> f32 {
  return 1.0 - smoothstep(0.0, softness, d);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let lum = luminance(textureSample(uTex, uTex_sampler, bm_in.vUv).xyz);
  let grid = rotate2(vec2f(bm_in.vUv.x * bm_u.uAspect, bm_in.vUv.y), 0.6) * 70.0;
  let cell = vec2f(fract(grid.x) - 0.5, fract(grid.y) - 0.5);
  let radius = (1.0 - lum) * 0.68;
  let ink = fillAA(length(cell) - radius, 0.08);
  let paper = vec3f(0.96, 0.94, 0.88);
  let inkColor = vec3f(0.12, 0.1, 0.2);
  return vec4f(mix(paper, inkColor, ink), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float', uTex: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2}],"uniformBlockSize":16},
};

export default halftoneShader;
