/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from '../index.js';

const juliaShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform float uAspect;
in vec2 vUv;
out vec4 fragColor;
vec3 cosinePalette(float t, vec3 a, vec3 b, vec3 c, vec3 d) {
  vec3 phase = (c * t + d) * 6.28318;
  return a + vec3(cos(phase.x), cos(phase.y), cos(phase.z)) * b;
}
void main() {
  float zx = (vUv.x - 0.5) * uAspect * 2.8;
  float zy = (vUv.y - 0.5) * 2.8;
  float cRe = 0.7885 * cos(uTime * 0.25);
  float cIm = 0.7885 * sin(uTime * 0.25);
  float escaped = 0.0;
  for (float i = 1.0; i <= 48.0; i = i + 1.0) {
    float nx = zx * zx - zy * zy + cRe;
    float ny = 2.0 * zx * zy + cIm;
    zx = nx;
    zy = ny;
    if (escaped < 0.5 && zx * zx + zy * zy > 4.0) {
      escaped = i;
    }
  }
  vec3 color = vec3(0.0, 0.0, 0.0);
  if (escaped > 0.5) {
    color = cosinePalette(escaped * 0.025 + uTime * 0.02, vec3(0.5, 0.5, 0.5), vec3(0.5, 0.5, 0.5), vec3(1.0, 1.0, 1.0), vec3(0.0, 0.1, 0.2));
  }
  fragColor = vec4(color, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn cosinePalette(t : f32, a : vec3f, b : vec3f, c : vec3f, d : vec3f) -> vec3f {
  let phase = (c * t + d) * 6.28318;
  return a + vec3f(cos(phase.x), cos(phase.y), cos(phase.z)) * b;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  var zx = (bm_in.vUv.x - 0.5) * bm_u.uAspect * 2.8;
  var zy = (bm_in.vUv.y - 0.5) * 2.8;
  let cRe = 0.7885 * cos(bm_u.uTime * 0.25);
  let cIm = 0.7885 * sin(bm_u.uTime * 0.25);
  var escaped = 0.0;
  for (var i = 1.0; i <= 48.0; i = i + 1.0) {
    let nx = zx * zx - zy * zy + cRe;
    let ny = 2.0 * zx * zy + cIm;
    zx = nx;
    zy = ny;
    if (escaped < 0.5 && zx * zx + zy * zy > 4.0) {
      escaped = i;
    }
  }
  var color = vec3f(0.0, 0.0, 0.0);
  if (escaped > 0.5) {
    color = cosinePalette(escaped * 0.025 + bm_u.uTime * 0.02, vec3f(0.5, 0.5, 0.5), vec3f(0.5, 0.5, 0.5), vec3f(1.0, 1.0, 1.0), vec3f(0.0, 0.1, 0.2));
  }
  return vec4f(color, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default juliaShader;
