/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from '../index.js';

const lightingShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform float uAspect;
in vec2 vUv;
out vec4 fragColor;
float lambert(vec3 normal, vec3 lightDir) {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
float blinnPhongSpec(vec3 normal, vec3 lightDir, vec3 viewDir, float shininess) {
  vec3 halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
float fresnel(vec3 normal, vec3 viewDir, float power) {
  float base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
vec3 hemisphereLight(vec3 normal, vec3 skyColor, vec3 groundColor) {
  float blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
float fillAA(float d, float softness) {
  return 1.0 - smoothstep(0.0, softness, d);
}
float sdCircle(vec2 p, float radius) {
  return length(p) - radius;
}
void main() {
  vec2 p = vec2((vUv.x - 0.5) * uAspect, vUv.y - 0.5) * 2.4;
  float r = length(p);
  vec3 lightDir = vec3(cos(uTime), 0.7, sin(uTime));
  vec3 viewDir = vec3(0.0, 0.0, 1.0);
  vec3 color = vec3(0.05, 0.05, 0.08);
  if (r < 1.0) {
    vec3 normal = vec3(p.x, p.y, sqrt(1.0 - r * r));
    vec3 ambient = hemisphereLight(normal, vec3(0.22, 0.25, 0.36), vec3(0.1, 0.08, 0.07));
    float diffuse = lambert(normal, lightDir);
    float spec = blinnPhongSpec(normal, lightDir, viewDir, 48.0);
    float rim = fresnel(normal, viewDir, 3.0);
    vec3 base = vec3(0.85, 0.35, 0.25);
    color = base * diffuse + ambient * base + vec3(1.0, 1.0, 1.0) * (spec * 0.5) + vec3(0.4, 0.5, 1.0) * (rim * 0.4);
  }
  float mask = fillAA(sdCircle(p, 1.0), 0.01);
  fragColor = vec4(color * mask + vec3(0.05, 0.05, 0.08) * (1.0 - mask), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn lambert(normal : vec3f, lightDir : vec3f) -> f32 {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
fn blinnPhongSpec(normal : vec3f, lightDir : vec3f, viewDir : vec3f, shininess : f32) -> f32 {
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
fn fresnel(normal : vec3f, viewDir : vec3f, power : f32) -> f32 {
  let base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
fn hemisphereLight(normal : vec3f, skyColor : vec3f, groundColor : vec3f) -> vec3f {
  let blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
fn fillAA(d : f32, softness : f32) -> f32 {
  return 1.0 - smoothstep(0.0, softness, d);
}
fn sdCircle(p : vec2f, radius : f32) -> f32 {
  return length(p) - radius;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = vec2f((bm_in.vUv.x - 0.5) * bm_u.uAspect, bm_in.vUv.y - 0.5) * 2.4;
  let r = length(p);
  let lightDir = vec3f(cos(bm_u.uTime), 0.7, sin(bm_u.uTime));
  let viewDir = vec3f(0.0, 0.0, 1.0);
  var color = vec3f(0.05, 0.05, 0.08);
  if (r < 1.0) {
    let normal = vec3f(p.x, p.y, sqrt(1.0 - r * r));
    let ambient = hemisphereLight(normal, vec3f(0.22, 0.25, 0.36), vec3f(0.1, 0.08, 0.07));
    let diffuse = lambert(normal, lightDir);
    let spec = blinnPhongSpec(normal, lightDir, viewDir, 48.0);
    let rim = fresnel(normal, viewDir, 3.0);
    let base = vec3f(0.85, 0.35, 0.25);
    color = base * diffuse + ambient * base + vec3f(1.0, 1.0, 1.0) * (spec * 0.5) + vec3f(0.4, 0.5, 1.0) * (rim * 0.4);
  }
  let mask = fillAA(sdCircle(p, 1.0), 0.01);
  return vec4f(color * mask + vec3f(0.05, 0.05, 0.08) * (1.0 - mask), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default lightingShader;
