/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from '../index.js';

const metaballsShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform float uAspect;
in vec2 vUv;
out vec4 fragColor;
vec3 cosinePalette(float t, vec3 a, vec3 b, vec3 c, vec3 d) {
  vec3 phase = (c * t + d) * 6.28318;
  return a + vec3(cos(phase.x), cos(phase.y), cos(phase.z)) * b;
}
void main() {
  vec2 p = vec2((vUv.x - 0.5) * uAspect, vUv.y - 0.5);
  vec2 b1 = vec2(cos(uTime) * 0.25, sin(uTime * 1.3) * 0.2);
  vec2 b2 = vec2(cos(uTime * 0.7 + 2.0) * 0.3, sin(uTime * 0.9 + 1.0) * 0.22);
  vec2 b3 = vec2(cos(uTime * 1.5 + 4.0) * 0.2, sin(uTime * 0.6 + 3.0) * 0.26);
  float field = 0.0;
  field = field + 0.012 / (distance(p, b1) * distance(p, b1) + 0.001);
  field = field + 0.012 / (distance(p, b2) * distance(p, b2) + 0.001);
  field = field + 0.012 / (distance(p, b3) * distance(p, b3) + 0.001);
  float body = smoothstep(0.9, 1.1, field);
  float glow = pow(smoothstep(0.3, 1.1, field), 3.0) * 0.6;
  vec3 color = cosinePalette(field * 0.2 + uTime * 0.05, vec3(0.5, 0.5, 0.5), vec3(0.5, 0.5, 0.5), vec3(1.0, 1.0, 1.0), vec3(0.3, 0.2, 0.2));
  fragColor = vec4(color * body + color * glow, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn cosinePalette(t : f32, a : vec3f, b : vec3f, c : vec3f, d : vec3f) -> vec3f {
  let phase = (c * t + d) * 6.28318;
  return a + vec3f(cos(phase.x), cos(phase.y), cos(phase.z)) * b;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = vec2f((bm_in.vUv.x - 0.5) * bm_u.uAspect, bm_in.vUv.y - 0.5);
  let b1 = vec2f(cos(bm_u.uTime) * 0.25, sin(bm_u.uTime * 1.3) * 0.2);
  let b2 = vec2f(cos(bm_u.uTime * 0.7 + 2.0) * 0.3, sin(bm_u.uTime * 0.9 + 1.0) * 0.22);
  let b3 = vec2f(cos(bm_u.uTime * 1.5 + 4.0) * 0.2, sin(bm_u.uTime * 0.6 + 3.0) * 0.26);
  var field = 0.0;
  field = field + 0.012 / (distance(p, b1) * distance(p, b1) + 0.001);
  field = field + 0.012 / (distance(p, b2) * distance(p, b2) + 0.001);
  field = field + 0.012 / (distance(p, b3) * distance(p, b3) + 0.001);
  let body = smoothstep(0.9, 1.1, field);
  let glow = pow(smoothstep(0.3, 1.1, field), 3.0) * 0.6;
  let color = cosinePalette(field * 0.2 + bm_u.uTime * 0.05, vec3f(0.5, 0.5, 0.5), vec3f(0.5, 0.5, 0.5), vec3f(1.0, 1.0, 1.0), vec3f(0.3, 0.2, 0.2));
  return vec4f(color * body + color * glow, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default metaballsShader;
