/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from '../index.js';

const pixelateShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float'; uTex: 'sampler2D' }> = {
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let cells = 60.0 + floor(sin(bm_u.uTime * 0.6) * 44.0);
  let q = vec2f(floor(bm_in.vUv.x * cells * bm_u.uAspect) / (cells * bm_u.uAspect), floor(bm_in.vUv.y * cells) / cells);
  return textureSample(uTex, uTex_sampler, q);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float', uTex: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2}],"uniformBlockSize":16},

};

export default pixelateShader;
