/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from '../index.js';

const raymarchShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn sdSphere3(p : vec3f, radius : f32) -> f32 {
  return length(p) - radius;
}
fn sdBox3(p : vec3f, halfSize : vec3f) -> f32 {
  let d = vec3f(abs(p.x) - halfSize.x, abs(p.y) - halfSize.y, abs(p.z) - halfSize.z);
  let outside = length(vec3f(max(d.x, 0.0), max(d.y, 0.0), max(d.z, 0.0)));
  return outside + min(max(d.x, max(d.y, d.z)), 0.0);
}
fn sdTorus3(p : vec3f, radii : vec2f) -> f32 {
  let q = vec2f(length(p.xz) - radii.x, p.y);
  return length(q) - radii.y;
}
fn smoothUnion(d1 : f32, d2 : f32, k : f32) -> f32 {
  let h = clamp(0.5 + 0.5 * (d2 - d1) / k, 0.0, 1.0);
  return mix(d2, d1, h) - k * h * (1.0 - h);
}
fn lambert(normal : vec3f, lightDir : vec3f) -> f32 {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
fn fresnel(normal : vec3f, viewDir : vec3f, power : f32) -> f32 {
  let base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
fn hemisphereLight(normal : vec3f, skyColor : vec3f, groundColor : vec3f) -> vec3f {
  let blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
fn scene(q : vec3f, time : f32) -> f32 {
  let spun = rotate2(q.xz, time * 0.6);
  let box = sdBox3(vec3f(spun.x, q.y, spun.y), vec3f(0.35, 0.35, 0.35));
  let ball = sdSphere3(q - vec3f(cos(time) * 0.7, sin(time * 1.4) * 0.3, sin(time) * 0.4), 0.3);
  let ring = sdTorus3(vec3f(q.x, q.y + 0.45, q.z), vec2f(0.7, 0.08));
  return smoothUnion(smoothUnion(box, ball, 0.25), ring, 0.2);
}
fn sceneNormal(q : vec3f, time : f32) -> vec3f {
  let e = 0.002;
  let dx = scene(q + vec3f(e, 0.0, 0.0), time) - scene(q - vec3f(e, 0.0, 0.0), time);
  let dy = scene(q + vec3f(0.0, e, 0.0), time) - scene(q - vec3f(0.0, e, 0.0), time);
  let dz = scene(q + vec3f(0.0, 0.0, e), time) - scene(q - vec3f(0.0, 0.0, e), time);
  return normalize(vec3f(dx, dy, dz));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = vec2f((bm_in.vUv.x - 0.5) * bm_u.uAspect, bm_in.vUv.y - 0.5);
  let ro = vec3f(0.0, 0.4, 2.4);
  let rd = normalize(vec3f(p.x, p.y - 0.15, -1.4));
  var t = 0.0;
  for (var i = 0.0; i < 72.0; i = i + 1.0) {
    let d = scene(ro + rd * t, bm_u.uTime);
    t = t + clamp(d, 0.001, 0.35);
  }
  let hit = ro + rd * t;
  var color = mix(vec3f(0.06, 0.06, 0.1), vec3f(0.12, 0.1, 0.18), bm_in.vUv.y);
  if (scene(hit, bm_u.uTime) < 0.01) {
    let n = sceneNormal(hit, bm_u.uTime);
    let lightDir = vec3f(0.6, 0.8, 0.4);
    let diffuse = lambert(n, lightDir);
    let ambient = hemisphereLight(n, vec3f(0.25, 0.28, 0.4), vec3f(0.12, 0.09, 0.08));
    let rim = fresnel(n, vec3f(0.0, 0.0, 1.0), 3.0);
    let base = vec3f(0.9, 0.5, 0.25);
    color = base * diffuse + ambient * base + vec3f(0.5, 0.6, 1.0) * (rim * 0.5);
  }
  return vec4f(color, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},

};

export default raymarchShader;
