/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from '../index.js';

const starfieldShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform float uAspect;
in vec2 vUv;
out vec4 fragColor;
vec2 hash22(vec2 p) {
  vec2 k = vec2(dot(p, vec2(127.1, 311.7)), dot(p, vec2(269.5, 183.3)));
  return vec2(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
float hash21(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}
void main() {
  vec2 p = vec2((vUv.x - 0.5) * uAspect, vUv.y - 0.5);
  float brightness = 0.0;
  for (float layer = 1.0; layer <= 3.0; layer = layer + 1.0) {
    vec2 q = p * (layer * 10.0) + vec2(uTime * 0.04 * layer, uTime * 0.01 * layer);
    vec2 cell = vec2(floor(q.x), floor(q.y));
    vec2 star = hash22(cell) * 0.8 + vec2(0.1, 0.1);
    float d = distance(q - cell, star);
    float twinkle = 0.6 + 0.4 * sin(uTime * 3.0 + hash21(cell) * 40.0);
    brightness = brightness + (1.0 - smoothstep(0.0, 0.12 / layer, d)) * twinkle / layer;
  }
  fragColor = vec4(brightness, brightness, brightness * 1.15, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn hash22(p : vec2f) -> vec2f {
  let k = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return vec2f(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
fn hash21(p : vec2f) -> f32 {
  return fract(sin(dot(p, vec2f(127.1, 311.7))) * 43758.5453);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = vec2f((bm_in.vUv.x - 0.5) * bm_u.uAspect, bm_in.vUv.y - 0.5);
  var brightness = 0.0;
  for (var layer = 1.0; layer <= 3.0; layer = layer + 1.0) {
    let q = p * (layer * 10.0) + vec2f(bm_u.uTime * 0.04 * layer, bm_u.uTime * 0.01 * layer);
    let cell = vec2f(floor(q.x), floor(q.y));
    let star = hash22(cell) * 0.8 + vec2f(0.1, 0.1);
    let d = distance(q - cell, star);
    let twinkle = 0.6 + 0.4 * sin(bm_u.uTime * 3.0 + hash21(cell) * 40.0);
    brightness = brightness + (1.0 - smoothstep(0.0, 0.12 / layer, d)) * twinkle / layer;
  }
  return vec4f(brightness, brightness, brightness * 1.15, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default starfieldShader;
