/** Writes src/lib/version.ts with the BroMetal version this build bundles. */
import { readFileSync, writeFileSync } from 'node:fs';

const useNpmPackage = process.env.BROMETAL_SOURCE === 'npm';
const manifest = useNpmPackage
  ? new URL('../../../node_modules/brometal-published/package.json', import.meta.url)
  : new URL('../../brometal/package.json', import.meta.url);
const version = JSON.parse(readFileSync(manifest, 'utf8')).version;
const target = new URL('../src/lib/version.ts', import.meta.url);
writeFileSync(
  target,
  `// Generated by scripts/generate-version.mjs — do not edit.\nexport const BROMETAL_VERSION = '${version}';\n`,
);
console.log(`✓ version.ts → ${version} (${useNpmPackage ? 'published npm package' : 'local workspace'})`);
