/**
 * Writes src/lib/version.ts with the brometal version this build bundles:
 * the local workspace package for dev builds, or the published npm package
 * when BROMETAL_SOURCE=npm — so the header always shows what's really running.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const useNpmPackage = process.env.BROMETAL_SOURCE === 'npm';

function readVersion() {
  if (!useNpmPackage) {
    return JSON.parse(
      readFileSync(new URL('../../brometal/package.json', import.meta.url), 'utf8'),
    ).version;
  }
  const candidates = [
    new URL('../node_modules/brometal-published/package.json', import.meta.url),
    new URL('../../../node_modules/brometal-published/package.json', import.meta.url),
  ];
  for (const candidate of candidates) {
    try {
      return JSON.parse(readFileSync(candidate, 'utf8')).version;
    } catch {
      // try the next location
    }
  }
  throw new Error('generate-version: could not locate brometal-published/package.json');
}

const version = readVersion();
const target = new URL('../src/lib/version.ts', import.meta.url);
writeFileSync(
  target,
  `// Generated by scripts/generate-version.mjs — do not edit.\nexport const BROMETAL_VERSION = '${version}';\n`,
);
console.log(`✓ version.ts → ${version} (${useNpmPackage ? 'published npm package' : 'local workspace'})`);
