/**
 * Compiles the prebuilt shaders in src/shaders/*.shader.ts into committed
 * .gen.ts modules (rewritten to package-relative imports) and regenerates
 * the src/shaders/index.ts barrel. Requires dist/ to be built first.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';

const shadersDir = new URL('../src/shaders/', import.meta.url).pathname;
execFileSync('node', [new URL('../dist/cli/index.js', import.meta.url).pathname, 'dev', '--once', shadersDir], {
  stdio: 'inherit',
});

const genFiles = readdirSync(shadersDir).filter((f) => f.endsWith('.shader.gen.ts')).sort();
const exports = [];
for (const file of genFiles) {
  const full = path.join(shadersDir, file);
  const rewritten = readFileSync(full, 'utf8').replace("from 'brometal';", "from '../index.js';");
  writeFileSync(full, rewritten);
  const base = file.replace('.shader.gen.ts', '');
  const camel = base.split('-').map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1))).join('');
  exports.push(`export { default as ${camel}Shader } from './${base}.shader.gen.js';`);
}
writeFileSync(
  path.join(shadersDir, 'index.ts'),
  `/* Generated by scripts/gen-shaders.mjs — do not edit. */\n${exports.join('\n')}\n`,
);
console.log(`✓ src/shaders: ${genFiles.length} prebuilt shaders, index regenerated`);
