import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { compileProject, genPathFor, isShaderFile, runCli, scanShaderFiles } from '../src/cli/run.js';
import { CUBE_SHADER } from './fixtures.js';

let root: string;

beforeEach(() => {
  root = mkdtempSync(path.join(tmpdir(), 'brometal-cli-'));
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

describe('brometal CLI compilation', () => {
  it('identifies shader files and their generated siblings', () => {
    expect(isShaderFile('cube.shader.ts')).toBe(true);
    expect(isShaderFile('cube.shader.gen.ts')).toBe(false);
    expect(isShaderFile('cube.ts')).toBe(false);
    expect(genPathFor('/a/b/cube.shader.ts')).toBe('/a/b/cube.shader.gen.ts');
  });

  it('scans recursively while skipping node_modules and dist', () => {
    mkdirSync(path.join(root, 'src/shaders'), { recursive: true });
    mkdirSync(path.join(root, 'node_modules/dep'), { recursive: true });
    mkdirSync(path.join(root, 'dist'), { recursive: true });
    writeFileSync(path.join(root, 'src/shaders/cube.shader.ts'), CUBE_SHADER);
    writeFileSync(path.join(root, 'node_modules/dep/skip.shader.ts'), CUBE_SHADER);
    writeFileSync(path.join(root, 'dist/skip.shader.ts'), CUBE_SHADER);
    expect(scanShaderFiles(root)).toEqual([path.join(root, 'src/shaders/cube.shader.ts')]);
  });

  it('writes a typed generated module next to the shader source', () => {
    mkdirSync(path.join(root, 'src/shaders'), { recursive: true });
    const shaderPath = path.join(root, 'src/shaders/cube.shader.ts');
    writeFileSync(shaderPath, CUBE_SHADER);

    const result = compileProject(root, { optimize: false });
    expect(result.errors).toEqual([]);
    expect(result.compiled).toEqual([shaderPath]);

    const generated = readFileSync(genPathFor(shaderPath), 'utf8');
    expect(generated).toContain('Generated by BroMetal');
    expect(generated).toContain(`import type { CompiledShader } from 'brometal';`);
    expect(generated).toContain(
      `CompiledShader<{ aPosition: 'vec3'; aColor: 'vec3' }, Record<string, never>, { uMvp: 'mat4' }>`,
    );
    expect(generated).toContain('@vertex');
    expect(generated).toContain(`attributes: { aPosition: 'vec3', aColor: 'vec3' }`);
    expect(generated).toContain('instanceAttributes: {}');
    expect(generated).toContain(`uniforms: { uMvp: 'mat4' }`);
    expect(generated).toContain('layout: {"attributes"');
    expect(generated).toContain('"location":0');
    expect(generated).toContain('"kind":"m4fv"');
    expect(generated).toContain('export default cubeShader;');
  });

  it('reports errors without writing output for broken shaders', () => {
    const shaderPath = path.join(root, 'broken.shader.ts');
    writeFileSync(shaderPath, `import { shader } from 'brometal';\nexport default shader({});\n`);

    const result = compileProject(root, { optimize: false });
    expect(result.compiled).toEqual([]);
    expect(result.errors).toEqual([shaderPath]);
    expect(() => readFileSync(genPathFor(shaderPath), 'utf8')).toThrow();
  });

});

describe('--js13k naming', () => {
  const named = (name: string): string =>
    CUBE_SHADER.replace('export default shader({', `export const ${name} = shader({`);

  const run = async (): Promise<{ code: number; output: string }> => {
    const quiet = vi.spyOn(console, 'log').mockImplementation(() => {});
    try {
      const code = await runCli(['prod', '--js13k', root]);
      return { code, output: quiet.mock.calls.flat().join('\n') };
    } finally {
      quiet.mockRestore();
    }
  };

  it('takes the name from the export, not the file', async () => {
    writeFileSync(path.join(root, 'anything.shader.ts'), named('Cube'));

    // Reported before the emit step, which needs a built dist this test does
    // not have. `check-template.mjs` covers the written file on a real GPU.
    const { output } = await run();
    expect(output).toContain('anything.shader.ts → Cube');
  });

  it('refuses to guess a name for a default export', async () => {
    writeFileSync(path.join(root, 'cube.shader.ts'), CUBE_SHADER);

    const { code, output } = await run();
    expect(code).toBe(1);
    expect(output).toContain('export const Cube = shader({...})');
    // Nothing written: a half-built shaders.js would concatenate into the game
    // and fail as a blank canvas rather than as this message.
    expect(() => readFileSync(path.join(root, 'dist/shaders.js'), 'utf8')).toThrow();
  });

  it('rejects two shaders claiming the same name', async () => {
    writeFileSync(path.join(root, 'a.shader.ts'), named('Cube'));
    writeFileSync(path.join(root, 'b.shader.ts'), named('Cube'));

    const { code, output } = await run();
    expect(code).toBe(1);
    expect(output).toContain("both export 'Cube'");
  });
});

describe('flag handling', () => {
  it('rejects an unknown flag instead of running anyway', async () => {
    // This used to fall through to an ordinary build and exit 0, which is how
    // `--js13k` against a release that predates it quietly emitted .gen.ts files
    // and failed much later somewhere unrelated.
    const quiet = vi.spyOn(console, 'log').mockImplementation(() => {});
    try {
      await expect(runCli(['dev', '--bogus', root])).resolves.toBe(1);
      expect(quiet.mock.calls.flat().join(' ')).toContain('--bogus');
    } finally {
      quiet.mockRestore();
    }
  });

  it('still accepts the flags it knows', async () => {
    const quiet = vi.spyOn(console, 'log').mockImplementation(() => {});
    try {
      // --once compiles and returns rather than entering watch mode.
      await expect(runCli(['dev', '--once', root])).resolves.toBe(0);
    } finally {
      quiet.mockRestore();
    }
  });
});
