/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const BallsRender: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iIndex: 'float' }, { uViewProj: 'mat4'; uState: 'sampler2D'; uCount: 'float'; uRadius: 'float'; uViewPos: 'vec3'; uLightPos: 'vec3'; uSkyTint: 'vec3'; uGroundTint: 'vec3'; uLightViewProj: 'mat4'; uShadowMap: 'sampler2D'; uRange: 'float'; uTexel: 'float'; uSoftness: 'float'; uBias: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCount : f32,
  uRadius : f32,
  uViewPos : vec3f,
  uLightPos : vec3f,
  uSkyTint : vec3f,
  uGroundTint : vec3f,
  uLightViewProj : mat4x4f,
  uRange : f32,
  uTexel : f32,
  uSoftness : f32,
  uBias : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uState : texture_2d<f32>;
@group(0) @binding(2) var uState_sampler : sampler;
@group(0) @binding(3) var uShadowMap : texture_2d<f32>;
@group(0) @binding(4) var uShadowMap_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iIndex : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vWorld : vec3f,
  @location(2) vSeed : f32,
  @location(3) vSpeed : f32,
}
fn hash11(p : f32) -> f32 {
  return fract(sin(p * 127.1) * 43758.5453);
}
fn specGGX(normal : vec3f, lightDir : vec3f, viewDir : vec3f, roughness : f32) -> f32 {
  let n = normalize(normal);
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  let ndoth = max(dot(n, halfway), 0.0);
  let a = roughness * roughness;
  let a2 = a * a;
  let denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  let ndf = a2 / (3.14159265 * denom * denom);
  let ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
fn fresnel(normal : vec3f, viewDir : vec3f, power : f32) -> f32 {
  let base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
fn hemisphereLight(normal : vec3f, skyColor : vec3f, groundColor : vec3f) -> vec3f {
  let blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
fn cosinePalette(t : f32, a : vec3f, b : vec3f, c : vec3f, d : vec3f) -> vec3f {
  let phase = (c * t + d) * 6.28318;
  return a + vec3f(cos(phase.x), cos(phase.y), cos(phase.z)) * b;
}
fn shadowDepth(worldPos : vec3f, lightPos : vec3f, range : f32) -> f32 {
  return distance(worldPos, lightPos) / range;
}
fn shadowFactor(shadowMap : texture_2d<f32>, shadowMap_sampler : sampler, lightViewProj : mat4x4f, worldPos : vec3f, normal : vec3f, lightPos : vec3f, range : f32, texel : f32, softness : f32, bias : f32) -> f32 {
  let toLight = normalize(lightPos - worldPos);
  let facing = max(dot(normalize(normal), toLight), 0.0);
  let slope = 1.0 + 2.0 * (1.0 - facing);
  let lookup = worldPos + normalize(normal) * (bias * slope);
  let clip = lightViewProj * vec4f(lookup, 1.0);
  let uv = ((clip).xy / (clip).w * vec2f(0.5, -0.5) + vec2f(0.5));
  let reference = shadowDepth(lookup, lightPos, range) - bias * slope / range;
  var visible = 0.0;
  for (var y = -1.0; y < 2.0; y = y + 1.0) {
    for (var x = -1.0; x < 2.0; x = x + 1.0) {
      let tap = uv + vec2f(x, y) * (texel * softness);
      visible = visible + step(reference, textureSampleLevel(shadowMap, shadowMap_sampler, tap, 0.0).x);
    }
  }
  return visible / 9.0;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let u = (bm_in.iIndex + 0.5) / bm_u.uCount * 0.5;
  let centre = textureSampleLevel(uState, uState_sampler, vec2f(u, 0.5), 0.0).xyz;
  let velocity = textureSampleLevel(uState, uState_sampler, vec2f(u + 0.5, 0.5), 0.0).xyz;
  let world = centre + bm_in.aPosition * bm_u.uRadius;
  bm_out.vNormal = bm_in.aNormal;
  bm_out.vWorld = world;
  bm_out.vSeed = hash11(bm_in.iIndex * 0.618 + 0.11);
  bm_out.vSpeed = clamp(length(velocity) * 0.09, 0.0, 1.0);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let n = normalize(bm_in.vNormal);
  let viewDir = normalize(bm_u.uViewPos - bm_in.vWorld);
  let light = normalize(bm_u.uLightPos - bm_in.vWorld);
  let facing = max(dot(n, light), 0.0);
  let sunlight = shadowFactor(uShadowMap, uShadowMap_sampler, bm_u.uLightViewProj, bm_in.vWorld, n, bm_u.uLightPos, bm_u.uRange, bm_u.uTexel, bm_u.uSoftness, bm_u.uBias);
  let base = cosinePalette(bm_in.vSeed, vec3f(0.5, 0.5, 0.52), vec3f(0.45, 0.42, 0.4), vec3f(1.0, 1.0, 1.0), vec3f(0.0, 0.25, 0.55));
  let albedo = mix(base, base + vec3f(0.16, 0.09, 0.02), bm_in.vSpeed);
  let ambient = hemisphereLight(n, bm_u.uSkyTint, bm_u.uGroundTint);
  let diffuse = facing * sunlight;
  let gloss = specGGX(n, light, viewDir, 0.16) * 1.4 * sunlight;
  let sheen = specGGX(n, light, viewDir, 0.55) * 0.25 * sunlight;
  let rim = pow(fresnel(n, viewDir, 4.0), 1.2) * 0.4;
  let lit = albedo * (ambient + vec3f(1.0, 0.97, 0.92) * (diffuse * 0.85));
  let colour = lit + vec3f(1.0, 0.98, 0.95) * (gloss + sheen) + bm_u.uSkyTint * rim;
  return vec4f(colour, distance(bm_in.vWorld, bm_u.uViewPos));
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iIndex: 'float' },
  uniforms: { uViewProj: 'mat4', uState: 'sampler2D', uCount: 'float', uRadius: 'float', uViewPos: 'vec3', uLightPos: 'vec3', uSkyTint: 'vec3', uGroundTint: 'vec3', uLightViewProj: 'mat4', uShadowMap: 'sampler2D', uRange: 'float', uTexel: 'float', uSoftness: 'float', uBias: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iIndex","type":"float","location":2,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uState","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCount","type":"float","kind":"1f","size":1,"offset":64},{"name":"uRadius","type":"float","kind":"1f","size":1,"offset":68},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uLightPos","type":"vec3","kind":"3fv","size":3,"offset":96},{"name":"uSkyTint","type":"vec3","kind":"3fv","size":3,"offset":112},{"name":"uGroundTint","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":144},{"name":"uShadowMap","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uRange","type":"float","kind":"1f","size":1,"offset":208},{"name":"uTexel","type":"float","kind":"1f","size":1,"offset":212},{"name":"uSoftness","type":"float","kind":"1f","size":1,"offset":216},{"name":"uBias","type":"float","kind":"1f","size":1,"offset":220}],"uniformBlockSize":224},

};

export default BallsRender;
