/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const ballsPhysicsShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uState: 'sampler2D'; uCount: 'float'; uDt: 'float'; uGravity: 'vec3'; uBounds: 'vec3'; uRadius: 'float'; uRestitution: 'float'; uFriction: 'float'; uDrag: 'float'; uSleep: 'float'; uSkin: 'float'; uBounceCut: 'float'; uRepair: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition.x, aPosition.y, 0.0, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform sampler2D uState;
uniform float uCount;
uniform float uDt;
uniform vec3 uGravity;
uniform vec3 uBounds;
uniform float uRadius;
uniform float uRestitution;
uniform float uFriction;
uniform float uDrag;
uniform float uSleep;
uniform float uSkin;
uniform float uBounceCut;
uniform float uRepair;
in vec2 vUv;
out vec4 fragColor;
vec3 integrateVelocity(vec3 vel, vec3 accel, float dt) {
  return vel + accel * dt;
}
vec3 separateSpheres(vec3 a, vec3 b, float radiusA, float radiusB, float share) {
  vec3 delta = a - b;
  float dist = max(length(delta), 0.0001);
  float overlap = max(radiusA + radiusB - dist, 0.0);
  return a + delta * (overlap * share / dist);
}
vec3 applyDrag(vec3 vel, float drag, float dt) {
  return vel * exp(-drag * dt);
}
vec3 bounceVelocity(vec3 vel, vec3 normal, float restitution) {
  vec3 result = vel;
  float len = length(normal);
  if (len > 0.0001) {
    vec3 n = normal * (1.0 / len);
    float approach = dot(vel, n);
    if (approach < 0.0) {
      result = vel - n * (approach * (1.0 + restitution));
    }
  }
  return result;
}
vec3 applyFriction(vec3 vel, vec3 normal, float normalImpulse, float friction) {
  vec3 result = vel;
  float len = length(normal);
  if (len > 0.0001) {
    vec3 n = normal * (1.0 / len);
    vec3 along = n * dot(vel, n);
    vec3 across = vel - along;
    float speed = length(across);
    float drop = min(friction * normalImpulse, speed);
    result = along + across * (1.0 - drop / max(speed, 0.0001));
  }
  return result;
}
vec3 restingDamp(vec3 vel, float threshold) {
  return vel * step(threshold, length(vel));
}
vec3 boxContactNormal(vec3 pos, float radius, vec3 halfExtent, float tolerance) {
  vec3 limit = vec3(halfExtent.x - radius - tolerance, halfExtent.y - radius - tolerance, halfExtent.z - radius - tolerance);
  float nx = step(pos.x, -limit.x) - step(limit.x, pos.x);
  float ny = step(pos.y, -limit.y) - step(limit.y, pos.y);
  float nz = step(pos.z, -limit.z) - step(limit.z, pos.z);
  return vec3(nx, ny, nz);
}
vec3 clampInsideBox(vec3 pos, float radius, vec3 halfExtent) {
  vec3 limit = vec3(halfExtent.x - radius, halfExtent.y - radius, halfExtent.z - radius);
  return vec3(clamp(pos.x, -limit.x, limit.x), clamp(pos.y, -limit.y, limit.y), clamp(pos.z, -limit.z, limit.z));
}
float collisionImpulse(vec3 relativeVelocity, vec3 normal, float invMassA, float invMassB, float restitution) {
  float j = 0.0;
  float len = length(normal);
  if (len > 0.0001) {
    vec3 n = normal * (1.0 / len);
    float approach = dot(relativeVelocity, n);
    if (approach < 0.0) {
      j = 0.0 - (1.0 + restitution) * approach / max(invMassA + invMassB, 0.0001);
    }
  }
  return j;
}
void main() {
  float isVelocity = step(0.5, vUv.x);
  float slot = vUv.x - isVelocity * 0.5;
  vec3 pos = texture(uState, vec2(slot, 0.5)).xyz;
  vec3 vel = texture(uState, vec2(slot + 0.5, 0.5)).xyz;
  vec3 free = applyDrag(integrateVelocity(vel, uGravity, uDt), uDrag, uDt);
  float diameter = uRadius * 2.0;
  vec3 push = vec3(0.0, 0.0, 0.0);
  vec3 repair = vec3(0.0, 0.0, 0.0);
  float touching = 0.0;
  float support = 0.0;
  for (float k = 0.0; k < uCount; k = k + 1.0) {
    float u = (k + 0.5) / uCount * 0.5;
    vec3 otherPos = texture(uState, vec2(u, 0.5)).xyz;
    vec3 otherVel = texture(uState, vec2(u + 0.5, 0.5)).xyz;
    vec3 delta = pos - otherPos;
    float dist = length(delta);
    float isSelf = step(dist, 0.0001);
    float contact = step(dist, diameter + uSkin) * (1.0 - isSelf);
    vec3 dir = delta * (1.0 / max(dist, 0.0001));
    float approach = dot(free - otherVel, dir);
    float bounce = uRestitution * step(uBounceCut, -approach);
    float impulse = collisionImpulse(free - otherVel, dir, 1.0, 1.0, bounce);
    push = push + dir * (impulse * contact);
    touching = touching + contact;
    vec3 repaired = separateSpheres(pos, otherPos, uRadius, uRadius, 0.5);
    repair = repair + (repaired - pos) * contact;
    support = support + max(dir.y, 0.0) * contact;
  }
  float share = 1.0 / max(touching, 1.0);
  vec3 stepped = free + push * share;
  vec3 wall = boxContactNormal(pos, uRadius, uBounds, uSkin);
  vec3 incoming = stepped;
  stepped = bounceVelocity(stepped, wall, uRestitution);
  float wallImpulse = length(stepped - incoming);
  stepped = applyFriction(stepped, wall, wallImpulse, uFriction);
  float supported = clamp(max(wall.y, 0.0) + support, 0.0, 1.0);
  stepped = mix(stepped, restingDamp(stepped, uSleep), supported);
  vec3 travelVec = stepped * uDt;
  float a = dot(travelVec, travelVec);
  float travel = 1.0;
  for (float k = 0.0; k < uCount; k = k + 1.0) {
    float u = (k + 0.5) / uCount * 0.5;
    vec3 otherPos = texture(uState, vec2(u, 0.5)).xyz;
    vec3 rel = pos - otherPos;
    float b = 2.0 * dot(rel, travelVec);
    float c = dot(rel, rel) - diameter * diameter;
    float disc = b * b - 4.0 * a * c;
    float hit = (0.0 - b - sqrt(max(disc, 0.0))) / max(2.0 * a, 0.000001);
    float real = step(0.000001, disc) * step(0.000001, a) * step(0.000001, c);
    float within = step(0.0, hit) * step(hit, 1.0);
    travel = min(travel, mix(1.0, hit, real * within));
  }
  vec3 advanced = pos + travelVec * (travel * 0.999) + repair * (share * uRepair);
  vec3 moved = clampInsideBox(advanced, uRadius, uBounds);
  fragColor = vec4(mix(moved, stepped, isVelocity), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uCount : f32,
  uDt : f32,
  uGravity : vec3f,
  uBounds : vec3f,
  uRadius : f32,
  uRestitution : f32,
  uFriction : f32,
  uDrag : f32,
  uSleep : f32,
  uSkin : f32,
  uBounceCut : f32,
  uRepair : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uState : texture_2d<f32>;
@group(0) @binding(2) var uState_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn integrateVelocity(vel : vec3f, accel : vec3f, dt : f32) -> vec3f {
  return vel + accel * dt;
}
fn separateSpheres(a : vec3f, b : vec3f, radiusA : f32, radiusB : f32, share : f32) -> vec3f {
  let delta = a - b;
  let dist = max(length(delta), 0.0001);
  let overlap = max(radiusA + radiusB - dist, 0.0);
  return a + delta * (overlap * share / dist);
}
fn applyDrag(vel : vec3f, drag : f32, dt : f32) -> vec3f {
  return vel * exp(-drag * dt);
}
fn bounceVelocity(vel : vec3f, normal : vec3f, restitution : f32) -> vec3f {
  var result = vel;
  let len = length(normal);
  if (len > 0.0001) {
    let n = normal * (1.0 / len);
    let approach = dot(vel, n);
    if (approach < 0.0) {
      result = vel - n * (approach * (1.0 + restitution));
    }
  }
  return result;
}
fn applyFriction(vel : vec3f, normal : vec3f, normalImpulse : f32, friction : f32) -> vec3f {
  var result = vel;
  let len = length(normal);
  if (len > 0.0001) {
    let n = normal * (1.0 / len);
    let along = n * dot(vel, n);
    let across = vel - along;
    let speed = length(across);
    let drop = min(friction * normalImpulse, speed);
    result = along + across * (1.0 - drop / max(speed, 0.0001));
  }
  return result;
}
fn restingDamp(vel : vec3f, threshold : f32) -> vec3f {
  return vel * step(threshold, length(vel));
}
fn boxContactNormal(pos : vec3f, radius : f32, halfExtent : vec3f, tolerance : f32) -> vec3f {
  let limit = vec3f(halfExtent.x - radius - tolerance, halfExtent.y - radius - tolerance, halfExtent.z - radius - tolerance);
  let nx = step(pos.x, -limit.x) - step(limit.x, pos.x);
  let ny = step(pos.y, -limit.y) - step(limit.y, pos.y);
  let nz = step(pos.z, -limit.z) - step(limit.z, pos.z);
  return vec3f(nx, ny, nz);
}
fn clampInsideBox(pos : vec3f, radius : f32, halfExtent : vec3f) -> vec3f {
  let limit = vec3f(halfExtent.x - radius, halfExtent.y - radius, halfExtent.z - radius);
  return vec3f(clamp(pos.x, -limit.x, limit.x), clamp(pos.y, -limit.y, limit.y), clamp(pos.z, -limit.z, limit.z));
}
fn collisionImpulse(relativeVelocity : vec3f, normal : vec3f, invMassA : f32, invMassB : f32, restitution : f32) -> f32 {
  var j = 0.0;
  let len = length(normal);
  if (len > 0.0001) {
    let n = normal * (1.0 / len);
    let approach = dot(relativeVelocity, n);
    if (approach < 0.0) {
      j = 0.0 - (1.0 + restitution) * approach / max(invMassA + invMassB, 0.0001);
    }
  }
  return j;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let isVelocity = step(0.5, bm_in.vUv.x);
  let slot = bm_in.vUv.x - isVelocity * 0.5;
  let pos = textureSample(uState, uState_sampler, vec2f(slot, 0.5)).xyz;
  let vel = textureSample(uState, uState_sampler, vec2f(slot + 0.5, 0.5)).xyz;
  let free = applyDrag(integrateVelocity(vel, bm_u.uGravity, bm_u.uDt), bm_u.uDrag, bm_u.uDt);
  let diameter = bm_u.uRadius * 2.0;
  var push = vec3f(0.0, 0.0, 0.0);
  var repair = vec3f(0.0, 0.0, 0.0);
  var touching = 0.0;
  var support = 0.0;
  for (var k = 0.0; k < bm_u.uCount; k = k + 1.0) {
    let u = (k + 0.5) / bm_u.uCount * 0.5;
    let otherPos = textureSample(uState, uState_sampler, vec2f(u, 0.5)).xyz;
    let otherVel = textureSample(uState, uState_sampler, vec2f(u + 0.5, 0.5)).xyz;
    let delta = pos - otherPos;
    let dist = length(delta);
    let isSelf = step(dist, 0.0001);
    let contact = step(dist, diameter + bm_u.uSkin) * (1.0 - isSelf);
    let dir = delta * (1.0 / max(dist, 0.0001));
    let approach = dot(free - otherVel, dir);
    let bounce = bm_u.uRestitution * step(bm_u.uBounceCut, -approach);
    let impulse = collisionImpulse(free - otherVel, dir, 1.0, 1.0, bounce);
    push = push + dir * (impulse * contact);
    touching = touching + contact;
    let repaired = separateSpheres(pos, otherPos, bm_u.uRadius, bm_u.uRadius, 0.5);
    repair = repair + (repaired - pos) * contact;
    support = support + max(dir.y, 0.0) * contact;
  }
  let share = 1.0 / max(touching, 1.0);
  var stepped = free + push * share;
  let wall = boxContactNormal(pos, bm_u.uRadius, bm_u.uBounds, bm_u.uSkin);
  let incoming = stepped;
  stepped = bounceVelocity(stepped, wall, bm_u.uRestitution);
  let wallImpulse = length(stepped - incoming);
  stepped = applyFriction(stepped, wall, wallImpulse, bm_u.uFriction);
  let supported = clamp(max(wall.y, 0.0) + support, 0.0, 1.0);
  stepped = mix(stepped, restingDamp(stepped, bm_u.uSleep), supported);
  let travelVec = stepped * bm_u.uDt;
  let a = dot(travelVec, travelVec);
  var travel = 1.0;
  for (var k = 0.0; k < bm_u.uCount; k = k + 1.0) {
    let u = (k + 0.5) / bm_u.uCount * 0.5;
    let otherPos = textureSample(uState, uState_sampler, vec2f(u, 0.5)).xyz;
    let rel = pos - otherPos;
    let b = 2.0 * dot(rel, travelVec);
    let c = dot(rel, rel) - diameter * diameter;
    let disc = b * b - 4.0 * a * c;
    let hit = (0.0 - b - sqrt(max(disc, 0.0))) / max(2.0 * a, 0.000001);
    let real = step(0.000001, disc) * step(0.000001, a) * step(0.000001, c);
    let within = step(0.0, hit) * step(hit, 1.0);
    travel = min(travel, mix(1.0, hit, real * within));
  }
  let advanced = pos + travelVec * (travel * 0.999) + repair * (share * bm_u.uRepair);
  let moved = clampInsideBox(advanced, bm_u.uRadius, bm_u.uBounds);
  return vec4f(mix(moved, stepped, isVelocity), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uState: 'sampler2D', uCount: 'float', uDt: 'float', uGravity: 'vec3', uBounds: 'vec3', uRadius: 'float', uRestitution: 'float', uFriction: 'float', uDrag: 'float', uSleep: 'float', uSkin: 'float', uBounceCut: 'float', uRepair: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uState","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCount","type":"float","kind":"1f","size":1,"offset":0},{"name":"uDt","type":"float","kind":"1f","size":1,"offset":4},{"name":"uGravity","type":"vec3","kind":"3fv","size":3,"offset":16},{"name":"uBounds","type":"vec3","kind":"3fv","size":3,"offset":32},{"name":"uRadius","type":"float","kind":"1f","size":1,"offset":44},{"name":"uRestitution","type":"float","kind":"1f","size":1,"offset":48},{"name":"uFriction","type":"float","kind":"1f","size":1,"offset":52},{"name":"uDrag","type":"float","kind":"1f","size":1,"offset":56},{"name":"uSleep","type":"float","kind":"1f","size":1,"offset":60},{"name":"uSkin","type":"float","kind":"1f","size":1,"offset":64},{"name":"uBounceCut","type":"float","kind":"1f","size":1,"offset":68},{"name":"uRepair","type":"float","kind":"1f","size":1,"offset":72}],"uniformBlockSize":80},
};

export default ballsPhysicsShader;
