/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const ballsRenderShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iIndex: 'float' }, { uViewProj: 'mat4'; uState: 'sampler2D'; uCount: 'float'; uRadius: 'float'; uViewPos: 'vec3'; uLightPos: 'vec3'; uSkyTint: 'vec3'; uGroundTint: 'vec3'; uLightViewProj: 'mat4'; uShadowMap: 'sampler2D'; uRange: 'float'; uTexel: 'float'; uSoftness: 'float'; uBias: 'float'; uNormalOffset: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 aNormal;
layout(location = 2) in float iIndex;
uniform mat4 uViewProj;
uniform sampler2D uState;
uniform float uCount;
uniform float uRadius;
out vec3 vNormal;
out vec3 vWorld;
out float vSeed;
out float vSpeed;
float hash11(float p) {
  return fract(sin(p * 127.1) * 43758.5453);
}
void main() {
  float u = (iIndex + 0.5) / uCount * 0.5;
  vec3 centre = texture(uState, vec2(u, 0.5)).xyz;
  vec3 velocity = texture(uState, vec2(u + 0.5, 0.5)).xyz;
  vec3 world = centre + aPosition * uRadius;
  vNormal = aNormal;
  vWorld = world;
  vSeed = hash11(iIndex * 0.618 + 0.11);
  vSpeed = clamp(length(velocity) * 0.09, 0.0, 1.0);
  gl_Position = uViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform vec3 uViewPos;
uniform vec3 uLightPos;
uniform vec3 uSkyTint;
uniform vec3 uGroundTint;
uniform mat4 uLightViewProj;
uniform sampler2D uShadowMap;
uniform float uRange;
uniform float uTexel;
uniform float uSoftness;
uniform float uBias;
uniform float uNormalOffset;
in vec3 vNormal;
in vec3 vWorld;
in float vSeed;
in float vSpeed;
out vec4 fragColor;
float specGGX(vec3 normal, vec3 lightDir, vec3 viewDir, float roughness) {
  vec3 n = normalize(normal);
  vec3 halfway = normalize(normalize(lightDir) + normalize(viewDir));
  float ndoth = max(dot(n, halfway), 0.0);
  float a = roughness * roughness;
  float a2 = a * a;
  float denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  float ndf = a2 / (3.14159265 * denom * denom);
  float ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
float fresnel(vec3 normal, vec3 viewDir, float power) {
  float base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
vec3 hemisphereLight(vec3 normal, vec3 skyColor, vec3 groundColor) {
  float blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
vec3 cosinePalette(float t, vec3 a, vec3 b, vec3 c, vec3 d) {
  vec3 phase = (c * t + d) * 6.28318;
  return a + vec3(cos(phase.x), cos(phase.y), cos(phase.z)) * b;
}
void main() {
  vec3 n = normalize(vNormal);
  vec3 viewDir = normalize(uViewPos - vWorld);
  vec3 light = normalize(uLightPos - vWorld);
  float facing = max(dot(n, light), 0.0);
  float slope = 1.0 + 2.0 * (1.0 - facing);
  vec3 lookup = vWorld + n * (uNormalOffset * slope);
  vec2 uv = ((uLightViewProj * vec4(lookup, 1.0)).xy / (uLightViewProj * vec4(lookup, 1.0)).w * 0.5 + 0.5);
  float reference = (distance(lookup, uLightPos) - uBias * slope) / uRange;
  float visible = 0.0;
  for (float sy = -1.0; sy < 2.0; sy = sy + 1.0) {
    for (float sx = -1.0; sx < 2.0; sx = sx + 1.0) {
      vec2 tap = uv + vec2(sx, sy) * (uTexel * uSoftness);
      visible = visible + step(reference, texture(uShadowMap, tap).x);
    }
  }
  float sunlight = visible / 9.0;
  vec3 base = cosinePalette(vSeed, vec3(0.5, 0.5, 0.52), vec3(0.45, 0.42, 0.4), vec3(1.0, 1.0, 1.0), vec3(0.0, 0.25, 0.55));
  vec3 albedo = mix(base, base + vec3(0.16, 0.09, 0.02), vSpeed);
  vec3 ambient = hemisphereLight(n, uSkyTint, uGroundTint);
  float diffuse = facing * sunlight;
  float gloss = specGGX(n, light, viewDir, 0.16) * 1.4 * sunlight;
  float sheen = specGGX(n, light, viewDir, 0.55) * 0.25 * sunlight;
  float rim = pow(fresnel(n, viewDir, 4.0), 1.2) * 0.4;
  vec3 lit = albedo * (ambient + vec3(1.0, 0.97, 0.92) * (diffuse * 0.85));
  vec3 colour = lit + vec3(1.0, 0.98, 0.95) * (gloss + sheen) + uSkyTint * rim;
  fragColor = vec4(colour, distance(vWorld, uViewPos));
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCount : f32,
  uRadius : f32,
  uViewPos : vec3f,
  uLightPos : vec3f,
  uSkyTint : vec3f,
  uGroundTint : vec3f,
  uLightViewProj : mat4x4f,
  uRange : f32,
  uTexel : f32,
  uSoftness : f32,
  uBias : f32,
  uNormalOffset : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uState : texture_2d<f32>;
@group(0) @binding(2) var uState_sampler : sampler;
@group(0) @binding(3) var uShadowMap : texture_2d<f32>;
@group(0) @binding(4) var uShadowMap_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iIndex : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vWorld : vec3f,
  @location(2) vSeed : f32,
  @location(3) vSpeed : f32,
}
fn hash11(p : f32) -> f32 {
  return fract(sin(p * 127.1) * 43758.5453);
}
fn specGGX(normal : vec3f, lightDir : vec3f, viewDir : vec3f, roughness : f32) -> f32 {
  let n = normalize(normal);
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  let ndoth = max(dot(n, halfway), 0.0);
  let a = roughness * roughness;
  let a2 = a * a;
  let denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  let ndf = a2 / (3.14159265 * denom * denom);
  let ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
fn fresnel(normal : vec3f, viewDir : vec3f, power : f32) -> f32 {
  let base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
fn hemisphereLight(normal : vec3f, skyColor : vec3f, groundColor : vec3f) -> vec3f {
  let blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
fn cosinePalette(t : f32, a : vec3f, b : vec3f, c : vec3f, d : vec3f) -> vec3f {
  let phase = (c * t + d) * 6.28318;
  return a + vec3f(cos(phase.x), cos(phase.y), cos(phase.z)) * b;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let u = (bm_in.iIndex + 0.5) / bm_u.uCount * 0.5;
  let centre = textureSampleLevel(uState, uState_sampler, vec2f(u, 0.5), 0.0).xyz;
  let velocity = textureSampleLevel(uState, uState_sampler, vec2f(u + 0.5, 0.5), 0.0).xyz;
  let world = centre + bm_in.aPosition * bm_u.uRadius;
  bm_out.vNormal = bm_in.aNormal;
  bm_out.vWorld = world;
  bm_out.vSeed = hash11(bm_in.iIndex * 0.618 + 0.11);
  bm_out.vSpeed = clamp(length(velocity) * 0.09, 0.0, 1.0);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let n = normalize(bm_in.vNormal);
  let viewDir = normalize(bm_u.uViewPos - bm_in.vWorld);
  let light = normalize(bm_u.uLightPos - bm_in.vWorld);
  let facing = max(dot(n, light), 0.0);
  let slope = 1.0 + 2.0 * (1.0 - facing);
  let lookup = bm_in.vWorld + n * (bm_u.uNormalOffset * slope);
  let uv = ((bm_u.uLightViewProj * vec4f(lookup, 1.0)).xy / (bm_u.uLightViewProj * vec4f(lookup, 1.0)).w * vec2f(0.5, -0.5) + vec2f(0.5));
  let reference = (distance(lookup, bm_u.uLightPos) - bm_u.uBias * slope) / bm_u.uRange;
  var visible = 0.0;
  for (var sy = -1.0; sy < 2.0; sy = sy + 1.0) {
    for (var sx = -1.0; sx < 2.0; sx = sx + 1.0) {
      let tap = uv + vec2f(sx, sy) * (bm_u.uTexel * bm_u.uSoftness);
      visible = visible + step(reference, textureSample(uShadowMap, uShadowMap_sampler, tap).x);
    }
  }
  let sunlight = visible / 9.0;
  let base = cosinePalette(bm_in.vSeed, vec3f(0.5, 0.5, 0.52), vec3f(0.45, 0.42, 0.4), vec3f(1.0, 1.0, 1.0), vec3f(0.0, 0.25, 0.55));
  let albedo = mix(base, base + vec3f(0.16, 0.09, 0.02), bm_in.vSpeed);
  let ambient = hemisphereLight(n, bm_u.uSkyTint, bm_u.uGroundTint);
  let diffuse = facing * sunlight;
  let gloss = specGGX(n, light, viewDir, 0.16) * 1.4 * sunlight;
  let sheen = specGGX(n, light, viewDir, 0.55) * 0.25 * sunlight;
  let rim = pow(fresnel(n, viewDir, 4.0), 1.2) * 0.4;
  let lit = albedo * (ambient + vec3f(1.0, 0.97, 0.92) * (diffuse * 0.85));
  let colour = lit + vec3f(1.0, 0.98, 0.95) * (gloss + sheen) + bm_u.uSkyTint * rim;
  return vec4f(colour, distance(bm_in.vWorld, bm_u.uViewPos));
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iIndex: 'float' },
  uniforms: { uViewProj: 'mat4', uState: 'sampler2D', uCount: 'float', uRadius: 'float', uViewPos: 'vec3', uLightPos: 'vec3', uSkyTint: 'vec3', uGroundTint: 'vec3', uLightViewProj: 'mat4', uShadowMap: 'sampler2D', uRange: 'float', uTexel: 'float', uSoftness: 'float', uBias: 'float', uNormalOffset: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iIndex","type":"float","location":2,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uState","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCount","type":"float","kind":"1f","size":1,"offset":64},{"name":"uRadius","type":"float","kind":"1f","size":1,"offset":68},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uLightPos","type":"vec3","kind":"3fv","size":3,"offset":96},{"name":"uSkyTint","type":"vec3","kind":"3fv","size":3,"offset":112},{"name":"uGroundTint","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":144},{"name":"uShadowMap","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uRange","type":"float","kind":"1f","size":1,"offset":208},{"name":"uTexel","type":"float","kind":"1f","size":1,"offset":212},{"name":"uSoftness","type":"float","kind":"1f","size":1,"offset":216},{"name":"uBias","type":"float","kind":"1f","size":1,"offset":220},{"name":"uNormalOffset","type":"float","kind":"1f","size":1,"offset":224}],"uniformBlockSize":240},
};

export default ballsRenderShader;
