/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const ballsSeedShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uCount: 'float'; uBounds: 'vec3'; uRadius: 'float'; uSpread: 'float' }> = {
  vertexSrc: `#version 300 es
precision highp float;
precision highp int;
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition.x, aPosition.y, 0.0, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
precision highp int;
uniform float uCount;
uniform vec3 uBounds;
uniform float uRadius;
uniform float uSpread;
in vec2 vUv;
out vec4 fragColor;
float hash11(float p) {
  return fract(sin(p * 127.1) * 43758.5453);
}
void main() {
  float isVelocity = step(0.5, vUv.x);
  float slot = vUv.x - isVelocity * 0.5;
  float index = floor(slot * 2.0 * uCount);
  vec3 inner = vec3(uBounds.x - uRadius, uBounds.y - uRadius, uBounds.z - uRadius);
  float span = inner.x * 2.0;
  float columns = max(floor(span / (uRadius * 2.35)), 1.0);
  float spacing = span / columns;
  float cx = mod(index, columns);
  float cz = mod(floor(index / columns), columns);
  float cy = floor(index / (columns * columns));
  float slack = (spacing - uRadius * 2.0) * 0.4;
  vec3 position = vec3(0.0 - inner.x + (cx + 0.5) * spacing + (hash11(index * 1.7 + 0.3) - 0.5) * slack, inner.y - (cy + 0.5) * spacing + (hash11(index * 3.1 + 5.7) - 0.5) * slack, 0.0 - inner.z + (cz + 0.5) * spacing + (hash11(index * 2.3 + 9.1) - 0.5) * slack);
  vec3 velocity = vec3((hash11(index * 7.7 + 1.9) - 0.5) * uSpread, (hash11(index * 4.9 + 3.3) - 0.5) * uSpread * 0.4, (hash11(index * 6.1 + 8.5) - 0.5) * uSpread);
  fragColor = vec4(mix(position, velocity, isVelocity), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uCount : f32,
  uBounds : vec3f,
  uRadius : f32,
  uSpread : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn hash11(p : f32) -> f32 {
  return fract(sin(p * 127.1) * 43758.5453);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let isVelocity = step(0.5, bm_in.vUv.x);
  let slot = bm_in.vUv.x - isVelocity * 0.5;
  let index = floor(slot * 2.0 * bm_u.uCount);
  let inner = vec3f(bm_u.uBounds.x - bm_u.uRadius, bm_u.uBounds.y - bm_u.uRadius, bm_u.uBounds.z - bm_u.uRadius);
  let span = inner.x * 2.0;
  let columns = max(floor(span / (bm_u.uRadius * 2.35)), 1.0);
  let spacing = span / columns;
  let cx = ((index) - (columns) * floor((index) / (columns)));
  let cz = ((floor(index / columns)) - (columns) * floor((floor(index / columns)) / (columns)));
  let cy = floor(index / (columns * columns));
  let slack = (spacing - bm_u.uRadius * 2.0) * 0.4;
  let position = vec3f(0.0 - inner.x + (cx + 0.5) * spacing + (hash11(index * 1.7 + 0.3) - 0.5) * slack, inner.y - (cy + 0.5) * spacing + (hash11(index * 3.1 + 5.7) - 0.5) * slack, 0.0 - inner.z + (cz + 0.5) * spacing + (hash11(index * 2.3 + 9.1) - 0.5) * slack);
  let velocity = vec3f((hash11(index * 7.7 + 1.9) - 0.5) * bm_u.uSpread, (hash11(index * 4.9 + 3.3) - 0.5) * bm_u.uSpread * 0.4, (hash11(index * 6.1 + 8.5) - 0.5) * bm_u.uSpread);
  return vec4f(mix(position, velocity, isVelocity), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uCount: 'float', uBounds: 'vec3', uRadius: 'float', uSpread: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uCount","type":"float","kind":"1f","size":1,"offset":0},{"name":"uBounds","type":"vec3","kind":"3fv","size":3,"offset":16},{"name":"uRadius","type":"float","kind":"1f","size":1,"offset":28},{"name":"uSpread","type":"float","kind":"1f","size":1,"offset":32}],"uniformBlockSize":48},

};

export default ballsSeedShader;
