/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const ballsGlassShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uBounds: 'vec3'; uViewPos: 'vec3'; uLightPos: 'vec3'; uSkyTint: 'vec3'; uHorizon: 'vec3'; uGlassTint: 'vec3'; uEdge: 'float'; uGlare: 'float'; uScene: 'sampler2D'; uReach: 'float'; uThickness: 'float'; uMirror: 'float' }> = {
  vertexSrc: `#version 300 es
precision highp float;
precision highp int;
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 aNormal;
uniform mat4 uViewProj;
uniform vec3 uBounds;
out vec3 vNormal;
out vec3 vWorld;
out vec3 vLocal;
void main() {
  vec3 world = vec3(aPosition.x * uBounds.x * 2.0, aPosition.y * uBounds.y * 2.0, aPosition.z * uBounds.z * 2.0);
  vNormal = aNormal;
  vWorld = world;
  vLocal = aPosition;
  gl_Position = uViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp sampler3D;
uniform mat4 uViewProj;
uniform vec3 uViewPos;
uniform vec3 uLightPos;
uniform vec3 uSkyTint;
uniform vec3 uHorizon;
uniform vec3 uGlassTint;
uniform float uEdge;
uniform float uGlare;
uniform sampler2D uScene;
uniform float uReach;
uniform float uThickness;
uniform float uMirror;
in vec3 vNormal;
in vec3 vWorld;
in vec3 vLocal;
out vec4 fragColor;
float fresnel(vec3 normal, vec3 viewDir, float power) {
  float base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
float specGGX(vec3 normal, vec3 lightDir, vec3 viewDir, float roughness) {
  vec3 n = normalize(normal);
  vec3 halfway = normalize(normalize(lightDir) + normalize(viewDir));
  float ndoth = max(dot(n, halfway), 0.0);
  float a = roughness * roughness;
  float a2 = a * a;
  float denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  float ndf = a2 / (3.14159265 * denom * denom);
  float ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
vec3 studioEnv(vec3 dir, vec3 sky, vec3 horizon, vec3 keyDir) {
  float up = clamp(dir.y * 0.5 + 0.5, 0.0, 1.0);
  vec3 base = mix(horizon * 0.22, sky, smoothstep(0.4, 0.98, up));
  float band = pow(1.0 - abs(dir.y), 7.0) * 0.34;
  float key = max(dot(dir, keyDir), 0.0);
  float core = pow(key, 600.0) * 45.0;
  float soft = pow(key, 40.0) * 1.4;
  float spill = pow(key, 5.0) * 0.18;
  float boxA = max(dot(dir, normalize(vec3(0.0 - 0.62, 0.3, 0.72))), 0.0);
  float boxB = max(dot(dir, normalize(vec3(0.78, 0.16, 0.0 - 0.6))), 0.0);
  float rigA = pow(boxA, 20.0) * 2.2 + pow(boxA, 4.0) * 0.3;
  float rigB = pow(boxB, 30.0) * 1.6 + pow(boxB, 5.0) * 0.2;
  return base + horizon * band + vec3(1.0, 0.98, 0.94) * (core + soft + spill) + vec3(0.96, 0.98, 1.0) * rigA + vec3(1.0, 0.97, 0.93) * rigB;
}
void main() {
  vec3 viewDir = normalize(uViewPos - vWorld);
  vec3 light = normalize(uLightPos - vWorld);
  vec3 raw = normalize(vNormal);
  vec3 n = raw * mix(0.0 - 1.0, 1.0, step(0.0, dot(raw, viewDir)));
  float cosTheta = clamp(dot(n, viewDir), 0.0, 1.0);
  float f = 0.04 + 0.96 * pow(1.0 - cosTheta, 5.0);
  vec3 bounced = reflect(viewDir * (0.0 - 1.0), n);
  vec3 rayEnd = vWorld + bounced * uReach;
  vec2 uvStart = ((uViewProj * vec4(vWorld, 1.0)).xy / (uViewProj * vec4(vWorld, 1.0)).w * 0.5 + 0.5);
  vec2 uvEnd = ((uViewProj * vec4(rayEnd, 1.0)).xy / (uViewProj * vec4(rayEnd, 1.0)).w * 0.5 + 0.5);
  float depthStart = distance(vWorld, uViewPos);
  float depthEnd = distance(rayEnd, uViewPos);
  vec2 hitUv = vec2(0.5, 0.5);
  float hitAlong = 1.0;
  float found = 0.0;
  float wasInFront = step(depthStart, texture(uScene, uvStart).w);
  for (float i = 1.0; i < 19.0; i = i + 1.0) {
    float along = i / 18.0;
    vec2 uv = mix(uvStart, uvEnd, along);
    float rayDepth = 1.0 / mix(1.0 / depthStart, 1.0 / depthEnd, along);
    vec4 sampled = texture(uScene, uv);
    float onScreen = step(0.0, uv.x) * step(uv.x, 1.0) * step(0.0, uv.y) * step(uv.y, 1.0);
    float nowBehind = step(sampled.w, rayDepth);
    float shallow = step(rayDepth - sampled.w, uThickness);
    float isHit = onScreen * wasInFront * nowBehind * shallow;
    float take = isHit * (1.0 - found);
    hitUv = mix(hitUv, uv, take);
    hitAlong = mix(hitAlong, along, take);
    found = max(found, isHit);
    wasInFront = step(rayDepth, sampled.w);
  }
  float lo = hitAlong - 1.0 / 18.0;
  float hi = hitAlong;
  for (float r = 0.0; r < 5.0; r = r + 1.0) {
    float mid = (lo + hi) * 0.5;
    vec2 probeUv = mix(uvStart, uvEnd, mid);
    float probeDepth = 1.0 / mix(1.0 / depthStart, 1.0 / depthEnd, mid);
    float behind = step(texture(uScene, probeUv).w, probeDepth);
    lo = mix(lo, mid, 1.0 - behind);
    hi = mix(hi, mid, behind);
  }
  vec2 refinedUv = mix(uvStart, uvEnd, hi);
  vec3 hitColour = texture(uScene, refinedUv).xyz;
  vec3 env = studioEnv(bounced, uSkyTint, uHorizon, light);
  float edge = smoothstep(0.0, 0.14, hitUv.x) * smoothstep(0.0, 0.14, 1.0 - hitUv.x) * smoothstep(0.0, 0.14, hitUv.y) * smoothstep(0.0, 0.14, 1.0 - hitUv.y);
  float grazing = smoothstep(0.12, 0.4, abs(dot(bounced, viewDir)));
  float confidence = found * edge * grazing * uMirror;
  vec3 mirror = mix(env, hitColour * 1.35 + env * 0.2, confidence);
  float hotspot = min(specGGX(n, light, viewDir, 0.05), 14.0) * 2.4;
  float bloom = specGGX(n, light, viewDir, 0.34) * 0.4;
  vec3 glare = vec3(1.0, 0.985, 0.95) * ((hotspot + bloom) * uGlare);
  float ax = abs(vLocal.x);
  float ay = abs(vLocal.y);
  float az = abs(vLocal.z);
  float secondAxis = max(min(ax, ay), min(max(ax, ay), az));
  float seam = smoothstep(0.45, 0.5, secondAxis);
  float corner = smoothstep(0.42, 0.5, min(min(ax, ay), az));
  float rim = fresnel(n, viewDir, 3.4);
  vec3 edging = (uSkyTint + vec3(0.24, 0.3, 0.28)) * ((seam * 0.75 + corner * 1.4) * uEdge);
  vec3 absorb = mix(vec3(1.0, 1.0, 1.0), uGlassTint, clamp(1.0 - cosTheta, 0.0, 1.0) * 0.85);
  vec3 reflected = mirror * absorb * f + glare + edging;
  float glareLuma = clamp(length(glare) * 0.5, 0.0, 1.0);
  float alpha = clamp(f * 0.92 + glareLuma + (seam * 0.32 + corner * 0.62) * uEdge + rim * 0.05, 0.02, 0.985);
  fragColor = vec4(reflected * (1.0 / alpha), alpha);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uBounds : vec3f,
  uViewPos : vec3f,
  uLightPos : vec3f,
  uSkyTint : vec3f,
  uHorizon : vec3f,
  uGlassTint : vec3f,
  uEdge : f32,
  uGlare : f32,
  uReach : f32,
  uThickness : f32,
  uMirror : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uScene : texture_2d<f32>;
@group(0) @binding(2) var uScene_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vWorld : vec3f,
  @location(2) vLocal : vec3f,
}
fn fresnel(normal : vec3f, viewDir : vec3f, power : f32) -> f32 {
  let base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
fn specGGX(normal : vec3f, lightDir : vec3f, viewDir : vec3f, roughness : f32) -> f32 {
  let n = normalize(normal);
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  let ndoth = max(dot(n, halfway), 0.0);
  let a = roughness * roughness;
  let a2 = a * a;
  let denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  let ndf = a2 / (3.14159265 * denom * denom);
  let ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
fn studioEnv(dir : vec3f, sky : vec3f, horizon : vec3f, keyDir : vec3f) -> vec3f {
  let up = clamp(dir.y * 0.5 + 0.5, 0.0, 1.0);
  let base = mix(horizon * 0.22, sky, smoothstep(0.4, 0.98, up));
  let band = pow(1.0 - abs(dir.y), 7.0) * 0.34;
  let key = max(dot(dir, keyDir), 0.0);
  let core = pow(key, 600.0) * 45.0;
  let soft = pow(key, 40.0) * 1.4;
  let spill = pow(key, 5.0) * 0.18;
  let boxA = max(dot(dir, normalize(vec3f(0.0 - 0.62, 0.3, 0.72))), 0.0);
  let boxB = max(dot(dir, normalize(vec3f(0.78, 0.16, 0.0 - 0.6))), 0.0);
  let rigA = pow(boxA, 20.0) * 2.2 + pow(boxA, 4.0) * 0.3;
  let rigB = pow(boxB, 30.0) * 1.6 + pow(boxB, 5.0) * 0.2;
  return base + horizon * band + vec3f(1.0, 0.98, 0.94) * (core + soft + spill) + vec3f(0.96, 0.98, 1.0) * rigA + vec3f(1.0, 0.97, 0.93) * rigB;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = vec3f(bm_in.aPosition.x * bm_u.uBounds.x * 2.0, bm_in.aPosition.y * bm_u.uBounds.y * 2.0, bm_in.aPosition.z * bm_u.uBounds.z * 2.0);
  bm_out.vNormal = bm_in.aNormal;
  bm_out.vWorld = world;
  bm_out.vLocal = bm_in.aPosition;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let viewDir = normalize(bm_u.uViewPos - bm_in.vWorld);
  let light = normalize(bm_u.uLightPos - bm_in.vWorld);
  let raw = normalize(bm_in.vNormal);
  let n = raw * mix(0.0 - 1.0, 1.0, step(0.0, dot(raw, viewDir)));
  let cosTheta = clamp(dot(n, viewDir), 0.0, 1.0);
  let f = 0.04 + 0.96 * pow(1.0 - cosTheta, 5.0);
  let bounced = reflect(viewDir * (0.0 - 1.0), n);
  let rayEnd = bm_in.vWorld + bounced * bm_u.uReach;
  let uvStart = ((bm_u.uViewProj * vec4f(bm_in.vWorld, 1.0)).xy / (bm_u.uViewProj * vec4f(bm_in.vWorld, 1.0)).w * vec2f(0.5, -0.5) + vec2f(0.5));
  let uvEnd = ((bm_u.uViewProj * vec4f(rayEnd, 1.0)).xy / (bm_u.uViewProj * vec4f(rayEnd, 1.0)).w * vec2f(0.5, -0.5) + vec2f(0.5));
  let depthStart = distance(bm_in.vWorld, bm_u.uViewPos);
  let depthEnd = distance(rayEnd, bm_u.uViewPos);
  var hitUv = vec2f(0.5, 0.5);
  var hitAlong = 1.0;
  var found = 0.0;
  var wasInFront = step(depthStart, textureSample(uScene, uScene_sampler, uvStart).w);
  for (var i = 1.0; i < 19.0; i = i + 1.0) {
    let along = i / 18.0;
    let uv = mix(uvStart, uvEnd, along);
    let rayDepth = 1.0 / mix(1.0 / depthStart, 1.0 / depthEnd, along);
    let sampled = textureSample(uScene, uScene_sampler, uv);
    let onScreen = step(0.0, uv.x) * step(uv.x, 1.0) * step(0.0, uv.y) * step(uv.y, 1.0);
    let nowBehind = step(sampled.w, rayDepth);
    let shallow = step(rayDepth - sampled.w, bm_u.uThickness);
    let isHit = onScreen * wasInFront * nowBehind * shallow;
    let take = isHit * (1.0 - found);
    hitUv = mix(hitUv, uv, take);
    hitAlong = mix(hitAlong, along, take);
    found = max(found, isHit);
    wasInFront = step(rayDepth, sampled.w);
  }
  var lo = hitAlong - 1.0 / 18.0;
  var hi = hitAlong;
  for (var r = 0.0; r < 5.0; r = r + 1.0) {
    let mid = (lo + hi) * 0.5;
    let probeUv = mix(uvStart, uvEnd, mid);
    let probeDepth = 1.0 / mix(1.0 / depthStart, 1.0 / depthEnd, mid);
    let behind = step(textureSample(uScene, uScene_sampler, probeUv).w, probeDepth);
    lo = mix(lo, mid, 1.0 - behind);
    hi = mix(hi, mid, behind);
  }
  let refinedUv = mix(uvStart, uvEnd, hi);
  let hitColour = textureSample(uScene, uScene_sampler, refinedUv).xyz;
  let env = studioEnv(bounced, bm_u.uSkyTint, bm_u.uHorizon, light);
  let edge = smoothstep(0.0, 0.14, hitUv.x) * smoothstep(0.0, 0.14, 1.0 - hitUv.x) * smoothstep(0.0, 0.14, hitUv.y) * smoothstep(0.0, 0.14, 1.0 - hitUv.y);
  let grazing = smoothstep(0.12, 0.4, abs(dot(bounced, viewDir)));
  let confidence = found * edge * grazing * bm_u.uMirror;
  let mirror = mix(env, hitColour * 1.35 + env * 0.2, confidence);
  let hotspot = min(specGGX(n, light, viewDir, 0.05), 14.0) * 2.4;
  let bloom = specGGX(n, light, viewDir, 0.34) * 0.4;
  let glare = vec3f(1.0, 0.985, 0.95) * ((hotspot + bloom) * bm_u.uGlare);
  let ax = abs(bm_in.vLocal.x);
  let ay = abs(bm_in.vLocal.y);
  let az = abs(bm_in.vLocal.z);
  let secondAxis = max(min(ax, ay), min(max(ax, ay), az));
  let seam = smoothstep(0.45, 0.5, secondAxis);
  let corner = smoothstep(0.42, 0.5, min(min(ax, ay), az));
  let rim = fresnel(n, viewDir, 3.4);
  let edging = (bm_u.uSkyTint + vec3f(0.24, 0.3, 0.28)) * ((seam * 0.75 + corner * 1.4) * bm_u.uEdge);
  let absorb = mix(vec3f(1.0, 1.0, 1.0), bm_u.uGlassTint, clamp(1.0 - cosTheta, 0.0, 1.0) * 0.85);
  let reflected = mirror * absorb * f + glare + edging;
  let glareLuma = clamp(length(glare) * 0.5, 0.0, 1.0);
  let alpha = clamp(f * 0.92 + glareLuma + (seam * 0.32 + corner * 0.62) * bm_u.uEdge + rim * 0.05, 0.02, 0.985);
  return vec4f(reflected * (1.0 / alpha), alpha);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uBounds: 'vec3', uViewPos: 'vec3', uLightPos: 'vec3', uSkyTint: 'vec3', uHorizon: 'vec3', uGlassTint: 'vec3', uEdge: 'float', uGlare: 'float', uScene: 'sampler2D', uReach: 'float', uThickness: 'float', uMirror: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uBounds","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uLightPos","type":"vec3","kind":"3fv","size":3,"offset":96},{"name":"uSkyTint","type":"vec3","kind":"3fv","size":3,"offset":112},{"name":"uHorizon","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uGlassTint","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uEdge","type":"float","kind":"1f","size":1,"offset":156},{"name":"uGlare","type":"float","kind":"1f","size":1,"offset":160},{"name":"uScene","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uReach","type":"float","kind":"1f","size":1,"offset":164},{"name":"uThickness","type":"float","kind":"1f","size":1,"offset":168},{"name":"uMirror","type":"float","kind":"1f","size":1,"offset":172}],"uniformBlockSize":176},

};

export default ballsGlassShader;
