/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const BallsBackdrop: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTop: 'vec3'; uBottom: 'vec3'; uGlow: 'vec3' }> = {
  wgslSrc: `struct BmUniforms {
  uTop : vec3f,
  uBottom : vec3f,
  uGlow : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.99999, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let base = mix(bm_u.uBottom, bm_u.uTop, pow(clamp(bm_in.vUv.y, 0.0, 1.0), 0.75));
  let falloff = 1.0 - clamp(length(bm_in.vUv - vec2f(0.5, 0.46)) * 1.7, 0.0, 1.0);
  return vec4f(base + bm_u.uGlow * (pow(falloff, 2.4) * 0.5), 4000.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTop: 'vec3', uBottom: 'vec3', uGlow: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTop","type":"vec3","kind":"3fv","size":3,"offset":0},{"name":"uBottom","type":"vec3","kind":"3fv","size":3,"offset":16},{"name":"uGlow","type":"vec3","kind":"3fv","size":3,"offset":32}],"uniformBlockSize":48},

};

export default BallsBackdrop;
