/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const ballsFloorShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uBounds: 'vec3'; uViewPos: 'vec3'; uLightPos: 'vec3'; uSkyTint: 'vec3'; uGroundTint: 'vec3'; uLightViewProj: 'mat4'; uShadowMap: 'sampler2D'; uRange: 'float'; uTexel: 'float'; uSoftness: 'float'; uBias: 'float' }> = {
  vertexSrc: `#version 300 es
precision highp float;
precision highp int;
layout(location = 0) in vec3 aPosition;
uniform mat4 uViewProj;
uniform vec3 uBounds;
out vec3 vWorld;
out vec2 vLocal;
void main() {
  vec3 world = vec3(aPosition.x * uBounds.x, 0.0 - uBounds.y + 0.004, aPosition.y * uBounds.z);
  vWorld = world;
  vLocal = vec2(aPosition.x, aPosition.y);
  gl_Position = uViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp sampler3D;
uniform vec3 uViewPos;
uniform vec3 uLightPos;
uniform vec3 uSkyTint;
uniform vec3 uGroundTint;
uniform mat4 uLightViewProj;
uniform sampler2D uShadowMap;
uniform float uRange;
uniform float uTexel;
uniform float uSoftness;
uniform float uBias;
in vec3 vWorld;
in vec2 vLocal;
out vec4 fragColor;
float specGGX(vec3 normal, vec3 lightDir, vec3 viewDir, float roughness) {
  vec3 n = normalize(normal);
  vec3 halfway = normalize(normalize(lightDir) + normalize(viewDir));
  float ndoth = max(dot(n, halfway), 0.0);
  float a = roughness * roughness;
  float a2 = a * a;
  float denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  float ndf = a2 / (3.14159265 * denom * denom);
  float ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
vec3 hemisphereLight(vec3 normal, vec3 skyColor, vec3 groundColor) {
  float blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
float shadowDepth(vec3 worldPos, vec3 lightPos, float range) {
  return distance(worldPos, lightPos) / range;
}
float shadowFactor(sampler2D shadowMap, mat4 lightViewProj, vec3 worldPos, vec3 normal, vec3 lightPos, float range, float texel, float softness, float bias) {
  vec3 toLight = normalize(lightPos - worldPos);
  float facing = max(dot(normalize(normal), toLight), 0.0);
  float slope = 1.0 + 2.0 * (1.0 - facing);
  vec3 lookup = worldPos + normalize(normal) * (bias * slope);
  vec4 clip = lightViewProj * vec4(lookup, 1.0);
  vec2 uv = ((clip).xy / (clip).w * 0.5 + 0.5);
  float reference = shadowDepth(lookup, lightPos, range) - bias * slope / range;
  float visible = 0.0;
  for (float y = -1.0; y < 2.0; y = y + 1.0) {
    for (float x = -1.0; x < 2.0; x = x + 1.0) {
      vec2 tap = uv + vec2(x, y) * (texel * softness);
      visible = visible + step(reference, texture(shadowMap, tap).x);
    }
  }
  return visible / 9.0;
}
void main() {
  vec3 n = vec3(0.0, 1.0, 0.0);
  vec3 viewDir = normalize(uViewPos - vWorld);
  vec3 light = normalize(uLightPos - vWorld);
  float facing = max(dot(n, light), 0.0);
  float sunlight = shadowFactor(uShadowMap, uLightViewProj, vWorld, n, uLightPos, uRange, uTexel, uSoftness, uBias);
  vec3 ambient = hemisphereLight(n, uSkyTint, uGroundTint);
  vec3 albedo = vec3(0.09, 0.095, 0.115);
  float gloss = specGGX(n, light, viewDir, 0.34) * 0.5 * sunlight;
  vec3 lit = albedo * (ambient + vec3(1.0, 0.97, 0.92) * (facing * sunlight * 0.9));
  float corner = 1.0 - smoothstep(0.72, 1.0, length(vLocal)) * 0.55;
  fragColor = vec4((lit + vec3(1.0, 0.99, 0.96) * gloss) * corner, distance(vWorld, uViewPos));
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uBounds : vec3f,
  uViewPos : vec3f,
  uLightPos : vec3f,
  uSkyTint : vec3f,
  uGroundTint : vec3f,
  uLightViewProj : mat4x4f,
  uRange : f32,
  uTexel : f32,
  uSoftness : f32,
  uBias : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uShadowMap : texture_2d<f32>;
@group(0) @binding(2) var uShadowMap_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vLocal : vec2f,
}
fn specGGX(normal : vec3f, lightDir : vec3f, viewDir : vec3f, roughness : f32) -> f32 {
  let n = normalize(normal);
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  let ndoth = max(dot(n, halfway), 0.0);
  let a = roughness * roughness;
  let a2 = a * a;
  let denom = ndoth * ndoth * (a2 - 1.0) + 1.0;
  let ndf = a2 / (3.14159265 * denom * denom);
  let ndotl = max(dot(n, normalize(lightDir)), 0.0);
  return ndf * ndotl * 0.25;
}
fn hemisphereLight(normal : vec3f, skyColor : vec3f, groundColor : vec3f) -> vec3f {
  let blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
fn shadowDepth(worldPos : vec3f, lightPos : vec3f, range : f32) -> f32 {
  return distance(worldPos, lightPos) / range;
}
fn shadowFactor(shadowMap : texture_2d<f32>, shadowMap_sampler : sampler, lightViewProj : mat4x4f, worldPos : vec3f, normal : vec3f, lightPos : vec3f, range : f32, texel : f32, softness : f32, bias : f32) -> f32 {
  let toLight = normalize(lightPos - worldPos);
  let facing = max(dot(normalize(normal), toLight), 0.0);
  let slope = 1.0 + 2.0 * (1.0 - facing);
  let lookup = worldPos + normalize(normal) * (bias * slope);
  let clip = lightViewProj * vec4f(lookup, 1.0);
  let uv = ((clip).xy / (clip).w * vec2f(0.5, -0.5) + vec2f(0.5));
  let reference = shadowDepth(lookup, lightPos, range) - bias * slope / range;
  var visible = 0.0;
  for (var y = -1.0; y < 2.0; y = y + 1.0) {
    for (var x = -1.0; x < 2.0; x = x + 1.0) {
      let tap = uv + vec2f(x, y) * (texel * softness);
      visible = visible + step(reference, textureSampleLevel(shadowMap, shadowMap_sampler, tap, 0.0).x);
    }
  }
  return visible / 9.0;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = vec3f(bm_in.aPosition.x * bm_u.uBounds.x, 0.0 - bm_u.uBounds.y + 0.004, bm_in.aPosition.y * bm_u.uBounds.z);
  bm_out.vWorld = world;
  bm_out.vLocal = vec2f(bm_in.aPosition.x, bm_in.aPosition.y);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let n = vec3f(0.0, 1.0, 0.0);
  let viewDir = normalize(bm_u.uViewPos - bm_in.vWorld);
  let light = normalize(bm_u.uLightPos - bm_in.vWorld);
  let facing = max(dot(n, light), 0.0);
  let sunlight = shadowFactor(uShadowMap, uShadowMap_sampler, bm_u.uLightViewProj, bm_in.vWorld, n, bm_u.uLightPos, bm_u.uRange, bm_u.uTexel, bm_u.uSoftness, bm_u.uBias);
  let ambient = hemisphereLight(n, bm_u.uSkyTint, bm_u.uGroundTint);
  let albedo = vec3f(0.09, 0.095, 0.115);
  let gloss = specGGX(n, light, viewDir, 0.34) * 0.5 * sunlight;
  let lit = albedo * (ambient + vec3f(1.0, 0.97, 0.92) * (facing * sunlight * 0.9));
  let corner = 1.0 - smoothstep(0.72, 1.0, length(bm_in.vLocal)) * 0.55;
  return vec4f((lit + vec3f(1.0, 0.99, 0.96) * gloss) * corner, distance(bm_in.vWorld, bm_u.uViewPos));
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uBounds: 'vec3', uViewPos: 'vec3', uLightPos: 'vec3', uSkyTint: 'vec3', uGroundTint: 'vec3', uLightViewProj: 'mat4', uShadowMap: 'sampler2D', uRange: 'float', uTexel: 'float', uSoftness: 'float', uBias: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uBounds","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uLightPos","type":"vec3","kind":"3fv","size":3,"offset":96},{"name":"uSkyTint","type":"vec3","kind":"3fv","size":3,"offset":112},{"name":"uGroundTint","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":144},{"name":"uShadowMap","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uRange","type":"float","kind":"1f","size":1,"offset":208},{"name":"uTexel","type":"float","kind":"1f","size":1,"offset":212},{"name":"uSoftness","type":"float","kind":"1f","size":1,"offset":216},{"name":"uBias","type":"float","kind":"1f","size":1,"offset":220}],"uniformBlockSize":224},

};

export default ballsFloorShader;
