/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const brocraftWaterShader: CompiledShader<{ aPosition: 'vec3' }, { iCell: 'vec2' }, { uViewProj: 'mat4'; uOrigin: 'vec2'; uRadius: 'float'; uSea: 'float'; uAmp: 'float'; uTime: 'float'; uViewPos: 'vec3'; uSunDir: 'vec3'; uSunColor: 'vec3'; uHorizon: 'vec3'; uZenith: 'vec3'; uFogStart: 'float'; uFogEnd: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 iCell;
uniform mat4 uViewProj;
uniform vec2 uOrigin;
uniform float uRadius;
uniform float uSea;
uniform float uAmp;
uniform float uTime;
out vec3 vWorld;
out float vDepth;
float hash21(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}
float vnoise2(vec2 p) {
  vec2 cell = vec2(floor(p.x), floor(p.y));
  vec2 f = p - cell;
  vec2 u = vec2(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y));
  float a = hash21(cell);
  float b = hash21(cell + vec2(1.0, 0.0));
  float c = hash21(cell + vec2(0.0, 1.0));
  float d = hash21(cell + vec2(1.0, 1.0));
  return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}
float fbm2(vec2 p, float octaves) {
  float total = 0.0;
  float amplitude = 0.5;
  float frequency = 1.0;
  float norm = 0.0;
  for (float i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise2(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
float seabedHeight(vec2 p, float amp) {
  float base = fbm2(p * 0.0072, 4.0);
  float detail = fbm2(p * 0.055, 3.0);
  float mountain = clamp((base - 0.52) * 3.2, 0.0, 1.0);
  float h = (base - 0.47) * 74.0 * amp + (detail - 0.5) * (5.0 + 40.0 * mountain) * amp;
  if (h < -7.0) {
    h = -7.0 + (h + 7.0) * 0.22;
  }
  return h;
}
float columnHeight(vec2 p, float amp) {
  return floor(seabedHeight(p, amp));
}
void main() {
  float wx = uOrigin.x + iCell.x;
  float wz = uOrigin.y + iCell.y;
  float h = columnHeight(vec2(wx, wz), uAmp);
  float px = wx + aPosition.x;
  float pz = wz - aPosition.y;
  float swell = cos(px * 0.35 + uTime * 1.1) * 0.02 + cos(pz * 0.27 - uTime * 0.9) * 0.02;
  float y = uSea + 0.38 + swell;
  vec3 world = vec3(px, y, pz);
  vWorld = world;
  vDepth = y - (seabedHeight(vec2(px, pz), uAmp) + 0.5);
  vec4 clip = uViewProj * vec4(world, 1.0);
  if (h >= uSea) {
    clip = vec4(2.0, 2.0, 2.0, 1.0);
  }
  if (length(iCell) > uRadius) {
    clip = vec4(2.0, 2.0, 2.0, 1.0);
  }
  gl_Position = clip;
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform vec3 uViewPos;
uniform vec3 uSunDir;
uniform vec3 uSunColor;
uniform vec3 uHorizon;
uniform vec3 uZenith;
uniform float uFogStart;
uniform float uFogEnd;
in vec3 vWorld;
in float vDepth;
out vec4 fragColor;
float fresnel(vec3 normal, vec3 viewDir, float power) {
  float base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
float blinnPhongSpec(vec3 normal, vec3 lightDir, vec3 viewDir, float shininess) {
  vec3 halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
vec3 ripple(vec2 p, float t) {
  vec2 k1 = vec2(0.62, 0.31);
  vec2 k2 = vec2(-0.28, 0.71);
  vec2 k3 = vec2(1.43, -0.97);
  vec2 k4 = vec2(-1.11, -1.63);
  float c1 = cos(dot(p, k1) + t * 1.6) * 0.1;
  float c2 = cos(dot(p, k2) + t * 1.15) * 0.085;
  float c3 = cos(dot(p, k3) - t * 2.3) * 0.03;
  float c4 = cos(dot(p, k4) + t * 2.9) * 0.02;
  float dx = k1.x * c1 + k2.x * c2 + k3.x * c3 + k4.x * c4;
  float dz = k1.y * c1 + k2.y * c2 + k3.y * c3 + k4.y * c4;
  return normalize(vec3(-dx, 1.0, -dz));
}
void main() {
  vec3 n = ripple(vec2(vWorld.x, vWorld.z), uTime);
  vec3 viewDir = normalize(uViewPos - vWorld);
  vec3 sun = normalize(uSunDir);
  float rim = clamp(fresnel(n, viewDir, 4.0) * 1.15, 0.0, 1.0);
  vec3 r = reflect(viewDir * -1.0, n);
  float lift = pow(clamp(r.y, 0.0, 1.0), 0.42);
  vec3 sky = mix(uHorizon, uZenith, lift);
  float toSun = max(dot(r, sun), 0.0);
  sky = sky + uSunColor * (pow(toSun, 6.0) * 0.25);
  vec3 shallow = vec3(0.17, 0.44, 0.46);
  vec3 deep = vec3(0.02, 0.09, 0.16);
  vec3 body = mix(shallow, deep, clamp(vDepth * 0.16, 0.0, 1.0));
  vec3 color = mix(body, sky, rim);
  color = color + uSunColor * (blinnPhongSpec(n, sun, viewDir, 700.0) * 2.4);
  color = color + uSunColor * (blinnPhongSpec(n, sun, viewDir, 30.0) * 0.1);
  float alpha = clamp(0.4 + vDepth * 0.16 + rim * 0.5, 0.0, 0.97);
  float dist = length(vec2(uViewPos.x - vWorld.x, uViewPos.z - vWorld.z));
  float fog = pow(smoothstep(uFogStart, uFogEnd, dist), 1.6);
  vec3 d = normalize(vWorld - uViewPos);
  float fogLift = pow(clamp(d.y, 0.0, 1.0), 0.42);
  vec3 fogColor = mix(uHorizon, uZenith, fogLift);
  fogColor = mix(fogColor, uHorizon * 0.82, clamp(-d.y * 3.0, 0.0, 1.0));
  fragColor = vec4(mix(color, fogColor, fog), alpha);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uOrigin : vec2f,
  uRadius : f32,
  uSea : f32,
  uAmp : f32,
  uTime : f32,
  uViewPos : vec3f,
  uSunDir : vec3f,
  uSunColor : vec3f,
  uHorizon : vec3f,
  uZenith : vec3f,
  uFogStart : f32,
  uFogEnd : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) iCell : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vDepth : f32,
}
fn hash21(p : vec2f) -> f32 {
  return fract(sin(dot(p, vec2f(127.1, 311.7))) * 43758.5453);
}
fn vnoise2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  let u = vec2f(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y));
  let a = hash21(cell);
  let b = hash21(cell + vec2f(1.0, 0.0));
  let c = hash21(cell + vec2f(0.0, 1.0));
  let d = hash21(cell + vec2f(1.0, 1.0));
  return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}
fn fbm2(p : vec2f, octaves : f32) -> f32 {
  var total = 0.0;
  var amplitude = 0.5;
  var frequency = 1.0;
  var norm = 0.0;
  for (var i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise2(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
fn fresnel(normal : vec3f, viewDir : vec3f, power : f32) -> f32 {
  let base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
fn blinnPhongSpec(normal : vec3f, lightDir : vec3f, viewDir : vec3f, shininess : f32) -> f32 {
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
fn seabedHeight(p : vec2f, amp : f32) -> f32 {
  let base = fbm2(p * 0.0072, 4.0);
  let detail = fbm2(p * 0.055, 3.0);
  let mountain = clamp((base - 0.52) * 3.2, 0.0, 1.0);
  var h = (base - 0.47) * 74.0 * amp + (detail - 0.5) * (5.0 + 40.0 * mountain) * amp;
  if (h < -7.0) {
    h = -7.0 + (h + 7.0) * 0.22;
  }
  return h;
}
fn columnHeight(p : vec2f, amp : f32) -> f32 {
  return floor(seabedHeight(p, amp));
}
fn ripple(p : vec2f, t : f32) -> vec3f {
  let k1 = vec2f(0.62, 0.31);
  let k2 = vec2f(-0.28, 0.71);
  let k3 = vec2f(1.43, -0.97);
  let k4 = vec2f(-1.11, -1.63);
  let c1 = cos(dot(p, k1) + t * 1.6) * 0.1;
  let c2 = cos(dot(p, k2) + t * 1.15) * 0.085;
  let c3 = cos(dot(p, k3) - t * 2.3) * 0.03;
  let c4 = cos(dot(p, k4) + t * 2.9) * 0.02;
  let dx = k1.x * c1 + k2.x * c2 + k3.x * c3 + k4.x * c4;
  let dz = k1.y * c1 + k2.y * c2 + k3.y * c3 + k4.y * c4;
  return normalize(vec3f(-dx, 1.0, -dz));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let wx = bm_u.uOrigin.x + bm_in.iCell.x;
  let wz = bm_u.uOrigin.y + bm_in.iCell.y;
  let h = columnHeight(vec2f(wx, wz), bm_u.uAmp);
  let px = wx + bm_in.aPosition.x;
  let pz = wz - bm_in.aPosition.y;
  let swell = cos(px * 0.35 + bm_u.uTime * 1.1) * 0.02 + cos(pz * 0.27 - bm_u.uTime * 0.9) * 0.02;
  let y = bm_u.uSea + 0.38 + swell;
  let world = vec3f(px, y, pz);
  bm_out.vWorld = world;
  bm_out.vDepth = y - (seabedHeight(vec2f(px, pz), bm_u.uAmp) + 0.5);
  var clip = bm_u.uViewProj * vec4f(world, 1.0);
  if (h >= bm_u.uSea) {
    clip = vec4f(2.0, 2.0, 2.0, 1.0);
  }
  if (length(bm_in.iCell) > bm_u.uRadius) {
    clip = vec4f(2.0, 2.0, 2.0, 1.0);
  }
  bm_out.bm_position = clip;
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let n = ripple(vec2f(bm_in.vWorld.x, bm_in.vWorld.z), bm_u.uTime);
  let viewDir = normalize(bm_u.uViewPos - bm_in.vWorld);
  let sun = normalize(bm_u.uSunDir);
  let rim = clamp(fresnel(n, viewDir, 4.0) * 1.15, 0.0, 1.0);
  let r = reflect(viewDir * -1.0, n);
  let lift = pow(clamp(r.y, 0.0, 1.0), 0.42);
  var sky = mix(bm_u.uHorizon, bm_u.uZenith, lift);
  let toSun = max(dot(r, sun), 0.0);
  sky = sky + bm_u.uSunColor * (pow(toSun, 6.0) * 0.25);
  let shallow = vec3f(0.17, 0.44, 0.46);
  let deep = vec3f(0.02, 0.09, 0.16);
  let body = mix(shallow, deep, clamp(bm_in.vDepth * 0.16, 0.0, 1.0));
  var color = mix(body, sky, rim);
  color = color + bm_u.uSunColor * (blinnPhongSpec(n, sun, viewDir, 700.0) * 2.4);
  color = color + bm_u.uSunColor * (blinnPhongSpec(n, sun, viewDir, 30.0) * 0.1);
  let alpha = clamp(0.4 + bm_in.vDepth * 0.16 + rim * 0.5, 0.0, 0.97);
  let dist = length(vec2f(bm_u.uViewPos.x - bm_in.vWorld.x, bm_u.uViewPos.z - bm_in.vWorld.z));
  let fog = pow(smoothstep(bm_u.uFogStart, bm_u.uFogEnd, dist), 1.6);
  let d = normalize(bm_in.vWorld - bm_u.uViewPos);
  let fogLift = pow(clamp(d.y, 0.0, 1.0), 0.42);
  var fogColor = mix(bm_u.uHorizon, bm_u.uZenith, fogLift);
  fogColor = mix(fogColor, bm_u.uHorizon * 0.82, clamp(-d.y * 3.0, 0.0, 1.0));
  return vec4f(mix(color, fogColor, fog), alpha);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: { iCell: 'vec2' },
  uniforms: { uViewProj: 'mat4', uOrigin: 'vec2', uRadius: 'float', uSea: 'float', uAmp: 'float', uTime: 'float', uViewPos: 'vec3', uSunDir: 'vec3', uSunColor: 'vec3', uHorizon: 'vec3', uZenith: 'vec3', uFogStart: 'float', uFogEnd: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"iCell","type":"vec2","location":1,"size":2,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uOrigin","type":"vec2","kind":"2fv","size":2,"offset":64},{"name":"uRadius","type":"float","kind":"1f","size":1,"offset":72},{"name":"uSea","type":"float","kind":"1f","size":1,"offset":76},{"name":"uAmp","type":"float","kind":"1f","size":1,"offset":80},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":84},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":96},{"name":"uSunDir","type":"vec3","kind":"3fv","size":3,"offset":112},{"name":"uSunColor","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uHorizon","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uZenith","type":"vec3","kind":"3fv","size":3,"offset":160},{"name":"uFogStart","type":"float","kind":"1f","size":1,"offset":172},{"name":"uFogEnd","type":"float","kind":"1f","size":1,"offset":176}],"uniformBlockSize":192},
};

export default brocraftWaterShader;
