/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const brocraftBlocksShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iCell: 'vec3' }, { uViewProj: 'mat4'; uOrigin: 'vec2'; uRadius: 'float'; uLayers: 'float'; uSea: 'float'; uAmp: 'float'; uViewPos: 'vec3'; uSunDir: 'vec3'; uSunColor: 'vec3'; uSkyTint: 'vec3'; uGroundTint: 'vec3'; uHorizon: 'vec3'; uZenith: 'vec3'; uFogStart: 'float'; uFogEnd: 'float'; uGrass: 'sampler2D'; uDirt: 'sampler2D'; uStone: 'sampler2D'; uSand: 'sampler2D' }> = {
  vertexSrc: `#version 300 es
precision highp float;
precision highp int;
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 aNormal;
layout(location = 2) in vec3 iCell;
uniform mat4 uViewProj;
uniform vec2 uOrigin;
uniform float uRadius;
uniform float uLayers;
uniform float uSea;
uniform float uAmp;
out vec3 vNormal;
out vec3 vWorld;
out float vType;
out float vBase;
out float vAo;
float hash21(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}
float vnoise2(vec2 p) {
  vec2 cell = vec2(floor(p.x), floor(p.y));
  vec2 f = p - cell;
  vec2 u = vec2(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y));
  float a = hash21(cell);
  float b = hash21(cell + vec2(1.0, 0.0));
  float c = hash21(cell + vec2(0.0, 1.0));
  float d = hash21(cell + vec2(1.0, 1.0));
  return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}
float fbm2(vec2 p, float octaves) {
  float total = 0.0;
  float amplitude = 0.5;
  float frequency = 1.0;
  float norm = 0.0;
  for (float i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise2(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
float columnHeight(vec2 p, float amp) {
  float base = fbm2(p * 0.0072, 4.0);
  float detail = fbm2(p * 0.055, 3.0);
  float mountain = clamp((base - 0.52) * 3.2, 0.0, 1.0);
  float h = (base - 0.47) * 74.0 * amp + (detail - 0.5) * (5.0 + 40.0 * mountain) * amp;
  if (h < -7.0) {
    h = -7.0 + (h + 7.0) * 0.22;
  }
  return floor(h);
}
float blockType(vec2 p, float h, float depth, float sea) {
  float rocky = fbm2(p * 0.031, 3.0);
  float t = 2.0;
  if (depth < 0.5) {
    t = 0.0;
    if (h < sea + 2.5) {
      t = 3.0;
    }
    if (h > 20.0 + rocky * 26.0) {
      t = 2.0;
    }
    if (rocky > 0.75 && h > sea + 5.5) {
      t = 2.0;
    }
  } else {
    if (depth < 3.5) {
      t = 1.0;
      if (h < sea + 2.5) {
        t = 3.0;
      }
    }
  }
  return t;
}
void main() {
  float layer = iCell.z;
  float wx = uOrigin.x + iCell.x;
  float wz = uOrigin.y + iCell.y;
  vec2 cell = vec2(wx, wz);
  float h = columnHeight(cell, uAmp);
  float by = h - layer;
  float hpx = columnHeight(vec2(wx + 1.0, wz), uAmp);
  float hnx = columnHeight(vec2(wx - 1.0, wz), uAmp);
  float hpz = columnHeight(vec2(wx, wz + 1.0), uAmp);
  float hnz = columnHeight(vec2(wx, wz - 1.0), uAmp);
  float hmin = min(min(hpx, hnx), min(hpz, hnz));
  float top = by + 0.5;
  float bottom = by - 0.5;
  if (layer > uLayers - 1.5) {
    bottom = min(bottom, hmin - 1.0);
  }
  float y = (top + bottom) * 0.5 + aPosition.y * (top - bottom);
  vec3 world = vec3(wx + aPosition.x, y, wz + aPosition.z);
  float ox = mix(step(by + 0.5, hnx), step(by + 0.5, hpx), step(0.0, aPosition.x));
  float oz = mix(step(by + 0.5, hnz), step(by + 0.5, hpz), step(0.0, aPosition.z));
  float crease = 1.0 - 0.26 * ox - 0.26 * oz;
  vAo = crease * (0.78 + 0.22 * (aPosition.y + 0.5));
  vNormal = aNormal;
  vWorld = world;
  vBase = by;
  vType = blockType(cell, h, layer, uSea);
  vec4 clip = uViewProj * vec4(world, 1.0);
  if (layer > 0.5 && hmin >= by) {
    clip = vec4(2.0, 2.0, 2.0, 1.0);
  }
  if (length(vec2(iCell.x, iCell.y)) > uRadius) {
    clip = vec4(2.0, 2.0, 2.0, 1.0);
  }
  gl_Position = clip;
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp sampler3D;
uniform float uSea;
uniform vec3 uViewPos;
uniform vec3 uSunDir;
uniform vec3 uSunColor;
uniform vec3 uSkyTint;
uniform vec3 uGroundTint;
uniform vec3 uHorizon;
uniform vec3 uZenith;
uniform float uFogStart;
uniform float uFogEnd;
uniform sampler2D uGrass;
uniform sampler2D uDirt;
uniform sampler2D uStone;
uniform sampler2D uSand;
in vec3 vNormal;
in vec3 vWorld;
in float vType;
in float vBase;
in float vAo;
out vec4 fragColor;
float hash21(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}
float vnoise2(vec2 p) {
  vec2 cell = vec2(floor(p.x), floor(p.y));
  vec2 f = p - cell;
  vec2 u = vec2(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y));
  float a = hash21(cell);
  float b = hash21(cell + vec2(1.0, 0.0));
  float c = hash21(cell + vec2(0.0, 1.0));
  float d = hash21(cell + vec2(1.0, 1.0));
  return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}
float fbm2(vec2 p, float octaves) {
  float total = 0.0;
  float amplitude = 0.5;
  float frequency = 1.0;
  float norm = 0.0;
  for (float i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise2(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
float luminance(vec3 color) {
  return dot(color, vec3(0.2126, 0.7152, 0.0722));
}
float lambert(vec3 normal, vec3 lightDir) {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
float blinnPhongSpec(vec3 normal, vec3 lightDir, vec3 viewDir, float shininess) {
  vec3 halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
vec3 hemisphereLight(vec3 normal, vec3 skyColor, vec3 groundColor) {
  float blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
void main() {
  vec3 n0 = normalize(vNormal);
  vec2 uv = vec2(vWorld.x, vWorld.z);
  if (abs(n0.x) > 0.5) {
    uv = vec2(vWorld.z, -vWorld.y);
  } else {
    if (abs(n0.z) > 0.5) {
      uv = vec2(vWorld.x, -vWorld.y);
    }
  }
  float localY = vWorld.y - vBase + 0.5;
  float grassBlock = 1.0 - step(0.5, vType);
  float lip = step(0.52 + vnoise2(uv * 6.5) * 0.34, localY);
  float wGrass = grassBlock * lip;
  float wDirt = grassBlock * (1.0 - lip) + (step(0.5, vType) - step(1.5, vType));
  float wStone = step(1.5, vType) - step(2.5, vType);
  float wSand = step(2.5, vType);
  float camDist = length(uViewPos - vWorld);
  float detail = 1.0 - smoothstep(12.0, 44.0, camDist);
  vec2 tuv = uv * 0.5;
  float e = 0.01;
  vec2 ex = vec2(e, 0.0);
  vec2 ey = vec2(0.0, e);
  float biome = fbm2(vec2(vWorld.x, vWorld.z) * 0.035, 3.0);
  vec3 grass = texture(uGrass, tuv).xyz * mix(vec3(0.84, 0.96, 0.74), vec3(1.14, 1.1, 0.86), biome);
  vec3 stone = texture(uStone, tuv).xyz * mix(vec3(0.78, 0.8, 0.85), vec3(1.06, 1.04, 1.0), biome);
  vec3 sand = texture(uSand, tuv).xyz * vec3(0.94, 0.85, 0.66);
  vec3 albedo = grass * wGrass + texture(uDirt, tuv).xyz * wDirt;
  albedo = albedo + stone * wStone + sand * wSand;
  vec3 atX = texture(uGrass, tuv + ex).xyz * wGrass + texture(uDirt, tuv + ex).xyz * wDirt + texture(uStone, tuv + ex).xyz * wStone + texture(uSand, tuv + ex).xyz * wSand;
  vec3 atY = texture(uGrass, tuv + ey).xyz * wGrass + texture(uDirt, tuv + ey).xyz * wDirt + texture(uStone, tuv + ey).xyz * wStone + texture(uSand, tuv + ey).xyz * wSand;
  vec3 lum = vec3(luminance(albedo), luminance(atX), luminance(atY));
  float shine = 12.0 * wGrass + 16.0 * wDirt + 54.0 * wStone + 30.0 * wSand;
  float specular = (0.03 * wGrass + 0.04 * wDirt + 0.16 * wStone + 0.09 * wSand) * (0.3 + 0.7 * detail);
  float relief = (1.5 * wGrass + 1.6 * wDirt + 2.1 * wStone + 0.9 * wSand) * detail;
  float tint = 0.95 + hash21(vec2(floor(vWorld.x + 0.001), floor(vWorld.z + 0.001))) * 0.1;
  float cavity = clamp(0.8 + lum.x * 0.42, 0.72, 1.08);
  albedo = albedo * (tint * cavity);
  vec2 bump = vec2((lum.x - lum.y) * relief * 5.0, (lum.x - lum.z) * relief * 5.0);
  vec3 tangent = vec3(1.0, 0.0, 0.0);
  vec3 bitangent = vec3(0.0, 0.0, 1.0);
  if (abs(n0.x) > 0.5) {
    tangent = vec3(0.0, 0.0, 1.0);
    bitangent = vec3(0.0, -1.0, 0.0);
  } else {
    if (abs(n0.z) > 0.5) {
      tangent = vec3(1.0, 0.0, 0.0);
      bitangent = vec3(0.0, -1.0, 0.0);
    }
  }
  vec3 n = normalize(n0 + tangent * bump.x + bitangent * bump.y);
  vec3 viewDir = normalize(uViewPos - vWorld);
  vec3 sun = normalize(uSunDir);
  float diffuse = lambert(n, sun);
  vec3 ambient = hemisphereLight(n, uSkyTint, uGroundTint) * vAo;
  float spec = blinnPhongSpec(n, sun, viewDir, shine) * specular * step(0.02, diffuse);
  float wet = 1.0 - smoothstep(uSea - 0.5, uSea + 1.5, vWorld.y);
  vec3 color = albedo * (ambient + uSunColor * (diffuse * vAo)) + uSunColor * spec;
  color = mix(color, color * vec3(0.55, 0.78, 0.95), wet * 0.55);
  float dist = length(vec2(uViewPos.x - vWorld.x, uViewPos.z - vWorld.z));
  float fog = pow(smoothstep(uFogStart, uFogEnd, dist), 1.6);
  vec3 d = normalize(vWorld - uViewPos);
  float lift = pow(clamp(d.y, 0.0, 1.0), 0.42);
  vec3 sky = mix(uHorizon, uZenith, lift);
  sky = mix(sky, uHorizon * 0.82, clamp(-d.y * 3.0, 0.0, 1.0));
  float toSun = max(dot(d, sun), 0.0);
  sky = sky + uSunColor * (pow(toSun, 6.0) * 0.22);
  fragColor = vec4(mix(color, sky, fog), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uOrigin : vec2f,
  uRadius : f32,
  uLayers : f32,
  uSea : f32,
  uAmp : f32,
  uViewPos : vec3f,
  uSunDir : vec3f,
  uSunColor : vec3f,
  uSkyTint : vec3f,
  uGroundTint : vec3f,
  uHorizon : vec3f,
  uZenith : vec3f,
  uFogStart : f32,
  uFogEnd : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uGrass : texture_2d<f32>;
@group(0) @binding(2) var uGrass_sampler : sampler;
@group(0) @binding(3) var uDirt : texture_2d<f32>;
@group(0) @binding(4) var uDirt_sampler : sampler;
@group(0) @binding(5) var uStone : texture_2d<f32>;
@group(0) @binding(6) var uStone_sampler : sampler;
@group(0) @binding(7) var uSand : texture_2d<f32>;
@group(0) @binding(8) var uSand_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iCell : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vWorld : vec3f,
  @location(2) vType : f32,
  @location(3) vBase : f32,
  @location(4) vAo : f32,
}
fn hash21(p : vec2f) -> f32 {
  return fract(sin(dot(p, vec2f(127.1, 311.7))) * 43758.5453);
}
fn vnoise2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  let u = vec2f(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y));
  let a = hash21(cell);
  let b = hash21(cell + vec2f(1.0, 0.0));
  let c = hash21(cell + vec2f(0.0, 1.0));
  let d = hash21(cell + vec2f(1.0, 1.0));
  return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}
fn fbm2(p : vec2f, octaves : f32) -> f32 {
  var total = 0.0;
  var amplitude = 0.5;
  var frequency = 1.0;
  var norm = 0.0;
  for (var i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise2(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
fn luminance(color : vec3f) -> f32 {
  return dot(color, vec3f(0.2126, 0.7152, 0.0722));
}
fn lambert(normal : vec3f, lightDir : vec3f) -> f32 {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
fn blinnPhongSpec(normal : vec3f, lightDir : vec3f, viewDir : vec3f, shininess : f32) -> f32 {
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
fn hemisphereLight(normal : vec3f, skyColor : vec3f, groundColor : vec3f) -> vec3f {
  let blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
fn columnHeight(p : vec2f, amp : f32) -> f32 {
  let base = fbm2(p * 0.0072, 4.0);
  let detail = fbm2(p * 0.055, 3.0);
  let mountain = clamp((base - 0.52) * 3.2, 0.0, 1.0);
  var h = (base - 0.47) * 74.0 * amp + (detail - 0.5) * (5.0 + 40.0 * mountain) * amp;
  if (h < -7.0) {
    h = -7.0 + (h + 7.0) * 0.22;
  }
  return floor(h);
}
fn blockType(p : vec2f, h : f32, depth : f32, sea : f32) -> f32 {
  let rocky = fbm2(p * 0.031, 3.0);
  var t = 2.0;
  if (depth < 0.5) {
    t = 0.0;
    if (h < sea + 2.5) {
      t = 3.0;
    }
    if (h > 20.0 + rocky * 26.0) {
      t = 2.0;
    }
    if (rocky > 0.75 && h > sea + 5.5) {
      t = 2.0;
    }
  } else {
    if (depth < 3.5) {
      t = 1.0;
      if (h < sea + 2.5) {
        t = 3.0;
      }
    }
  }
  return t;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let layer = bm_in.iCell.z;
  let wx = bm_u.uOrigin.x + bm_in.iCell.x;
  let wz = bm_u.uOrigin.y + bm_in.iCell.y;
  let cell = vec2f(wx, wz);
  let h = columnHeight(cell, bm_u.uAmp);
  let by = h - layer;
  let hpx = columnHeight(vec2f(wx + 1.0, wz), bm_u.uAmp);
  let hnx = columnHeight(vec2f(wx - 1.0, wz), bm_u.uAmp);
  let hpz = columnHeight(vec2f(wx, wz + 1.0), bm_u.uAmp);
  let hnz = columnHeight(vec2f(wx, wz - 1.0), bm_u.uAmp);
  let hmin = min(min(hpx, hnx), min(hpz, hnz));
  let top = by + 0.5;
  var bottom = by - 0.5;
  if (layer > bm_u.uLayers - 1.5) {
    bottom = min(bottom, hmin - 1.0);
  }
  let y = (top + bottom) * 0.5 + bm_in.aPosition.y * (top - bottom);
  let world = vec3f(wx + bm_in.aPosition.x, y, wz + bm_in.aPosition.z);
  let ox = mix(step(by + 0.5, hnx), step(by + 0.5, hpx), step(0.0, bm_in.aPosition.x));
  let oz = mix(step(by + 0.5, hnz), step(by + 0.5, hpz), step(0.0, bm_in.aPosition.z));
  let crease = 1.0 - 0.26 * ox - 0.26 * oz;
  bm_out.vAo = crease * (0.78 + 0.22 * (bm_in.aPosition.y + 0.5));
  bm_out.vNormal = bm_in.aNormal;
  bm_out.vWorld = world;
  bm_out.vBase = by;
  bm_out.vType = blockType(cell, h, layer, bm_u.uSea);
  var clip = bm_u.uViewProj * vec4f(world, 1.0);
  if (layer > 0.5 && hmin >= by) {
    clip = vec4f(2.0, 2.0, 2.0, 1.0);
  }
  if (length(vec2f(bm_in.iCell.x, bm_in.iCell.y)) > bm_u.uRadius) {
    clip = vec4f(2.0, 2.0, 2.0, 1.0);
  }
  bm_out.bm_position = clip;
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let n0 = normalize(bm_in.vNormal);
  var uv = vec2f(bm_in.vWorld.x, bm_in.vWorld.z);
  if (abs(n0.x) > 0.5) {
    uv = vec2f(bm_in.vWorld.z, -bm_in.vWorld.y);
  } else {
    if (abs(n0.z) > 0.5) {
      uv = vec2f(bm_in.vWorld.x, -bm_in.vWorld.y);
    }
  }
  let localY = bm_in.vWorld.y - bm_in.vBase + 0.5;
  let grassBlock = 1.0 - step(0.5, bm_in.vType);
  let lip = step(0.52 + vnoise2(uv * 6.5) * 0.34, localY);
  let wGrass = grassBlock * lip;
  let wDirt = grassBlock * (1.0 - lip) + (step(0.5, bm_in.vType) - step(1.5, bm_in.vType));
  let wStone = step(1.5, bm_in.vType) - step(2.5, bm_in.vType);
  let wSand = step(2.5, bm_in.vType);
  let camDist = length(bm_u.uViewPos - bm_in.vWorld);
  let detail = 1.0 - smoothstep(12.0, 44.0, camDist);
  let tuv = uv * 0.5;
  let e = 0.01;
  let ex = vec2f(e, 0.0);
  let ey = vec2f(0.0, e);
  let biome = fbm2(vec2f(bm_in.vWorld.x, bm_in.vWorld.z) * 0.035, 3.0);
  let grass = textureSample(uGrass, uGrass_sampler, tuv).xyz * mix(vec3f(0.84, 0.96, 0.74), vec3f(1.14, 1.1, 0.86), biome);
  let stone = textureSample(uStone, uStone_sampler, tuv).xyz * mix(vec3f(0.78, 0.8, 0.85), vec3f(1.06, 1.04, 1.0), biome);
  let sand = textureSample(uSand, uSand_sampler, tuv).xyz * vec3f(0.94, 0.85, 0.66);
  var albedo = grass * wGrass + textureSample(uDirt, uDirt_sampler, tuv).xyz * wDirt;
  albedo = albedo + stone * wStone + sand * wSand;
  let atX = textureSample(uGrass, uGrass_sampler, tuv + ex).xyz * wGrass + textureSample(uDirt, uDirt_sampler, tuv + ex).xyz * wDirt + textureSample(uStone, uStone_sampler, tuv + ex).xyz * wStone + textureSample(uSand, uSand_sampler, tuv + ex).xyz * wSand;
  let atY = textureSample(uGrass, uGrass_sampler, tuv + ey).xyz * wGrass + textureSample(uDirt, uDirt_sampler, tuv + ey).xyz * wDirt + textureSample(uStone, uStone_sampler, tuv + ey).xyz * wStone + textureSample(uSand, uSand_sampler, tuv + ey).xyz * wSand;
  let lum = vec3f(luminance(albedo), luminance(atX), luminance(atY));
  let shine = 12.0 * wGrass + 16.0 * wDirt + 54.0 * wStone + 30.0 * wSand;
  let specular = (0.03 * wGrass + 0.04 * wDirt + 0.16 * wStone + 0.09 * wSand) * (0.3 + 0.7 * detail);
  let relief = (1.5 * wGrass + 1.6 * wDirt + 2.1 * wStone + 0.9 * wSand) * detail;
  let tint = 0.95 + hash21(vec2f(floor(bm_in.vWorld.x + 0.001), floor(bm_in.vWorld.z + 0.001))) * 0.1;
  let cavity = clamp(0.8 + lum.x * 0.42, 0.72, 1.08);
  albedo = albedo * (tint * cavity);
  let bump = vec2f((lum.x - lum.y) * relief * 5.0, (lum.x - lum.z) * relief * 5.0);
  var tangent = vec3f(1.0, 0.0, 0.0);
  var bitangent = vec3f(0.0, 0.0, 1.0);
  if (abs(n0.x) > 0.5) {
    tangent = vec3f(0.0, 0.0, 1.0);
    bitangent = vec3f(0.0, -1.0, 0.0);
  } else {
    if (abs(n0.z) > 0.5) {
      tangent = vec3f(1.0, 0.0, 0.0);
      bitangent = vec3f(0.0, -1.0, 0.0);
    }
  }
  let n = normalize(n0 + tangent * bump.x + bitangent * bump.y);
  let viewDir = normalize(bm_u.uViewPos - bm_in.vWorld);
  let sun = normalize(bm_u.uSunDir);
  let diffuse = lambert(n, sun);
  let ambient = hemisphereLight(n, bm_u.uSkyTint, bm_u.uGroundTint) * bm_in.vAo;
  let spec = blinnPhongSpec(n, sun, viewDir, shine) * specular * step(0.02, diffuse);
  let wet = 1.0 - smoothstep(bm_u.uSea - 0.5, bm_u.uSea + 1.5, bm_in.vWorld.y);
  var color = albedo * (ambient + bm_u.uSunColor * (diffuse * bm_in.vAo)) + bm_u.uSunColor * spec;
  color = mix(color, color * vec3f(0.55, 0.78, 0.95), wet * 0.55);
  let dist = length(vec2f(bm_u.uViewPos.x - bm_in.vWorld.x, bm_u.uViewPos.z - bm_in.vWorld.z));
  let fog = pow(smoothstep(bm_u.uFogStart, bm_u.uFogEnd, dist), 1.6);
  let d = normalize(bm_in.vWorld - bm_u.uViewPos);
  let lift = pow(clamp(d.y, 0.0, 1.0), 0.42);
  var sky = mix(bm_u.uHorizon, bm_u.uZenith, lift);
  sky = mix(sky, bm_u.uHorizon * 0.82, clamp(-d.y * 3.0, 0.0, 1.0));
  let toSun = max(dot(d, sun), 0.0);
  sky = sky + bm_u.uSunColor * (pow(toSun, 6.0) * 0.22);
  return vec4f(mix(color, sky, fog), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iCell: 'vec3' },
  uniforms: { uViewProj: 'mat4', uOrigin: 'vec2', uRadius: 'float', uLayers: 'float', uSea: 'float', uAmp: 'float', uViewPos: 'vec3', uSunDir: 'vec3', uSunColor: 'vec3', uSkyTint: 'vec3', uGroundTint: 'vec3', uHorizon: 'vec3', uZenith: 'vec3', uFogStart: 'float', uFogEnd: 'float', uGrass: 'sampler2D', uDirt: 'sampler2D', uStone: 'sampler2D', uSand: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iCell","type":"vec3","location":2,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uOrigin","type":"vec2","kind":"2fv","size":2,"offset":64},{"name":"uRadius","type":"float","kind":"1f","size":1,"offset":72},{"name":"uLayers","type":"float","kind":"1f","size":1,"offset":76},{"name":"uSea","type":"float","kind":"1f","size":1,"offset":80},{"name":"uAmp","type":"float","kind":"1f","size":1,"offset":84},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":96},{"name":"uSunDir","type":"vec3","kind":"3fv","size":3,"offset":112},{"name":"uSunColor","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uSkyTint","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uGroundTint","type":"vec3","kind":"3fv","size":3,"offset":160},{"name":"uHorizon","type":"vec3","kind":"3fv","size":3,"offset":176},{"name":"uZenith","type":"vec3","kind":"3fv","size":3,"offset":192},{"name":"uFogStart","type":"float","kind":"1f","size":1,"offset":204},{"name":"uFogEnd","type":"float","kind":"1f","size":1,"offset":208},{"name":"uGrass","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uDirt","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uStone","type":"sampler2D","kind":"1i","size":1,"unit":2,"textureBinding":5,"samplerBinding":6},{"name":"uSand","type":"sampler2D","kind":"1i","size":1,"unit":3,"textureBinding":7,"samplerBinding":8}],"uniformBlockSize":224},

};

export default brocraftBlocksShader;
