/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const colorCubeShader: CompiledShader<{ aPosition: 'vec3'; aColor: 'vec3' }, Record<string, never>, { uMvp: 'mat4' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 aColor;
uniform mat4 uMvp;
out vec3 vColor;
void main() {
  vColor = aColor;
  gl_Position = uMvp * vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
in vec3 vColor;
out vec4 fragColor;
void main() {
  fragColor = vec4(vColor, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aColor: 'vec3' },
  instanceAttributes: {},
  uniforms: { uMvp: 'mat4' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aColor","type":"vec3","location":1,"size":3,"divisor":0}],"uniforms":[{"name":"uMvp","type":"mat4","kind":"m4fv","size":16}]},
};

export default colorCubeShader;
