/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const colorCubeShader: CompiledShader<{ aPosition: 'vec3'; aColor: 'vec3' }, Record<string, never>, { uMvp: 'mat4' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 aColor;
uniform mat4 uMvp;
out vec3 vColor;
void main() {
  vColor = aColor;
  gl_Position = uMvp * vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
in vec3 vColor;
out vec4 fragColor;
void main() {
  fragColor = vec4(vColor, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uMvp : mat4x4f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aColor : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vColor : vec3f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vColor = bm_in.aColor;
  bm_out.bm_position = bm_u.uMvp * vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  return vec4f(bm_in.vColor, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aColor: 'vec3' },
  instanceAttributes: {},
  uniforms: { uMvp: 'mat4' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aColor","type":"vec3","location":1,"size":3,"divisor":0}],"uniforms":[{"name":"uMvp","type":"mat4","kind":"m4fv","size":16,"offset":0}],"uniformBlockSize":64},
};

export default colorCubeShader;
