/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const gameReticleShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, { iAlong: 'float'; iSize: 'float'; iAlpha: 'float' }, { uColor: 'vec3'; uCursor: 'vec2'; uShip: 'vec2'; uAspect: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uColor : vec3f,
  uCursor : vec2f,
  uShip : vec2f,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
  @location(2) iAlong : f32,
  @location(3) iSize : f32,
  @location(4) iAlpha : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
  @location(1) vAlpha : f32,
}
fn sdBox2(p : vec2f, halfSize : vec2f) -> f32 {
  let d = vec2f(abs(p.x) - halfSize.x, abs(p.y) - halfSize.y);
  let outside = length(vec2f(max(d.x, 0.0), max(d.y, 0.0)));
  return outside + min(max(d.x, d.y), 0.0);
}
fn strokeAA(d : f32, width : f32, softness : f32) -> f32 {
  return 1.0 - smoothstep(width - softness, width + softness, abs(d));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.vAlpha = bm_in.iAlpha;
  let centre = bm_u.uShip + (bm_u.uCursor - bm_u.uShip) * bm_in.iAlong;
  bm_out.bm_position = vec4f(centre.x + bm_in.aPosition.x * bm_in.iSize / bm_u.uAspect, centre.y + bm_in.aPosition.y * bm_in.iSize, 0.0 - 1.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = bm_in.vUv - vec2f(0.5, 0.5);
  let outline = strokeAA(sdBox2(p, vec2f(0.34, 0.34)), 0.012, 0.008);
  let corner = smoothstep(0.2, 0.23, min(abs(p.x), abs(p.y)));
  return vec4f(bm_u.uColor, outline * corner * bm_in.vAlpha);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iAlong: 'float', iSize: 'float', iAlpha: 'float' },
  uniforms: { uColor: 'vec3', uCursor: 'vec2', uShip: 'vec2', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0},{"name":"iAlong","type":"float","location":2,"size":1,"divisor":1},{"name":"iSize","type":"float","location":3,"size":1,"divisor":1},{"name":"iAlpha","type":"float","location":4,"size":1,"divisor":1}],"uniforms":[{"name":"uColor","type":"vec3","kind":"3fv","size":3,"offset":0},{"name":"uCursor","type":"vec2","kind":"2fv","size":2,"offset":16},{"name":"uShip","type":"vec2","kind":"2fv","size":2,"offset":24},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":32}],"uniformBlockSize":48},

};

export default gameReticleShader;
