/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const gameLaserShader: CompiledShader<{ aPosition: 'vec3' }, { iStart: 'vec3'; iDir: 'vec3'; iBirth: 'float' }, { uViewProj: 'mat4'; uTime: 'float'; uViewPos: 'vec3' }> = {
  vertexSrc: `#version 300 es
precision highp float;
precision highp int;
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 iStart;
layout(location = 2) in vec3 iDir;
layout(location = 3) in float iBirth;
uniform mat4 uViewProj;
uniform float uTime;
uniform vec3 uViewPos;
out float vFacing;
out float vAlong;
out float vFade;
void main() {
  float age = uTime - iBirth;
  float life = 1.1;
  float alive = clamp(age * 60.0, 0.0, 1.0) * clamp((life - age) * 4.0, 0.0, 1.0);
  vec3 f = normalize(iDir);
  vec3 rgt = normalize(cross(f, vec3(0.0, 1.0, 0.0)));
  vec3 up = cross(f, rgt);
  float width = 0.18 * alive;
  vec3 local = rgt * (aPosition.x * width) + up * (aPosition.y * width) + f * (aPosition.z * 1.7);
  vec3 center = iStart + f * (age * 55.0);
  vec3 world = center + local;
  vec3 n = normalize(rgt * aPosition.x + up * aPosition.y + f * (aPosition.z * 0.1));
  vFacing = clamp(dot(n, normalize(uViewPos - world)), 0.0, 1.0);
  vAlong = aPosition.z * 0.5 + 0.5;
  vFade = alive;
  gl_Position = uViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
precision highp int;
in float vFacing;
in float vAlong;
in float vFade;
out vec4 fragColor;
void main() {
  float core = pow(vFacing, 3.0);
  float halo = pow(vFacing, 1.3) * 0.9;
  vec3 color = mix(vec3(0.3, 0.55, 1.0), vec3(1.0, 1.0, 1.0), core);
  fragColor = vec4(color, (core * 1.3 + halo) * (0.65 + vAlong * 0.35) * vFade);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uTime : f32,
  uViewPos : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) iStart : vec3f,
  @location(2) iDir : vec3f,
  @location(3) iBirth : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vFacing : f32,
  @location(1) vAlong : f32,
  @location(2) vFade : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let age = bm_u.uTime - bm_in.iBirth;
  let life = 1.1;
  let alive = clamp(age * 60.0, 0.0, 1.0) * clamp((life - age) * 4.0, 0.0, 1.0);
  let f = normalize(bm_in.iDir);
  let rgt = normalize(cross(f, vec3f(0.0, 1.0, 0.0)));
  let up = cross(f, rgt);
  let width = 0.18 * alive;
  let local = rgt * (bm_in.aPosition.x * width) + up * (bm_in.aPosition.y * width) + f * (bm_in.aPosition.z * 1.7);
  let center = bm_in.iStart + f * (age * 55.0);
  let world = center + local;
  let n = normalize(rgt * bm_in.aPosition.x + up * bm_in.aPosition.y + f * (bm_in.aPosition.z * 0.1));
  bm_out.vFacing = clamp(dot(n, normalize(bm_u.uViewPos - world)), 0.0, 1.0);
  bm_out.vAlong = bm_in.aPosition.z * 0.5 + 0.5;
  bm_out.vFade = alive;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let core = pow(bm_in.vFacing, 3.0);
  let halo = pow(bm_in.vFacing, 1.3) * 0.9;
  let color = mix(vec3f(0.3, 0.55, 1.0), vec3f(1.0, 1.0, 1.0), core);
  return vec4f(color, (core * 1.3 + halo) * (0.65 + bm_in.vAlong * 0.35) * bm_in.vFade);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: { iStart: 'vec3', iDir: 'vec3', iBirth: 'float' },
  uniforms: { uViewProj: 'mat4', uTime: 'float', uViewPos: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"iStart","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iDir","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iBirth","type":"float","location":3,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":64},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":80}],"uniformBlockSize":96},

};

export default gameLaserShader;
