/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const GameLaser: CompiledShader<{ aPosition: 'vec3' }, { iStart: 'vec3'; iDir: 'vec3'; iBirth: 'float' }, { uViewProj: 'mat4'; uTime: 'float'; uColor: 'vec3'; uSpeed: 'float'; uLife: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uTime : f32,
  uColor : vec3f,
  uSpeed : f32,
  uLife : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) iStart : vec3f,
  @location(2) iDir : vec3f,
  @location(3) iBirth : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vAlong : f32,
  @location(1) vFade : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let age = bm_u.uTime - bm_in.iBirth;
  let alive = clamp(age * 60.0, 0.0, 1.0) * clamp((bm_u.uLife - age) * 4.0, 0.0, 1.0);
  let f = normalize(bm_in.iDir);
  let rgt = normalize(cross(f, vec3f(0.0, 1.0, 0.0)));
  let up = cross(f, rgt);
  let width = 0.05 * alive;
  let along = bm_in.aPosition.z + 0.5;
  let local = rgt * (bm_in.aPosition.x * width) + up * (bm_in.aPosition.y * width) + f * (along * 4.5);
  let world = bm_in.iStart + f * (age * bm_u.uSpeed) + local;
  bm_out.vAlong = along;
  bm_out.vFade = alive;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let head = bm_in.vAlong * bm_in.vAlong;
  return vec4f(bm_u.uColor + vec3f(1.0, 1.0, 1.0) * (head * 0.8), (0.25 + head) * bm_in.vFade);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: { iStart: 'vec3', iDir: 'vec3', iBirth: 'float' },
  uniforms: { uViewProj: 'mat4', uTime: 'float', uColor: 'vec3', uSpeed: 'float', uLife: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"iStart","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iDir","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iBirth","type":"float","location":3,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":64},{"name":"uColor","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uSpeed","type":"float","kind":"1f","size":1,"offset":92},{"name":"uLife","type":"float","kind":"1f","size":1,"offset":96}],"uniformBlockSize":112},

};

export default GameLaser;
