/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const gameRocksShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, { iOffset: 'vec3'; iScale: 'float'; iSeed: 'float' }, { uViewProj: 'mat4'; uScroll: 'float'; uWrap: 'float'; uAhead: 'float'; uLightDir: 'vec3'; uTime: 'float'; uTex: 'sampler2D' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
layout(location = 2) in vec3 iOffset;
layout(location = 3) in float iScale;
layout(location = 4) in float iSeed;
uniform mat4 uViewProj;
uniform float uScroll;
uniform float uWrap;
uniform float uAhead;
uniform float uTime;
out vec3 vNormal;
out vec2 vUv;
out float vTint;
out float vHeight;
out float vDepth;
vec2 rotate2(vec2 p, float angle) {
  float c = cos(angle);
  float s = sin(angle);
  return vec2(p.x * c - p.y * s, p.x * s + p.y * c);
}
float hash11(float p) {
  return fract(sin(p * 127.1) * 43758.5453);
}
float hash31(vec3 p) {
  return fract(sin(dot(p, vec3(127.1, 311.7, 74.7))) * 43758.5453);
}
float vnoise3(vec3 p) {
  vec3 cell = vec3(floor(p.x), floor(p.y), floor(p.z));
  vec3 f = p - cell;
  vec3 u = vec3(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y), f.z * f.z * (3.0 - 2.0 * f.z));
  float n000 = hash31(cell);
  float n100 = hash31(cell + vec3(1.0, 0.0, 0.0));
  float n010 = hash31(cell + vec3(0.0, 1.0, 0.0));
  float n110 = hash31(cell + vec3(1.0, 1.0, 0.0));
  float n001 = hash31(cell + vec3(0.0, 0.0, 1.0));
  float n101 = hash31(cell + vec3(1.0, 0.0, 1.0));
  float n011 = hash31(cell + vec3(0.0, 1.0, 1.0));
  float n111 = hash31(cell + vec3(1.0, 1.0, 1.0));
  float nx00 = mix(n000, n100, u.x);
  float nx10 = mix(n010, n110, u.x);
  float nx01 = mix(n001, n101, u.x);
  float nx11 = mix(n011, n111, u.x);
  float nxy0 = mix(nx00, nx10, u.y);
  float nxy1 = mix(nx01, nx11, u.y);
  return mix(nxy0, nxy1, u.z);
}
float fbm3(vec3 p, float octaves) {
  float total = 0.0;
  float amplitude = 0.5;
  float frequency = 1.0;
  float norm = 0.0;
  for (float i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise3(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
float rockRadius(vec3 dir, float seed) {
  vec3 q = dir * 2.3 + vec3(seed * 37.7, seed * 11.3, seed * 71.9);
  return 1.0 + (fbm3(q, 4.0) - 0.5) * 0.55;
}
void main() {
  vec3 dir = normalize(aPosition);
  vec3 t1 = normalize(cross(dir, vec3(0.31, 0.82, 0.47)));
  vec3 t2 = cross(dir, t1);
  float e = 0.12;
  vec3 d1 = normalize(dir + t1 * e);
  vec3 d2 = normalize(dir + t2 * e);
  float r0 = rockRadius(dir, iSeed);
  vec3 p0 = dir * r0;
  vec3 edge1 = d1 * rockRadius(d1, iSeed) - p0;
  vec3 edge2 = d2 * rockRadius(d2, iSeed) - p0;
  vec3 normal = normalize(cross(edge1, edge2));
  float spin = uTime * (0.2 + iSeed * 0.8);
  vec2 pr = rotate2(p0.xz, spin);
  vec2 nr = rotate2(normal.xz, spin);
  vec3 local = vec3(pr.x, p0.y, pr.y) * iScale;
  float z = mod(iOffset.z + uScroll, uWrap) - uWrap + uAhead;
  vec3 world = local + vec3(iOffset.x, iOffset.y, z);
  vNormal = vec3(nr.x, normal.y, nr.y);
  vUv = aUv * 2.0 + vec2(iSeed * 5.3, iSeed * 2.9);
  vTint = 0.6 + hash11(iSeed * 91.7) * 0.4;
  vHeight = r0;
  vDepth = z;
  gl_Position = uViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform vec3 uLightDir;
uniform sampler2D uTex;
in vec3 vNormal;
in vec2 vUv;
in float vTint;
in float vHeight;
in float vDepth;
out vec4 fragColor;
float lambert(vec3 normal, vec3 lightDir) {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
void main() {
  vec3 grain = texture(uTex, vUv).xyz;
  float diffuse = lambert(vNormal, uLightDir);
  float t = clamp((vHeight - 0.72) * 1.8, 0.0, 1.0);
  vec3 grade = mix(vec3(0.55, 0.62, 0.85), vec3(1.15, 1.15, 1.25), t);
  vec3 base = grain * grade * vTint;
  vec3 lit = base * (0.35 + diffuse * 1.1);
  vec3 haze = vec3(0.0, 0.0, 0.0);
  float dist = 0.0 - vDepth;
  float fog = clamp((dist - 5.0) / 40.0, 0.0, 1.0);
  fragColor = vec4(mix(lit, haze, fog), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uScroll : f32,
  uWrap : f32,
  uAhead : f32,
  uLightDir : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
  @location(2) iOffset : vec3f,
  @location(3) iScale : f32,
  @location(4) iSeed : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vUv : vec2f,
  @location(2) vTint : f32,
  @location(3) vHeight : f32,
  @location(4) vDepth : f32,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn hash11(p : f32) -> f32 {
  return fract(sin(p * 127.1) * 43758.5453);
}
fn lambert(normal : vec3f, lightDir : vec3f) -> f32 {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
fn hash31(p : vec3f) -> f32 {
  return fract(sin(dot(p, vec3f(127.1, 311.7, 74.7))) * 43758.5453);
}
fn vnoise3(p : vec3f) -> f32 {
  let cell = vec3f(floor(p.x), floor(p.y), floor(p.z));
  let f = p - cell;
  let u = vec3f(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y), f.z * f.z * (3.0 - 2.0 * f.z));
  let n000 = hash31(cell);
  let n100 = hash31(cell + vec3f(1.0, 0.0, 0.0));
  let n010 = hash31(cell + vec3f(0.0, 1.0, 0.0));
  let n110 = hash31(cell + vec3f(1.0, 1.0, 0.0));
  let n001 = hash31(cell + vec3f(0.0, 0.0, 1.0));
  let n101 = hash31(cell + vec3f(1.0, 0.0, 1.0));
  let n011 = hash31(cell + vec3f(0.0, 1.0, 1.0));
  let n111 = hash31(cell + vec3f(1.0, 1.0, 1.0));
  let nx00 = mix(n000, n100, u.x);
  let nx10 = mix(n010, n110, u.x);
  let nx01 = mix(n001, n101, u.x);
  let nx11 = mix(n011, n111, u.x);
  let nxy0 = mix(nx00, nx10, u.y);
  let nxy1 = mix(nx01, nx11, u.y);
  return mix(nxy0, nxy1, u.z);
}
fn fbm3(p : vec3f, octaves : f32) -> f32 {
  var total = 0.0;
  var amplitude = 0.5;
  var frequency = 1.0;
  var norm = 0.0;
  for (var i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise3(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
fn rockRadius(dir : vec3f, seed : f32) -> f32 {
  let q = dir * 2.3 + vec3f(seed * 37.7, seed * 11.3, seed * 71.9);
  return 1.0 + (fbm3(q, 4.0) - 0.5) * 0.55;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let dir = normalize(bm_in.aPosition);
  let t1 = normalize(cross(dir, vec3f(0.31, 0.82, 0.47)));
  let t2 = cross(dir, t1);
  let e = 0.12;
  let d1 = normalize(dir + t1 * e);
  let d2 = normalize(dir + t2 * e);
  let r0 = rockRadius(dir, bm_in.iSeed);
  let p0 = dir * r0;
  let edge1 = d1 * rockRadius(d1, bm_in.iSeed) - p0;
  let edge2 = d2 * rockRadius(d2, bm_in.iSeed) - p0;
  let normal = normalize(cross(edge1, edge2));
  let spin = bm_u.uTime * (0.2 + bm_in.iSeed * 0.8);
  let pr = rotate2(p0.xz, spin);
  let nr = rotate2(normal.xz, spin);
  let local = vec3f(pr.x, p0.y, pr.y) * bm_in.iScale;
  let z = ((bm_in.iOffset.z + bm_u.uScroll) - (bm_u.uWrap) * floor((bm_in.iOffset.z + bm_u.uScroll) / (bm_u.uWrap))) - bm_u.uWrap + bm_u.uAhead;
  let world = local + vec3f(bm_in.iOffset.x, bm_in.iOffset.y, z);
  bm_out.vNormal = vec3f(nr.x, normal.y, nr.y);
  bm_out.vUv = bm_in.aUv * 2.0 + vec2f(bm_in.iSeed * 5.3, bm_in.iSeed * 2.9);
  bm_out.vTint = 0.6 + hash11(bm_in.iSeed * 91.7) * 0.4;
  bm_out.vHeight = r0;
  bm_out.vDepth = z;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let grain = textureSample(uTex, uTex_sampler, bm_in.vUv).xyz;
  let diffuse = lambert(bm_in.vNormal, bm_u.uLightDir);
  let t = clamp((bm_in.vHeight - 0.72) * 1.8, 0.0, 1.0);
  let grade = mix(vec3f(0.55, 0.62, 0.85), vec3f(1.15, 1.15, 1.25), t);
  let base = grain * grade * bm_in.vTint;
  let lit = base * (0.35 + diffuse * 1.1);
  let haze = vec3f(0.0, 0.0, 0.0);
  let dist = 0.0 - bm_in.vDepth;
  let fog = clamp((dist - 5.0) / 40.0, 0.0, 1.0);
  return vec4f(mix(lit, haze, fog), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'float', iSeed: 'float' },
  uniforms: { uViewProj: 'mat4', uScroll: 'float', uWrap: 'float', uAhead: 'float', uLightDir: 'vec3', uTime: 'float', uTex: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0},{"name":"iOffset","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iScale","type":"float","location":3,"size":1,"divisor":1},{"name":"iSeed","type":"float","location":4,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uScroll","type":"float","kind":"1f","size":1,"offset":64},{"name":"uWrap","type":"float","kind":"1f","size":1,"offset":68},{"name":"uAhead","type":"float","kind":"1f","size":1,"offset":72},{"name":"uLightDir","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":92},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2}],"uniformBlockSize":96},
};

export default gameRocksShader;
