/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const gameStarsShader: CompiledShader<{ aPosition: 'vec3' }, { iOffset: 'vec3'; iLen: 'float'; iSeed: 'float' }, { uViewProj: 'mat4'; uScroll: 'float'; uWrap: 'float'; uAhead: 'float'; uColor: 'vec3' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 iOffset;
layout(location = 2) in float iLen;
layout(location = 3) in float iSeed;
uniform mat4 uViewProj;
uniform float uScroll;
uniform float uWrap;
uniform float uAhead;
out float vAlpha;
void main() {
  float z = mod(iOffset.z + uScroll * (0.7 + iSeed * 0.6), uWrap) - uWrap + uAhead;
  vec3 local = vec3(aPosition.x * 0.035, aPosition.y * 0.035, aPosition.z * iLen);
  vec3 world = local + vec3(iOffset.x, iOffset.y, z);
  float closeness = clamp((z + uWrap - uAhead) / uWrap, 0.0, 1.0);
  vAlpha = (0.15 + closeness * 0.85) * (0.4 + iSeed * 0.6);
  gl_Position = uViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform vec3 uColor;
in float vAlpha;
out vec4 fragColor;
void main() {
  fragColor = vec4(uColor, vAlpha);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uScroll : f32,
  uWrap : f32,
  uAhead : f32,
  uColor : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) iOffset : vec3f,
  @location(2) iLen : f32,
  @location(3) iSeed : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vAlpha : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let z = ((bm_in.iOffset.z + bm_u.uScroll * (0.7 + bm_in.iSeed * 0.6)) - (bm_u.uWrap) * floor((bm_in.iOffset.z + bm_u.uScroll * (0.7 + bm_in.iSeed * 0.6)) / (bm_u.uWrap))) - bm_u.uWrap + bm_u.uAhead;
  let local = vec3f(bm_in.aPosition.x * 0.035, bm_in.aPosition.y * 0.035, bm_in.aPosition.z * bm_in.iLen);
  let world = local + vec3f(bm_in.iOffset.x, bm_in.iOffset.y, z);
  let closeness = clamp((z + bm_u.uWrap - bm_u.uAhead) / bm_u.uWrap, 0.0, 1.0);
  bm_out.vAlpha = (0.15 + closeness * 0.85) * (0.4 + bm_in.iSeed * 0.6);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  return vec4f(bm_u.uColor, bm_in.vAlpha);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iLen: 'float', iSeed: 'float' },
  uniforms: { uViewProj: 'mat4', uScroll: 'float', uWrap: 'float', uAhead: 'float', uColor: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iLen","type":"float","location":2,"size":1,"divisor":1},{"name":"iSeed","type":"float","location":3,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uScroll","type":"float","kind":"1f","size":1,"offset":64},{"name":"uWrap","type":"float","kind":"1f","size":1,"offset":68},{"name":"uAhead","type":"float","kind":"1f","size":1,"offset":72},{"name":"uColor","type":"vec3","kind":"3fv","size":3,"offset":80}],"uniformBlockSize":96},
};

export default gameStarsShader;
