/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const gameGlowShader: CompiledShader<{ aPosition: 'vec3' }, { iOffset: 'vec3'; iScale: 'float'; iAlpha: 'float' }, { uViewProj: 'mat4'; uColor: 'vec3' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 iOffset;
layout(location = 2) in float iScale;
layout(location = 3) in float iAlpha;
uniform mat4 uViewProj;
out float vAlpha;
void main() {
  vAlpha = iAlpha;
  gl_Position = uViewProj * vec4(aPosition * iScale + iOffset, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform vec3 uColor;
in float vAlpha;
out vec4 fragColor;
void main() {
  fragColor = vec4(uColor, vAlpha);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uColor : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) iOffset : vec3f,
  @location(2) iScale : f32,
  @location(3) iAlpha : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vAlpha : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vAlpha = bm_in.iAlpha;
  bm_out.bm_position = bm_u.uViewProj * vec4f(bm_in.aPosition * bm_in.iScale + bm_in.iOffset, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  return vec4f(bm_u.uColor, bm_in.vAlpha);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'float', iAlpha: 'float' },
  uniforms: { uViewProj: 'mat4', uColor: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iScale","type":"float","location":2,"size":1,"divisor":1},{"name":"iAlpha","type":"float","location":3,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uColor","type":"vec3","kind":"3fv","size":3,"offset":64}],"uniformBlockSize":80},
};

export default gameGlowShader;
