/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const gameRocksShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iOffset: 'vec3'; iScale: 'float'; iSeed: 'float' }, { uViewProj: 'mat4'; uScroll: 'float'; uWrap: 'float'; uAhead: 'float'; uLightDir: 'vec3'; uTime: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 aNormal;
layout(location = 2) in vec3 iOffset;
layout(location = 3) in float iScale;
layout(location = 4) in float iSeed;
uniform mat4 uViewProj;
uniform float uScroll;
uniform float uWrap;
uniform float uAhead;
uniform float uTime;
out vec3 vNormal;
out float vTint;
vec2 rotate2(vec2 p, float angle) {
  float c = cos(angle);
  float s = sin(angle);
  return vec2(p.x * c - p.y * s, p.x * s + p.y * c);
}
float hash11(float p) {
  return fract(sin(p * 127.1) * 43758.5453);
}
void main() {
  float spin = uTime * (0.2 + iSeed * 0.8);
  vec2 pr = rotate2(aPosition.xz, spin);
  vec2 nr = rotate2(aNormal.xz, spin);
  vec3 local = vec3(pr.x, aPosition.y, pr.y) * iScale;
  float z = mod(iOffset.z + uScroll, uWrap) - uWrap + uAhead;
  vec3 world = local + vec3(iOffset.x, iOffset.y, z);
  vNormal = vec3(nr.x, aNormal.y, nr.y);
  vTint = 0.6 + hash11(iSeed * 91.7) * 0.4;
  gl_Position = uViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform vec3 uLightDir;
in vec3 vNormal;
in float vTint;
out vec4 fragColor;
float lambert(vec3 normal, vec3 lightDir) {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
void main() {
  float diffuse = lambert(vNormal, uLightDir);
  vec3 base = vec3(0.6, 0.5, 0.44) * vTint;
  fragColor = vec4(base * (0.25 + diffuse * 0.85), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uScroll : f32,
  uWrap : f32,
  uAhead : f32,
  uLightDir : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iOffset : vec3f,
  @location(3) iScale : f32,
  @location(4) iSeed : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vTint : f32,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn hash11(p : f32) -> f32 {
  return fract(sin(p * 127.1) * 43758.5453);
}
fn lambert(normal : vec3f, lightDir : vec3f) -> f32 {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let spin = bm_u.uTime * (0.2 + bm_in.iSeed * 0.8);
  let pr = rotate2(bm_in.aPosition.xz, spin);
  let nr = rotate2(bm_in.aNormal.xz, spin);
  let local = vec3f(pr.x, bm_in.aPosition.y, pr.y) * bm_in.iScale;
  let z = (bm_in.iOffset.z + bm_u.uScroll - bm_u.uWrap * floor(bm_in.iOffset.z + bm_u.uScroll / bm_u.uWrap)) - bm_u.uWrap + bm_u.uAhead;
  let world = local + vec3f(bm_in.iOffset.x, bm_in.iOffset.y, z);
  bm_out.vNormal = vec3f(nr.x, bm_in.aNormal.y, nr.y);
  bm_out.vTint = 0.6 + hash11(bm_in.iSeed * 91.7) * 0.4;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let diffuse = lambert(bm_in.vNormal, bm_u.uLightDir);
  let base = vec3f(0.6, 0.5, 0.44) * bm_in.vTint;
  return vec4f(base * (0.25 + diffuse * 0.85), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'float', iSeed: 'float' },
  uniforms: { uViewProj: 'mat4', uScroll: 'float', uWrap: 'float', uAhead: 'float', uLightDir: 'vec3', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iScale","type":"float","location":3,"size":1,"divisor":1},{"name":"iSeed","type":"float","location":4,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uScroll","type":"float","kind":"1f","size":1,"offset":64},{"name":"uWrap","type":"float","kind":"1f","size":1,"offset":68},{"name":"uAhead","type":"float","kind":"1f","size":1,"offset":72},{"name":"uLightDir","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":92}],"uniformBlockSize":96},
};

export default gameRocksShader;
