/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const gamePlumeShader: CompiledShader<{ aPosition: 'vec3' }, { iOffset: 'vec3' }, { uViewProj: 'mat4'; uModel: 'mat4'; uViewPos: 'vec3'; uSize: 'vec3'; uTime: 'float'; uPulse: 'float'; uCore: 'vec3'; uEdge: 'vec3' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uModel : mat4x4f,
  uViewPos : vec3f,
  uSize : vec3f,
  uTime : f32,
  uPulse : f32,
  uCore : vec3f,
  uEdge : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) iOffset : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUnit : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vWorldPos : vec3f,
}
fn hash31(p : vec3f) -> f32 {
  return fract(sin(dot(p, vec3f(127.1, 311.7, 74.7))) * 43758.5453);
}
fn vnoise3(p : vec3f) -> f32 {
  let cell = vec3f(floor(p.x), floor(p.y), floor(p.z));
  let f = p - cell;
  let u = vec3f(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y), f.z * f.z * (3.0 - 2.0 * f.z));
  let n000 = hash31(cell);
  let n100 = hash31(cell + vec3f(1.0, 0.0, 0.0));
  let n010 = hash31(cell + vec3f(0.0, 1.0, 0.0));
  let n110 = hash31(cell + vec3f(1.0, 1.0, 0.0));
  let n001 = hash31(cell + vec3f(0.0, 0.0, 1.0));
  let n101 = hash31(cell + vec3f(1.0, 0.0, 1.0));
  let n011 = hash31(cell + vec3f(0.0, 1.0, 1.0));
  let n111 = hash31(cell + vec3f(1.0, 1.0, 1.0));
  let nx00 = mix(n000, n100, u.x);
  let nx10 = mix(n010, n110, u.x);
  let nx01 = mix(n001, n101, u.x);
  let nx11 = mix(n011, n111, u.x);
  let nxy0 = mix(nx00, nx10, u.y);
  let nxy1 = mix(nx01, nx11, u.y);
  return mix(nxy0, nxy1, u.z);
}
fn fbm3(p : vec3f, octaves : f32) -> f32 {
  var total = 0.0;
  var amplitude = 0.5;
  var frequency = 1.0;
  var norm = 0.0;
  for (var i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise3(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUnit = bm_in.aPosition;
  bm_out.vNormal = (bm_u.uModel * vec4f(bm_in.aPosition, 0.0)).xyz;
  let stretched = vec3f(bm_in.aPosition.x * bm_u.uSize.x, bm_in.aPosition.y * bm_u.uSize.y, bm_in.aPosition.z * bm_u.uSize.z) + bm_in.iOffset;
  let world = bm_u.uModel * vec4f(stretched, 1.0);
  bm_out.vWorldPos = world.xyz;
  bm_out.bm_position = bm_u.uViewProj * world;
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let viewDir = normalize(bm_u.uViewPos - bm_in.vWorldPos);
  let thickness = abs(dot(normalize(bm_in.vNormal), viewDir));
  let core = pow(thickness, 7.0);
  let halo = pow(thickness, 1.5);
  let churn = fbm3(vec3f(bm_in.vUnit.x * 2.6, bm_in.vUnit.y * 2.6, bm_in.vUnit.z * 1.7 - bm_u.uTime * 5.0), 3.0);
  let flicker = 0.72 + churn * 0.55;
  let intensity = max((core * 1.5 + halo * 0.85) * flicker * bm_u.uPulse, 0.0);
  let tint = mix(bm_u.uEdge, bm_u.uCore, core);
  return vec4f(tint * intensity, intensity);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: { iOffset: 'vec3' },
  uniforms: { uViewProj: 'mat4', uModel: 'mat4', uViewPos: 'vec3', uSize: 'vec3', uTime: 'float', uPulse: 'float', uCore: 'vec3', uEdge: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":1,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uModel","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uSize","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":156},{"name":"uPulse","type":"float","kind":"1f","size":1,"offset":160},{"name":"uCore","type":"vec3","kind":"3fv","size":3,"offset":176},{"name":"uEdge","type":"vec3","kind":"3fv","size":3,"offset":192}],"uniformBlockSize":208},

};

export default gamePlumeShader;
