/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const InstancedCubes: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iOffset: 'vec3'; iNormal: 'vec3'; iTangent: 'vec3'; iPhase: 'float'; iScale: 'vec3'; iTint: 'vec3' }, { uViewProj: 'mat4'; uViewPos: 'vec3'; uTime: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uViewPos : vec3f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iOffset : vec3f,
  @location(3) iNormal : vec3f,
  @location(4) iTangent : vec3f,
  @location(5) iPhase : f32,
  @location(6) iScale : vec3f,
  @location(7) iTint : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vColor : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vWorld : vec3f,
  @location(3) vPulse : f32,
}
fn blinnPhongSpec(normal : vec3f, lightDir : vec3f, viewDir : vec3f, shininess : f32) -> f32 {
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let bitangent = normalize(cross(bm_in.iNormal, bm_in.iTangent));
  let spin = bm_in.iPhase * 6.2831853 + bm_u.uTime * (0.2 + bm_in.iPhase * 0.35);
  let local = bm_in.aPosition * bm_in.iScale;
  let spun = rotate2(local.xz, spin);
  let wave = sin(bm_in.iPhase * 37.0 + bm_u.uTime * 2.1) * 0.65 + sin(bm_in.iPhase * 91.0 - bm_u.uTime * 1.3) * 0.22;
  let world = bm_in.iOffset + bm_in.iTangent * spun.x + bm_in.iNormal * (local.y + wave) + bitangent * spun.y;
  let normalSpun = rotate2(bm_in.aNormal.xz, spin);
  bm_out.vNormal = normalize(bm_in.iTangent * normalSpun.x + bm_in.iNormal * bm_in.aNormal.y + bitangent * normalSpun.y);
  bm_out.vWorld = world;
  bm_out.vColor = bm_in.iTint;
  bm_out.vPulse = sin(bm_in.iPhase * 58.0 - bm_u.uTime * 2.6) * 0.5 + 0.5;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let n = normalize(bm_in.vNormal);
  let light = normalize(vec3f(-0.35, 0.75, 0.55));
  let view = normalize(bm_u.uViewPos - bm_in.vWorld);
  let diffuse = max(dot(n, light), 0.0);
  let rim = pow(1.0 - clamp(dot(n, view), 0.0, 1.0), 2.4);
  let specular = blinnPhongSpec(n, light, view, 40.0);
  let lit = bm_in.vColor * (0.12 + diffuse * 1.15 + bm_in.vPulse * 0.16);
  let edge = mix(vec3f(0.18, 0.32, 1.1), vec3f(1.35, 0.42, 0.95), bm_in.vPulse);
  let color = lit + edge * (rim * 0.7) + vec3f(1.0, 0.82, 0.62) * (specular * 0.75);
  return vec4f(color, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iNormal: 'vec3', iTangent: 'vec3', iPhase: 'float', iScale: 'vec3', iTint: 'vec3' },
  uniforms: { uViewProj: 'mat4', uViewPos: 'vec3', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iNormal","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iTangent","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iPhase","type":"float","location":5,"size":1,"divisor":1},{"name":"iScale","type":"vec3","location":6,"size":3,"divisor":1},{"name":"iTint","type":"vec3","location":7,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":76}],"uniformBlockSize":80},

};

export default InstancedCubes;
