/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const LegendOfBro: CompiledShader<{ aCorner: 'vec2' }, { iPos: 'vec2'; iCell: 'vec2'; iSize: 'vec2' }, { uViewProj: 'mat4'; uCell: 'vec2'; uTile: 'float'; uAtlas: 'sampler2D' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCell : vec2f,
  uTile : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uAtlas : texture_2d<f32>;
@group(0) @binding(2) var uAtlas_sampler : sampler;
struct BmVSIn {
  @location(0) aCorner : vec2f,
  @location(1) iPos : vec2f,
  @location(2) iCell : vec2f,
  @location(3) iSize : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let span = bm_in.aCorner * bm_in.iSize;
  bm_out.vUv = (bm_in.iCell + span) * bm_u.uCell;
  let world = bm_in.iPos + span * bm_u.uTile;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world.x, world.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  return textureSample(uAtlas, uAtlas_sampler, bm_in.vUv);
}
`,
  attributes: { aCorner: 'vec2' },
  instanceAttributes: { iPos: 'vec2', iCell: 'vec2', iSize: 'vec2' },
  uniforms: { uViewProj: 'mat4', uCell: 'vec2', uTile: 'float', uAtlas: 'sampler2D' },
  layout: {"attributes":[{"name":"aCorner","type":"vec2","location":0,"size":2,"divisor":0},{"name":"iPos","type":"vec2","location":1,"size":2,"divisor":1},{"name":"iCell","type":"vec2","location":2,"size":2,"divisor":1},{"name":"iSize","type":"vec2","location":3,"size":2,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCell","type":"vec2","kind":"2fv","size":2,"offset":64},{"name":"uTile","type":"float","kind":"1f","size":1,"offset":72},{"name":"uAtlas","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2}],"uniformBlockSize":80},

};

export default LegendOfBro;
