/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const lightCubeShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3'; aColor: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uModel: 'mat4'; uLightPos: 'vec3'; uViewPos: 'vec3' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 aNormal;
layout(location = 2) in vec3 aColor;
uniform mat4 uViewProj;
uniform mat4 uModel;
out vec3 vNormal;
out vec3 vColor;
out vec3 vWorldPos;
void main() {
  vec4 world = uModel * vec4(aPosition, 1.0);
  vWorldPos = world.xyz;
  vNormal = (uModel * vec4(aNormal, 0.0)).xyz;
  vColor = aColor;
  gl_Position = uViewProj * world;
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform vec3 uLightPos;
uniform vec3 uViewPos;
in vec3 vNormal;
in vec3 vColor;
in vec3 vWorldPos;
out vec4 fragColor;
void main() {
  float ambient = 0.25;
  vec3 n = normalize(vNormal);
  vec3 lightDir = normalize(uLightPos - vWorldPos);
  float diffuse = max(dot(n, lightDir), 0.0);
  vec3 viewDir = normalize(uViewPos - vWorldPos);
  vec3 halfway = normalize(lightDir + viewDir);
  float specular = pow(max(dot(n, halfway), 0.0), 32.0) * 0.4;
  vec3 lit = vColor * (ambient + diffuse) + vec3(1.0, 1.0, 1.0) * specular;
  fragColor = vec4(lit, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3', aColor: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uModel: 'mat4', uLightPos: 'vec3', uViewPos: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"aColor","type":"vec3","location":2,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16},{"name":"uModel","type":"mat4","kind":"m4fv","size":16},{"name":"uLightPos","type":"vec3","kind":"3fv","size":3},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3}]},
};

export default lightCubeShader;
