/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const modelShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uViewProj: 'mat4'; uModel: 'mat4'; uLightDir: 'vec3'; uViewPos: 'vec3'; uTex: 'sampler2D' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 aNormal;
layout(location = 2) in vec2 aUv;
uniform mat4 uViewProj;
uniform mat4 uModel;
out vec3 vNormal;
out vec2 vUv;
out vec3 vWorldPos;
void main() {
  vec4 world = uModel * vec4(aPosition, 1.0);
  vWorldPos = world.xyz;
  vNormal = (uModel * vec4(aNormal, 0.0)).xyz;
  vUv = aUv;
  gl_Position = uViewProj * world;
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform vec3 uLightDir;
uniform vec3 uViewPos;
uniform sampler2D uTex;
in vec3 vNormal;
in vec2 vUv;
in vec3 vWorldPos;
out vec4 fragColor;
float lambert(vec3 normal, vec3 lightDir) {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
float blinnPhongSpec(vec3 normal, vec3 lightDir, vec3 viewDir, float shininess) {
  vec3 halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
vec3 hemisphereLight(vec3 normal, vec3 skyColor, vec3 groundColor) {
  float blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
void main() {
  vec3 base = texture(uTex, vUv).xyz;
  vec3 viewDir = normalize(uViewPos - vWorldPos);
  float diffuse = lambert(vNormal, uLightDir);
  float specular = blinnPhongSpec(vNormal, uLightDir, viewDir, 48.0) * 0.35;
  vec3 ambient = hemisphereLight(vNormal, vec3(0.55, 0.6, 0.75), vec3(0.25, 0.22, 0.3));
  vec3 lit = base * (ambient * 0.5 + vec3(1.0, 1.0, 1.0) * (diffuse * 0.85));
  fragColor = vec4(lit + vec3(1.0, 1.0, 1.0) * specular, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uModel : mat4x4f,
  uLightDir : vec3f,
  uViewPos : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vUv : vec2f,
  @location(2) vWorldPos : vec3f,
}
fn lambert(normal : vec3f, lightDir : vec3f) -> f32 {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
fn blinnPhongSpec(normal : vec3f, lightDir : vec3f, viewDir : vec3f, shininess : f32) -> f32 {
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
fn hemisphereLight(normal : vec3f, skyColor : vec3f, groundColor : vec3f) -> vec3f {
  let blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = bm_u.uModel * vec4f(bm_in.aPosition, 1.0);
  bm_out.vWorldPos = world.xyz;
  bm_out.vNormal = (bm_u.uModel * vec4f(bm_in.aNormal, 0.0)).xyz;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = bm_u.uViewProj * world;
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let base = textureSample(uTex, uTex_sampler, bm_in.vUv).xyz;
  let viewDir = normalize(bm_u.uViewPos - bm_in.vWorldPos);
  let diffuse = lambert(bm_in.vNormal, bm_u.uLightDir);
  let specular = blinnPhongSpec(bm_in.vNormal, bm_u.uLightDir, viewDir, 48.0) * 0.35;
  let ambient = hemisphereLight(bm_in.vNormal, vec3f(0.55, 0.6, 0.75), vec3f(0.25, 0.22, 0.3));
  let lit = base * (ambient * 0.5 + vec3f(1.0, 1.0, 1.0) * (diffuse * 0.85));
  return vec4f(lit + vec3f(1.0, 1.0, 1.0) * specular, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uModel: 'mat4', uLightDir: 'vec3', uViewPos: 'vec3', uTex: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":2,"size":2,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uModel","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uLightDir","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2}],"uniformBlockSize":160},
};

export default modelShader;
