/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const NaniteCull: CompiledShader<Record<string, never>, Record<string, never>, { uViewProj: 'mat4'; uCamera: 'vec3'; uHighVisible: 'storage'; uMidVisible: 'storage'; uLowVisible: 'storage'; uHighArgs: 'storage'; uMidArgs: 'storage'; uLowArgs: 'storage' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCamera : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var<storage, read_write> uHighVisible : array<f32>;
@group(0) @binding(2) var<storage, read_write> uMidVisible : array<f32>;
@group(0) @binding(3) var<storage, read_write> uLowVisible : array<f32>;
@group(0) @binding(4) var<storage, read_write> uHighArgs : array<atomic<u32>>;
@group(0) @binding(5) var<storage, read_write> uMidArgs : array<atomic<u32>>;
@group(0) @binding(6) var<storage, read_write> uLowArgs : array<atomic<u32>>;
@compute @workgroup_size(64, 1, 1)
fn cs_main(@builtin(global_invocation_id) bm_gid : vec3u) {
  let id = vec3f(bm_gid);
  let instance = id.x;
  let column = ((instance) - (400.0) * floor((instance) / (400.0)));
  let row = floor(instance / 400.0);
  let world = vec3f((column - 200.0) * 4.0, -1.0, (row - 200.0) * 4.0);
  let clip = bm_u.uViewProj * vec4f(world, 1.0);
  let margin = clip.w * 0.025;
  if (clip.w > 0.0 && abs(clip.x) <= clip.w + margin && abs(clip.y) <= clip.w + margin && clip.z >= 0.0 && clip.z <= clip.w) {
    let distanceToCamera = length(world - bm_u.uCamera);
    if (distanceToCamera < 42.0) {
      let slot = f32(atomicAdd(&uHighArgs[u32(1.0)], u32(1.0)));
      uHighVisible[u32(slot)] = instance;
    } else {
      if (distanceToCamera < 125.0) {
        let slot = f32(atomicAdd(&uMidArgs[u32(1.0)], u32(1.0)));
        uMidVisible[u32(slot)] = instance;
      } else {
        let slot = f32(atomicAdd(&uLowArgs[u32(1.0)], u32(1.0)));
        uLowVisible[u32(slot)] = instance;
      }
    }
  }
}
`,
  attributes: {},
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uCamera: 'vec3', uHighVisible: 'storage', uMidVisible: 'storage', uLowVisible: 'storage', uHighArgs: 'storage', uMidArgs: 'storage', uLowArgs: 'storage' },
  layout: {"attributes":[],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCamera","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uHighVisible","type":"storage","kind":"1i","size":1,"unit":0,"textureBinding":1},{"name":"uMidVisible","type":"storage","kind":"1i","size":1,"unit":1,"textureBinding":2},{"name":"uLowVisible","type":"storage","kind":"1i","size":1,"unit":2,"textureBinding":3},{"name":"uHighArgs","type":"storage","kind":"1i","size":1,"unit":3,"textureBinding":4},{"name":"uMidArgs","type":"storage","kind":"1i","size":1,"unit":4,"textureBinding":5},{"name":"uLowArgs","type":"storage","kind":"1i","size":1,"unit":5,"textureBinding":6}],"uniformBlockSize":80},
  storageWritten: ["uHighArgs","uHighVisible","uMidArgs","uMidVisible","uLowArgs","uLowVisible"],
  hasCompute: true,

};

export default NaniteCull;
