/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const NaniteStyle: CompiledShader<{ aPosition: 'vec3'; aClusterColor: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uTime: 'float'; uVisible: 'storage' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var<storage, read> uVisible : array<f32>;
struct BmVSIn {
  @builtin(instance_index) bm_instance_index : u32,
  @location(0) aPosition : vec3f,
  @location(1) aClusterColor : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vColor : vec3f,
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let instance = uVisible[u32(f32(bm_in.bm_instance_index))];
  let column = ((instance) - (400.0) * floor((instance) / (400.0)));
  let row = floor(instance / 400.0);
  let offset = vec3f((column - 200.0) * 4.0, -1.0, (row - 200.0) * 4.0);
  let angle = instance + bm_u.uTime;
  let spun = rotate2(bm_in.aPosition.xz, angle);
  let local = vec3f(spun.x, bm_in.aPosition.y, spun.y);
  let world = local + offset;
  let tint = vec3f(sin(instance * 0.017 + bm_in.aClusterColor.x * 17.3) * 0.4 + 0.6, sin(instance * 0.023 + bm_in.aClusterColor.y * 19.7 + 2.1) * 0.4 + 0.6, sin(instance * 0.031 + bm_in.aClusterColor.z * 23.9 + 4.2) * 0.4 + 0.6);
  let varied = mix(bm_in.aClusterColor, tint, 0.68);
  bm_out.vColor = mix(varied, vec3f(1.0), 0.28);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  return vec4f(bm_in.vColor, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aClusterColor: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uTime: 'float', uVisible: 'storage' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aClusterColor","type":"vec3","location":1,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":64},{"name":"uVisible","type":"storage","kind":"1i","size":1,"unit":0,"textureBinding":1}],"uniformBlockSize":80},

};

export default NaniteStyle;
