/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const oceanCsFftShader: CompiledShader<Record<string, never>, Record<string, never>, { uStage: 'float'; uVertical: 'float'; uCount: 'float'; uSource: 'storage'; uTarget: 'storage' }> = {
  vertexSrc: ``,
  fragmentSrc: ``,
  wgslSrc: `struct BmUniforms {
  uStage : f32,
  uVertical : f32,
  uCount : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var<storage, read> uSource : array<vec4f>;
@group(0) @binding(2) var<storage, read_write> uTarget : array<vec4f>;
fn complexMul(a : vec2f, b : vec2f) -> vec2f {
  return vec2f(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x);
}
fn bitReverse(index : f32) -> f32 {
  let stages = 7.0;
  var value = index;
  var reversed = 0.0;
  for (var i = 0.0; i < stages; i = i + 1.0) {
    reversed = reversed * 2.0 + ((value) - (2.0) * floor((value) / (2.0)));
    value = floor(value / 2.0);
  }
  return reversed;
}
@compute @workgroup_size(64, 1, 1)
fn cs_main(@builtin(global_invocation_id) bm_gid : vec3u) {
  let id = vec3f(bm_gid);
  let size = 128.0;
  let twoPi = 6.283185307179586;
  let index = min(floor(id.x), max(bm_u.uCount - 1.0, 0.0));
  let x = ((index) - (size) * floor((index) / (size)));
  let y = floor(index / size);
  let along = mix(x, y, bm_u.uVertical);
  let span = pow(2.0, bm_u.uStage);
  let wing = step(((along) - (span * 2.0) * floor((along) / (span * 2.0))), span - 0.5);
  let twiddleK = ((along * (size / (span * 2.0))) - (size) * floor((along * (size / (span * 2.0))) / (size)));
  let angle = twoPi * twiddleK / size;
  let twiddle = vec2f(cos(angle), sin(angle));
  let rawTop = mix(along - span, along, wing);
  let rawBottom = mix(along, along + span, wing);
  let first = step(bm_u.uStage, 0.5);
  let topIndex = mix(rawTop, bitReverse(rawTop), first);
  let bottomIndex = mix(rawBottom, bitReverse(rawBottom), first);
  let topLinear = mix(y * size + topIndex, topIndex * size + x, bm_u.uVertical);
  let bottomLinear = mix(y * size + bottomIndex, bottomIndex * size + x, bm_u.uVertical);
  let top = uSource[u32(topLinear)];
  let bottom = uSource[u32(bottomLinear)];
  let a = vec2f(top.x, top.y) + complexMul(twiddle, vec2f(bottom.x, bottom.y));
  let b = vec2f(top.z, top.w) + complexMul(twiddle, vec2f(bottom.z, bottom.w));
  uTarget[u32(index)] = vec4f(a.x, a.y, b.x, b.y);
}
`,
  attributes: {},
  instanceAttributes: {},
  uniforms: { uStage: 'float', uVertical: 'float', uCount: 'float', uSource: 'storage', uTarget: 'storage' },
  layout: {"attributes":[],"uniforms":[{"name":"uStage","type":"float","kind":"1f","size":1,"offset":0},{"name":"uVertical","type":"float","kind":"1f","size":1,"offset":4},{"name":"uCount","type":"float","kind":"1f","size":1,"offset":8},{"name":"uSource","type":"storage","kind":"1i","size":1,"unit":0,"textureBinding":1},{"name":"uTarget","type":"storage","kind":"1i","size":1,"unit":1,"textureBinding":2}],"uniformBlockSize":16},
  storageWritten: ["uTarget"],
  hasCompute: true,

};

export default oceanCsFftShader;
