/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const oceanShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uViewProj: 'mat4'; uModel: 'mat4'; uTime: 'float'; uViewPos: 'vec3'; uSunDir: 'vec3' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
uniform mat4 uViewProj;
uniform mat4 uModel;
uniform float uTime;
out vec3 vNormal;
out vec3 vWorldPos;
out vec2 vUv;
vec3 gerstner(vec2 p, float dirX, float dirY, float steepness, float wavelength, float time) {
  float k = 6.28318 / wavelength;
  float c = sqrt(9.8 / k);
  vec2 d = normalize(vec2(dirX, dirY));
  float f = k * (dot(d, p) - c * time);
  float a = steepness / k;
  return vec3(d.x * a * cos(f), d.y * a * cos(f), a * sin(f));
}
vec3 oceanOffset(vec2 p, float time) {
  vec3 w1 = gerstner(p, 1.0, 0.6, 0.18, 5.2, time);
  vec3 w2 = gerstner(p, -0.7, 1.0, 0.14, 3.1, time);
  vec3 w3 = gerstner(p, 1.0, -1.3, 0.1, 1.8, time);
  vec3 w4 = gerstner(p, -0.4, -0.9, 0.08, 1.1, time);
  return w1 + w2 + w3 + w4;
}
void main() {
  vec2 p = aPosition.xy;
  vec3 off = oceanOffset(p, uTime);
  float e = 0.06;
  vec2 px = vec2(p.x + e, p.y);
  vec2 py = vec2(p.x, p.y + e);
  vec3 offX = oceanOffset(px, uTime);
  vec3 offY = oceanOffset(py, uTime);
  vec3 base = vec3(p.x, p.y, 0.0) + off;
  vec3 tangentX = vec3(px.x, px.y, 0.0) + offX - base;
  vec3 tangentY = vec3(py.x, py.y, 0.0) + offY - base;
  vec3 normal = normalize(cross(tangentX, tangentY));
  vec4 world = uModel * vec4(base, 1.0);
  vWorldPos = world.xyz;
  vNormal = (uModel * vec4(normal, 0.0)).xyz;
  vUv = aUv;
  gl_Position = uViewProj * world;
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform vec3 uViewPos;
uniform vec3 uSunDir;
in vec3 vNormal;
in vec3 vWorldPos;
in vec2 vUv;
out vec4 fragColor;
float hash21(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}
float vnoise2(vec2 p) {
  vec2 cell = vec2(floor(p.x), floor(p.y));
  vec2 f = p - cell;
  vec2 u = vec2(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y));
  float a = hash21(cell);
  float b = hash21(cell + vec2(1.0, 0.0));
  float c = hash21(cell + vec2(0.0, 1.0));
  float d = hash21(cell + vec2(1.0, 1.0));
  return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}
float fbm2(vec2 p, float octaves) {
  float total = 0.0;
  float amplitude = 0.5;
  float frequency = 1.0;
  float norm = 0.0;
  for (float i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise2(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
float fresnel(vec3 normal, vec3 viewDir, float power) {
  float base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
float blinnPhongSpec(vec3 normal, vec3 lightDir, vec3 viewDir, float shininess) {
  vec3 halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
void main() {
  vec2 q = vUv * 60.0 + vec2(uTime * 0.6, uTime * 0.35);
  float e = 0.35;
  float h0 = fbm2(q, 3.0);
  float hx = fbm2(q + vec2(e, 0.0), 3.0);
  float hy = fbm2(q + vec2(0.0, e), 3.0);
  vec3 ripple = vec3((h0 - hx) * 1.4, 0.0, (h0 - hy) * 1.4);
  vec3 n = normalize(normalize(vNormal) + ripple);
  vec3 viewDir = normalize(uViewPos - vWorldPos);
  vec3 skyColor = vec3(0.09, 0.11, 0.2);
  vec3 deepColor = vec3(0.012, 0.035, 0.06);
  float rim = fresnel(n, viewDir, 5.0);
  float facing = max(dot(n, viewDir), 0.0);
  vec3 body = mix(deepColor, vec3(0.03, 0.1, 0.14), facing);
  vec3 color = mix(body, skyColor, clamp(rim * 1.4, 0.0, 1.0));
  float glint = blinnPhongSpec(n, uSunDir, viewDir, 900.0);
  float sheen = blinnPhongSpec(n, uSunDir, viewDir, 24.0);
  vec3 moon = vec3(1.0, 0.97, 0.88);
  color = color + moon * (glint * 2.2) + moon * (sheen * 0.12);
  float lift = clamp(vWorldPos.y * 1.3 + 0.15, 0.0, 1.0);
  color = color + vec3(0.05, 0.09, 0.11) * pow(lift, 3.0);
  fragColor = vec4(color, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uModel : mat4x4f,
  uTime : f32,
  uViewPos : vec3f,
  uSunDir : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vWorldPos : vec3f,
  @location(2) vUv : vec2f,
}
fn hash21(p : vec2f) -> f32 {
  return fract(sin(dot(p, vec2f(127.1, 311.7))) * 43758.5453);
}
fn vnoise2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  let u = vec2f(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y));
  let a = hash21(cell);
  let b = hash21(cell + vec2f(1.0, 0.0));
  let c = hash21(cell + vec2f(0.0, 1.0));
  let d = hash21(cell + vec2f(1.0, 1.0));
  return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}
fn fbm2(p : vec2f, octaves : f32) -> f32 {
  var total = 0.0;
  var amplitude = 0.5;
  var frequency = 1.0;
  var norm = 0.0;
  for (var i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise2(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
fn fresnel(normal : vec3f, viewDir : vec3f, power : f32) -> f32 {
  let base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
fn blinnPhongSpec(normal : vec3f, lightDir : vec3f, viewDir : vec3f, shininess : f32) -> f32 {
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
fn gerstner(p : vec2f, dirX : f32, dirY : f32, steepness : f32, wavelength : f32, time : f32) -> vec3f {
  let k = 6.28318 / wavelength;
  let c = sqrt(9.8 / k);
  let d = normalize(vec2f(dirX, dirY));
  let f = k * (dot(d, p) - c * time);
  let a = steepness / k;
  return vec3f(d.x * a * cos(f), d.y * a * cos(f), a * sin(f));
}
fn oceanOffset(p : vec2f, time : f32) -> vec3f {
  let w1 = gerstner(p, 1.0, 0.6, 0.18, 5.2, time);
  let w2 = gerstner(p, -0.7, 1.0, 0.14, 3.1, time);
  let w3 = gerstner(p, 1.0, -1.3, 0.1, 1.8, time);
  let w4 = gerstner(p, -0.4, -0.9, 0.08, 1.1, time);
  return w1 + w2 + w3 + w4;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let p = bm_in.aPosition.xy;
  let off = oceanOffset(p, bm_u.uTime);
  let e = 0.06;
  let px = vec2f(p.x + e, p.y);
  let py = vec2f(p.x, p.y + e);
  let offX = oceanOffset(px, bm_u.uTime);
  let offY = oceanOffset(py, bm_u.uTime);
  let base = vec3f(p.x, p.y, 0.0) + off;
  let tangentX = vec3f(px.x, px.y, 0.0) + offX - base;
  let tangentY = vec3f(py.x, py.y, 0.0) + offY - base;
  let normal = normalize(cross(tangentX, tangentY));
  let world = bm_u.uModel * vec4f(base, 1.0);
  bm_out.vWorldPos = world.xyz;
  bm_out.vNormal = (bm_u.uModel * vec4f(normal, 0.0)).xyz;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = bm_u.uViewProj * world;
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let q = bm_in.vUv * 60.0 + vec2f(bm_u.uTime * 0.6, bm_u.uTime * 0.35);
  let e = 0.35;
  let h0 = fbm2(q, 3.0);
  let hx = fbm2(q + vec2f(e, 0.0), 3.0);
  let hy = fbm2(q + vec2f(0.0, e), 3.0);
  let ripple = vec3f((h0 - hx) * 1.4, 0.0, (h0 - hy) * 1.4);
  let n = normalize(normalize(bm_in.vNormal) + ripple);
  let viewDir = normalize(bm_u.uViewPos - bm_in.vWorldPos);
  let skyColor = vec3f(0.09, 0.11, 0.2);
  let deepColor = vec3f(0.012, 0.035, 0.06);
  let rim = fresnel(n, viewDir, 5.0);
  let facing = max(dot(n, viewDir), 0.0);
  let body = mix(deepColor, vec3f(0.03, 0.1, 0.14), facing);
  var color = mix(body, skyColor, clamp(rim * 1.4, 0.0, 1.0));
  let glint = blinnPhongSpec(n, bm_u.uSunDir, viewDir, 900.0);
  let sheen = blinnPhongSpec(n, bm_u.uSunDir, viewDir, 24.0);
  let moon = vec3f(1.0, 0.97, 0.88);
  color = color + moon * (glint * 2.2) + moon * (sheen * 0.12);
  let lift = clamp(bm_in.vWorldPos.y * 1.3 + 0.15, 0.0, 1.0);
  color = color + vec3f(0.05, 0.09, 0.11) * pow(lift, 3.0);
  return vec4f(color, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uModel: 'mat4', uTime: 'float', uViewPos: 'vec3', uSunDir: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uModel","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":128},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uSunDir","type":"vec3","kind":"3fv","size":3,"offset":160}],"uniformBlockSize":176},
};

export default oceanShader;
