/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const oceanCsAssembleShader: CompiledShader<Record<string, never>, Record<string, never>, { uPatchSize: 'float'; uChoppiness: 'float'; uScale: 'float'; uFoamThreshold: 'float'; uCount: 'float'; uTransform: 'storage'; uDisplacement: 'storage' }> = {
  vertexSrc: ``,
  fragmentSrc: ``,
  wgslSrc: `struct BmUniforms {
  uPatchSize : f32,
  uChoppiness : f32,
  uScale : f32,
  uFoamThreshold : f32,
  uCount : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var<storage, read> uTransform : array<vec4f>;
@group(0) @binding(2) var<storage, read_write> uDisplacement : array<vec4f>;
@compute @workgroup_size(64, 1, 1)
fn cs_main(@builtin(global_invocation_id) bm_gid : vec3u) {
  let id = vec3f(bm_gid);
  let size = 128.0;
  let index = min(floor(id.x), max(bm_u.uCount - 1.0, 0.0));
  let x = ((index) - (size) * floor((index) / (size)));
  let y = floor(index / size);
  let sign = 1.0 - 2.0 * ((x + y) - (2.0) * floor((x + y) / (2.0)));
  let gain = bm_u.uScale * sign;
  let centre = uTransform[u32(index)];
  let dx = centre.x * bm_u.uChoppiness * gain;
  let dy = centre.y * gain;
  let dz = centre.z * bm_u.uChoppiness * gain;
  let rightIndex = y * size + ((x + 1.0) - (size) * floor((x + 1.0) / (size)));
  let upIndex = ((y + 1.0) - (size) * floor((y + 1.0) / (size))) * size + x;
  let right = uTransform[u32(rightIndex)];
  let up = uTransform[u32(upIndex)];
  let perMetre = size / bm_u.uPatchSize;
  let dxdx = (0.0 - right.x * bm_u.uChoppiness * gain - dx) * perMetre;
  let dzdx = (0.0 - right.z * bm_u.uChoppiness * gain - dz) * perMetre;
  let dxdz = (0.0 - up.x * bm_u.uChoppiness * gain - dx) * perMetre;
  let dzdz = (0.0 - up.z * bm_u.uChoppiness * gain - dz) * perMetre;
  let jacobian = (1.0 + dxdx) * (1.0 + dzdz) - dxdz * dzdx;
  let foam = max(bm_u.uFoamThreshold - jacobian, 0.0);
  uDisplacement[u32(index)] = vec4f(dx, dy, dz, foam);
}
`,
  attributes: {},
  instanceAttributes: {},
  uniforms: { uPatchSize: 'float', uChoppiness: 'float', uScale: 'float', uFoamThreshold: 'float', uCount: 'float', uTransform: 'storage', uDisplacement: 'storage' },
  layout: {"attributes":[],"uniforms":[{"name":"uPatchSize","type":"float","kind":"1f","size":1,"offset":0},{"name":"uChoppiness","type":"float","kind":"1f","size":1,"offset":4},{"name":"uScale","type":"float","kind":"1f","size":1,"offset":8},{"name":"uFoamThreshold","type":"float","kind":"1f","size":1,"offset":12},{"name":"uCount","type":"float","kind":"1f","size":1,"offset":16},{"name":"uTransform","type":"storage","kind":"1i","size":1,"unit":0,"textureBinding":1},{"name":"uDisplacement","type":"storage","kind":"1i","size":1,"unit":1,"textureBinding":2}],"uniformBlockSize":32},
  storageWritten: ["uDisplacement"],
  hasCompute: true,

};

export default oceanCsAssembleShader;
