/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const OceanCsEvolve: CompiledShader<Record<string, never>, Record<string, never>, { uPatchSize: 'float'; uTime: 'float'; uCount: 'float'; uSpectrum: 'storage'; uField: 'storage' }> = {
  wgslSrc: `struct BmUniforms {
  uPatchSize : f32,
  uTime : f32,
  uCount : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var<storage, read> uSpectrum : array<vec4f>;
@group(0) @binding(2) var<storage, read_write> uField : array<vec4f>;
fn complexMul(a : vec2f, b : vec2f) -> vec2f {
  return vec2f(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x);
}
@compute @workgroup_size(64, 1, 1)
fn cs_main(@builtin(global_invocation_id) bm_gid : vec3u) {
  let id = vec3f(bm_gid);
  let size = 128.0;
  let twoPi = 6.283185307179586;
  let gravity = 9.81;
  let index = min(floor(id.x), max(bm_u.uCount - 1.0, 0.0));
  let x = ((index) - (size) * floor((index) / (size)));
  let y = floor(index / size);
  let n = x - size * 0.5;
  let m = y - size * 0.5;
  let delta = twoPi / bm_u.uPatchSize;
  let k = vec2f(n * delta, m * delta);
  let kLength = length(k);
  let alive = step(0.0001, kLength);
  let safeLength = max(kLength, 0.0001);
  let seed = uSpectrum[u32(index)];
  let positive = vec2f(seed.x, seed.y);
  let negative = vec2f(seed.z, 0.0 - seed.w);
  let omega = sqrt(gravity * safeLength) * bm_u.uTime;
  let phase = vec2f(cos(omega), sin(omega));
  let conjugate = vec2f(phase.x, 0.0 - phase.y);
  let height = complexMul(positive, phase) + complexMul(negative, conjugate);
  let unit = vec2f(k.x / safeLength * alive, k.y / safeLength * alive);
  let displaceX = vec2f(height.y * unit.x, 0.0 - height.x * unit.x);
  let displaceZ = vec2f(height.y * unit.y, 0.0 - height.x * unit.y);
  uField[u32(index)] = vec4f(displaceX.x - height.y, displaceX.y + height.x, displaceZ.x, displaceZ.y);
}
`,
  attributes: {},
  instanceAttributes: {},
  uniforms: { uPatchSize: 'float', uTime: 'float', uCount: 'float', uSpectrum: 'storage', uField: 'storage' },
  layout: {"attributes":[],"uniforms":[{"name":"uPatchSize","type":"float","kind":"1f","size":1,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":4},{"name":"uCount","type":"float","kind":"1f","size":1,"offset":8},{"name":"uSpectrum","type":"storage","kind":"1i","size":1,"unit":0,"textureBinding":1},{"name":"uField","type":"storage","kind":"1i","size":1,"unit":1,"textureBinding":2}],"uniformBlockSize":16},
  storageWritten: ["uField"],
  hasCompute: true,

};

export default OceanCsEvolve;
