/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const oceanCsSpectrumShader: CompiledShader<Record<string, never>, Record<string, never>, { uPatchSize: 'float'; uWindDir: 'vec2'; uWindSpeed: 'float'; uPeakWavelength: 'float'; uAmplitude: 'float'; uSpread: 'float'; uBand: 'vec2'; uSeed: 'float'; uCount: 'float'; uSpectrum: 'storage' }> = {
  wgslSrc: `struct BmUniforms {
  uPatchSize : f32,
  uWindDir : vec2f,
  uWindSpeed : f32,
  uPeakWavelength : f32,
  uAmplitude : f32,
  uSpread : f32,
  uBand : vec2f,
  uSeed : f32,
  uCount : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var<storage, read_write> uSpectrum : array<vec4f>;
fn hash22(p : vec2f) -> vec2f {
  let k = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return vec2f(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
fn gaussian(seed : vec2f) -> vec2f {
  let twoPi = 6.283185307179586;
  let u = hash22(seed);
  let radius = sqrt(0.0 - 2.0 * log(max(u.x, 0.000001)));
  let angle = twoPi * u.y;
  return vec2f(radius * cos(angle), radius * sin(angle));
}
fn jonswap(omega : f32, peak : f32) -> f32 {
  let gravity = 9.81;
  let gamma = 3.3;
  let sigma = mix(0.07, 0.09, step(peak, omega));
  let relative = (omega - peak) / (sigma * peak);
  let enhancement = pow(gamma, exp(-0.5 * relative * relative));
  let shape = exp(-1.25 * pow(peak / omega, 4.0));
  return 0.0081 * gravity * gravity * shape * enhancement / pow(omega, 5.0);
}
@compute @workgroup_size(64, 1, 1)
fn cs_main(@builtin(global_invocation_id) bm_gid : vec3u) {
  let id = vec3f(bm_gid);
  let size = 128.0;
  let twoPi = 6.283185307179586;
  let gravity = 9.81;
  let index = min(floor(id.x), max(bm_u.uCount - 1.0, 0.0));
  let x = ((index) - (size) * floor((index) / (size)));
  let y = floor(index / size);
  let n = x - size * 0.5;
  let m = y - size * 0.5;
  let delta = twoPi / bm_u.uPatchSize;
  let k = vec2f(n * delta, m * delta);
  let kLength = length(k);
  let alive = step(0.0001, kLength);
  let safeLength = max(kLength, 0.0001);
  let direction = normalize(vec2f(k.x + 0.000001, k.y));
  let omega = sqrt(gravity * safeLength);
  let peak = sqrt(gravity * twoPi / max(bm_u.uPeakWavelength, 0.5));
  let energy = jonswap(max(omega, 0.001), peak);
  let dOmegaDk = gravity / (2.0 * omega);
  let alignment = dot(direction, normalize(bm_u.uWindDir));
  let forward = pow(max(alignment, 0.0), bm_u.uSpread);
  let backward = 0.25 * pow(max(0.0 - alignment, 0.0), bm_u.uSpread);
  let spread = forward + backward;
  let smallest = 0.002 * bm_u.uWindSpeed * bm_u.uWindSpeed;
  let cutoff = exp(-safeLength * safeLength * smallest * smallest);
  let band = step(bm_u.uBand.x, kLength) * step(kLength, bm_u.uBand.y);
  let windScale = pow(max(bm_u.uWindSpeed, 0.1) / 10.0, 2.0);
  let variance = 2.0 * energy * spread * dOmegaDk * delta * delta * windScale * bm_u.uAmplitude * cutoff / safeLength;
  let scale = sqrt(max(variance, 0.0)) * 0.7071067811865476 * alive * band;
  let positive = gaussian(vec2f(x + bm_u.uSeed, y + bm_u.uSeed * 1.7));
  let negative = gaussian(vec2f(size - x + bm_u.uSeed * 3.1, size - y + bm_u.uSeed * 2.3));
  uSpectrum[u32(index)] = vec4f(positive.x * scale, positive.y * scale, negative.x * scale, negative.y * scale);
}
`,
  attributes: {},
  instanceAttributes: {},
  uniforms: { uPatchSize: 'float', uWindDir: 'vec2', uWindSpeed: 'float', uPeakWavelength: 'float', uAmplitude: 'float', uSpread: 'float', uBand: 'vec2', uSeed: 'float', uCount: 'float', uSpectrum: 'storage' },
  layout: {"attributes":[],"uniforms":[{"name":"uPatchSize","type":"float","kind":"1f","size":1,"offset":0},{"name":"uWindDir","type":"vec2","kind":"2fv","size":2,"offset":8},{"name":"uWindSpeed","type":"float","kind":"1f","size":1,"offset":16},{"name":"uPeakWavelength","type":"float","kind":"1f","size":1,"offset":20},{"name":"uAmplitude","type":"float","kind":"1f","size":1,"offset":24},{"name":"uSpread","type":"float","kind":"1f","size":1,"offset":28},{"name":"uBand","type":"vec2","kind":"2fv","size":2,"offset":32},{"name":"uSeed","type":"float","kind":"1f","size":1,"offset":40},{"name":"uCount","type":"float","kind":"1f","size":1,"offset":44},{"name":"uSpectrum","type":"storage","kind":"1i","size":1,"unit":0,"textureBinding":1}],"uniformBlockSize":48},
  storageWritten: ["uSpectrum"],
  hasCompute: true,

};

export default oceanCsSpectrumShader;
