/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const shadowSceneShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3' }, { iOffset: 'vec3'; iScale: 'vec3'; iSpin: 'float'; iColor: 'vec3'; iGround: 'float' }, { uViewProj: 'mat4'; uLightViewProj: 'mat4'; uShadowMap: 'sampler2D'; uLightPos: 'vec3'; uViewPos: 'vec3'; uLightColor: 'vec3'; uSkyColor: 'vec3'; uGroundColor: 'vec3'; uFogColor: 'vec3'; uTime: 'float'; uRange: 'float'; uTexel: 'float'; uSoftness: 'float'; uBias: 'float'; uShadowStrength: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uLightViewProj : mat4x4f,
  uLightPos : vec3f,
  uViewPos : vec3f,
  uLightColor : vec3f,
  uSkyColor : vec3f,
  uGroundColor : vec3f,
  uFogColor : vec3f,
  uTime : f32,
  uRange : f32,
  uTexel : f32,
  uSoftness : f32,
  uBias : f32,
  uShadowStrength : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uShadowMap : texture_2d<f32>;
@group(0) @binding(2) var uShadowMap_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) iOffset : vec3f,
  @location(3) iScale : vec3f,
  @location(4) iSpin : f32,
  @location(5) iColor : vec3f,
  @location(6) iGround : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vColor : vec3f,
  @location(3) vGround : f32,
}
fn rotate3(p : vec3f, axis : vec3f, angle : f32) -> vec3f {
  let a = normalize(axis);
  let c = cos(angle);
  let s = sin(angle);
  return p * c + cross(a, p) * s + a * (dot(a, p) * (1.0 - c));
}
fn blinnPhongSpec(normal : vec3f, lightDir : vec3f, viewDir : vec3f, shininess : f32) -> f32 {
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
fn hemisphereLight(normal : vec3f, skyColor : vec3f, groundColor : vec3f) -> vec3f {
  let blend = normalize(normal).y * 0.5 + 0.5;
  return mix(groundColor, skyColor, blend);
}
fn tonemapACES(color : vec3f) -> vec3f {
  let num = color * (color * 2.51 + vec3f(0.03, 0.03, 0.03));
  let den = color * (color * 2.43 + vec3f(0.59, 0.59, 0.59)) + vec3f(0.14, 0.14, 0.14);
  return clamp(num / den, vec3f(0.0), vec3f(1.0));
}
fn gammaCorrect(color : vec3f, gamma : f32) -> vec3f {
  let inv = 1.0 / gamma;
  return vec3f(pow(color.x, inv), pow(color.y, inv), pow(color.z, inv));
}
fn shadowDepth(worldPos : vec3f, lightPos : vec3f, range : f32) -> f32 {
  return distance(worldPos, lightPos) / range;
}
fn shadowFactor(shadowMap : texture_2d<f32>, shadowMap_sampler : sampler, lightViewProj : mat4x4f, worldPos : vec3f, normal : vec3f, lightPos : vec3f, range : f32, texel : f32, softness : f32, bias : f32) -> f32 {
  let toLight = normalize(lightPos - worldPos);
  let facing = max(dot(normalize(normal), toLight), 0.0);
  let slope = 1.0 + 2.0 * (1.0 - facing);
  let lookup = worldPos + normalize(normal) * (bias * slope);
  let clip = lightViewProj * vec4f(lookup, 1.0);
  let uv = ((clip).xy / (clip).w * vec2f(0.5, -0.5) + vec2f(0.5));
  let reference = shadowDepth(lookup, lightPos, range) - bias * slope / range;
  var visible = 0.0;
  for (var y = -1.0; y < 2.0; y = y + 1.0) {
    for (var x = -1.0; x < 2.0; x = x + 1.0) {
      let tap = uv + vec2f(x, y) * (texel * softness);
      visible = visible + step(reference, textureSampleLevel(shadowMap, shadowMap_sampler, tap, 0.0).x);
    }
  }
  return visible / 9.0;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let angle = bm_in.iSpin * bm_u.uTime;
  let world = rotate3(bm_in.aPosition * bm_in.iScale, vec3f(0.0, 1.0, 0.0), angle) + bm_in.iOffset;
  bm_out.vNormal = rotate3(bm_in.aNormal / bm_in.iScale, vec3f(0.0, 1.0, 0.0), angle);
  bm_out.vWorld = world;
  bm_out.vColor = bm_in.iColor;
  bm_out.vGround = bm_in.iGround;
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let n = normalize(bm_in.vNormal);
  let toLight = bm_u.uLightPos - bm_in.vWorld;
  let lightDistance = length(toLight);
  let l = toLight * (1.0 / lightDistance);
  let viewDir = normalize(bm_u.uViewPos - bm_in.vWorld);
  let ndl = max(dot(n, l), 0.0);
  let visible = shadowFactor(uShadowMap, uShadowMap_sampler, bm_u.uLightViewProj, bm_in.vWorld, n, bm_u.uLightPos, bm_u.uRange, bm_u.uTexel, bm_u.uSoftness, bm_u.uBias);
  let lit = 1.0 - (1.0 - visible) * bm_u.uShadowStrength;
  let specular = blinnPhongSpec(n, l, viewDir, 48.0) * lit * (1.0 - bm_in.vGround * 0.75);
  let ambient = hemisphereLight(n, bm_u.uSkyColor, bm_u.uGroundColor);
  let falloff = 1.0 / (1.0 + lightDistance * lightDistance * 0.012);
  let checker = ((floor(bm_in.vWorld.x * 0.5) + floor(bm_in.vWorld.z * 0.5)) - (2.0) * floor((floor(bm_in.vWorld.x * 0.5) + floor(bm_in.vWorld.z * 0.5)) / (2.0)));
  let albedo = mix(bm_in.vColor, bm_in.vColor * 0.78, checker * bm_in.vGround);
  let direct = bm_u.uLightColor * (ndl * lit * falloff * 2.4);
  let linear = albedo * (ambient + direct) + bm_u.uLightColor * (specular * 0.9);
  let fade = 1.0 - smoothstep(14.0, 19.0, length(bm_in.vWorld.xz));
  let tonemapped = gammaCorrect(tonemapACES(linear), 2.2);
  return vec4f(mix(bm_u.uFogColor, tonemapped, max(fade, 1.0 - bm_in.vGround)), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iSpin: 'float', iColor: 'vec3', iGround: 'float' },
  uniforms: { uViewProj: 'mat4', uLightViewProj: 'mat4', uShadowMap: 'sampler2D', uLightPos: 'vec3', uViewPos: 'vec3', uLightColor: 'vec3', uSkyColor: 'vec3', uGroundColor: 'vec3', uFogColor: 'vec3', uTime: 'float', uRange: 'float', uTexel: 'float', uSoftness: 'float', uBias: 'float', uShadowStrength: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iSpin","type":"float","location":4,"size":1,"divisor":1},{"name":"iColor","type":"vec3","location":5,"size":3,"divisor":1},{"name":"iGround","type":"float","location":6,"size":1,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uShadowMap","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uLightPos","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uLightColor","type":"vec3","kind":"3fv","size":3,"offset":160},{"name":"uSkyColor","type":"vec3","kind":"3fv","size":3,"offset":176},{"name":"uGroundColor","type":"vec3","kind":"3fv","size":3,"offset":192},{"name":"uFogColor","type":"vec3","kind":"3fv","size":3,"offset":208},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":220},{"name":"uRange","type":"float","kind":"1f","size":1,"offset":224},{"name":"uTexel","type":"float","kind":"1f","size":1,"offset":228},{"name":"uSoftness","type":"float","kind":"1f","size":1,"offset":232},{"name":"uBias","type":"float","kind":"1f","size":1,"offset":236},{"name":"uShadowStrength","type":"float","kind":"1f","size":1,"offset":240}],"uniformBlockSize":256},

};

export default shadowSceneShader;
