/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const shadowDepthShader: CompiledShader<{ aPosition: 'vec3' }, { iOffset: 'vec3'; iScale: 'vec3'; iSpin: 'float' }, { uLightViewProj: 'mat4'; uLightPos: 'vec3'; uTime: 'float'; uRange: 'float' }> = {
  vertexSrc: `#version 300 es
precision highp float;
precision highp int;
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 iOffset;
layout(location = 2) in vec3 iScale;
layout(location = 3) in float iSpin;
uniform mat4 uLightViewProj;
uniform vec3 uLightPos;
uniform float uTime;
uniform float uRange;
out float vDistance;
vec3 rotate3(vec3 p, vec3 axis, float angle) {
  vec3 a = normalize(axis);
  float c = cos(angle);
  float s = sin(angle);
  return p * c + cross(a, p) * s + a * (dot(a, p) * (1.0 - c));
}
float shadowDepth(vec3 worldPos, vec3 lightPos, float range) {
  return distance(worldPos, lightPos) / range;
}
void main() {
  vec3 world = rotate3(aPosition * iScale, vec3(0.0, 1.0, 0.0), iSpin * uTime) + iOffset;
  vDistance = shadowDepth(world, uLightPos, uRange);
  gl_Position = uLightViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
precision highp int;
in float vDistance;
out vec4 fragColor;
void main() {
  fragColor = vec4(vDistance, 0.0, 0.0, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uLightViewProj : mat4x4f,
  uLightPos : vec3f,
  uTime : f32,
  uRange : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) iOffset : vec3f,
  @location(2) iScale : vec3f,
  @location(3) iSpin : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vDistance : f32,
}
fn rotate3(p : vec3f, axis : vec3f, angle : f32) -> vec3f {
  let a = normalize(axis);
  let c = cos(angle);
  let s = sin(angle);
  return p * c + cross(a, p) * s + a * (dot(a, p) * (1.0 - c));
}
fn shadowDepth(worldPos : vec3f, lightPos : vec3f, range : f32) -> f32 {
  return distance(worldPos, lightPos) / range;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = rotate3(bm_in.aPosition * bm_in.iScale, vec3f(0.0, 1.0, 0.0), bm_in.iSpin * bm_u.uTime) + bm_in.iOffset;
  bm_out.vDistance = shadowDepth(world, bm_u.uLightPos, bm_u.uRange);
  bm_out.bm_position = bm_u.uLightViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  return vec4f(bm_in.vDistance, 0.0, 0.0, 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iScale: 'vec3', iSpin: 'float' },
  uniforms: { uLightViewProj: 'mat4', uLightPos: 'vec3', uTime: 'float', uRange: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"iOffset","type":"vec3","location":1,"size":3,"divisor":1},{"name":"iScale","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iSpin","type":"float","location":3,"size":1,"divisor":1}],"uniforms":[{"name":"uLightViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uLightPos","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":76},{"name":"uRange","type":"float","kind":"1f","size":1,"offset":80}],"uniformBlockSize":96},

};

export default shadowDepthShader;
