/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const shadowPreviewShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uMap: 'sampler2D'; uRect: 'vec4' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
uniform vec4 uRect;
out vec2 vUv;
void main() {
  vUv = ((vec4(aPosition.x, aPosition.y, 0.0, 1.0)).xy / (vec4(aPosition.x, aPosition.y, 0.0, 1.0)).w * 0.5 + 0.5);
  gl_Position = vec4(aPosition.x * uRect.z + uRect.x, aPosition.y * uRect.w + uRect.y, 0.0, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform sampler2D uMap;
in vec2 vUv;
out vec4 fragColor;
void main() {
  float nearest = texture(uMap, vUv).x;
  float empty = step(0.999, nearest);
  float shade = pow(1.0 - nearest, 0.55);
  vec3 image = mix(vec3(shade * 0.95, shade * 0.98, shade), vec3(0.07, 0.08, 0.11), empty);
  float edge = step(0.984, max(abs(vUv.x - 0.5), abs(vUv.y - 0.5)) * 2.0);
  fragColor = vec4(mix(image, vec3(0.32, 0.35, 0.44), edge), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uRect : vec4f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uMap : texture_2d<f32>;
@group(0) @binding(2) var uMap_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = ((vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0)).xy / (vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0)).w * vec2f(0.5, -0.5) + vec2f(0.5));
  bm_out.bm_position = vec4f(bm_in.aPosition.x * bm_u.uRect.z + bm_u.uRect.x, bm_in.aPosition.y * bm_u.uRect.w + bm_u.uRect.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let nearest = textureSample(uMap, uMap_sampler, bm_in.vUv).x;
  let empty = step(0.999, nearest);
  let shade = pow(1.0 - nearest, 0.55);
  let image = mix(vec3f(shade * 0.95, shade * 0.98, shade), vec3f(0.07, 0.08, 0.11), empty);
  let edge = step(0.984, max(abs(bm_in.vUv.x - 0.5), abs(bm_in.vUv.y - 0.5)) * 2.0);
  return vec4f(mix(image, vec3f(0.32, 0.35, 0.44), edge), 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uMap: 'sampler2D', uRect: 'vec4' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uMap","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uRect","type":"vec4","kind":"4fv","size":4,"offset":0}],"uniformBlockSize":16},
};

export default shadowPreviewShader;
