/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const Terrain: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uViewProj: 'mat4'; uModel: 'mat4'; uTime: 'float'; uLightDir: 'vec3'; uAmp: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uModel : mat4x4f,
  uTime : f32,
  uLightDir : vec3f,
  uAmp : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vHeight : f32,
}
fn hash22(p : vec2f) -> vec2f {
  let k = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return vec2f(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
fn gnoise2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  let u = vec2f(f.x * f.x * f.x * (f.x * (f.x * 6.0 - 15.0) + 10.0), f.y * f.y * f.y * (f.y * (f.y * 6.0 - 15.0) + 10.0));
  let ga = hash22(cell) * 2.0 - vec2f(1.0, 1.0);
  let gb = hash22(cell + vec2f(1.0, 0.0)) * 2.0 - vec2f(1.0, 1.0);
  let gc = hash22(cell + vec2f(0.0, 1.0)) * 2.0 - vec2f(1.0, 1.0);
  let gd = hash22(cell + vec2f(1.0, 1.0)) * 2.0 - vec2f(1.0, 1.0);
  let va = dot(ga, f);
  let vb = dot(gb, f - vec2f(1.0, 0.0));
  let vc = dot(gc, f - vec2f(0.0, 1.0));
  let vd = dot(gd, f - vec2f(1.0, 1.0));
  return mix(mix(va, vb, u.x), mix(vc, vd, u.x), u.y) * 0.7 + 0.5;
}
fn gfbm2(p : vec2f, octaves : f32) -> f32 {
  var total = 0.0;
  var amplitude = 0.5;
  var frequency = 1.0;
  var norm = 0.0;
  for (var i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * gnoise2(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
fn lambert(normal : vec3f, lightDir : vec3f) -> f32 {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let q = bm_in.aUv * 5.0 + vec2f(bm_u.uTime * 0.22, bm_u.uTime * 0.09);
  let h = gfbm2(q, 4.0);
  let e = 0.04;
  let hx = gfbm2(q + vec2f(e, 0.0), 4.0);
  let hy = gfbm2(q + vec2f(0.0, e), 4.0);
  let normal = normalize(vec3f((h - hx) * bm_u.uAmp * 20.0, (h - hy) * bm_u.uAmp * 20.0, 1.0));
  bm_out.vNormal = (bm_u.uModel * vec4f(normal, 0.0)).xyz;
  bm_out.vHeight = h;
  let displaced = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, (h - 0.5) * bm_u.uAmp, 1.0);
  bm_out.bm_position = bm_u.uViewProj * (bm_u.uModel * displaced);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let diffuse = lambert(bm_in.vNormal, bm_u.uLightDir);
  let low = vec3f(0.1, 0.25, 0.35);
  let high = vec3f(0.85, 0.8, 0.7);
  return vec4f(mix(low, high, bm_in.vHeight) * (0.3 + diffuse * 0.8), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uModel: 'mat4', uTime: 'float', uLightDir: 'vec3', uAmp: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uModel","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":128},{"name":"uLightDir","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uAmp","type":"float","kind":"1f","size":1,"offset":156}],"uniformBlockSize":160},

};

export default Terrain;
