/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const texturedCubeShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uViewProj: 'mat4'; uModel: 'mat4'; uLightPos: 'vec3'; uViewPos: 'vec3'; uTex: 'sampler2D' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uModel : mat4x4f,
  uLightPos : vec3f,
  uViewPos : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uTex : texture_2d<f32>;
@group(0) @binding(2) var uTex_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vUv : vec2f,
  @location(2) vWorldPos : vec3f,
}
fn lambert(normal : vec3f, lightDir : vec3f) -> f32 {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
fn blinnPhongSpec(normal : vec3f, lightDir : vec3f, viewDir : vec3f, shininess : f32) -> f32 {
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = bm_u.uModel * vec4f(bm_in.aPosition, 1.0);
  bm_out.vWorldPos = world.xyz;
  bm_out.vNormal = (bm_u.uModel * vec4f(bm_in.aNormal, 0.0)).xyz;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = bm_u.uViewProj * world;
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let ambient = 0.25;
  let lightDir = bm_u.uLightPos - bm_in.vWorldPos;
  let viewDir = bm_u.uViewPos - bm_in.vWorldPos;
  let diffuse = lambert(bm_in.vNormal, lightDir);
  let specular = blinnPhongSpec(bm_in.vNormal, lightDir, viewDir, 32.0) * 0.4;
  let base = textureSample(uTex, uTex_sampler, bm_in.vUv).xyz;
  let lit = base * (ambient + diffuse) + vec3f(1.0, 1.0, 1.0) * specular;
  return vec4f(lit, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uModel: 'mat4', uLightPos: 'vec3', uViewPos: 'vec3', uTex: 'sampler2D' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":2,"size":2,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uModel","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uLightPos","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uTex","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2}],"uniformBlockSize":160},

};

export default texturedCubeShader;
