/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const WaterproProbeVelocity: CompiledShader<Record<string, never>, Record<string, never>, { uDeltaTime: 'float'; uCount: 'float'; uVelocity: 'storage'; uPosition: 'storage'; uPrevious: 'storage' }> = {
  wgslSrc: `struct BmUniforms {
  uDeltaTime : f32,
  uCount : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var<storage, read_write> uVelocity : array<vec4f>;
@group(0) @binding(2) var<storage, read> uPosition : array<vec4f>;
@group(0) @binding(3) var<storage, read_write> uPrevious : array<vec4f>;
@compute @workgroup_size(64, 1, 1)
fn cs_main(@builtin(global_invocation_id) bm_gid : vec3u) {
  let id = vec3f(bm_gid);
  let index = min(floor(id.x), max(bm_u.uCount - 1.0, 0.0));
  let step = max(bm_u.uDeltaTime, 0.001);
  let current = uPosition[u32(index)];
  let previous = uPrevious[u32(index)];
  uVelocity[u32(index)] = vec4f((current.x - previous.x) / step, (current.y - previous.y) / step, (current.z - previous.z) / step, 0.0);
  uPrevious[u32(index)] = current;
}
`,
  attributes: {},
  instanceAttributes: {},
  uniforms: { uDeltaTime: 'float', uCount: 'float', uVelocity: 'storage', uPosition: 'storage', uPrevious: 'storage' },
  layout: {"attributes":[],"uniforms":[{"name":"uDeltaTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uCount","type":"float","kind":"1f","size":1,"offset":4},{"name":"uVelocity","type":"storage","kind":"1i","size":1,"unit":0,"textureBinding":1},{"name":"uPosition","type":"storage","kind":"1i","size":1,"unit":1,"textureBinding":2},{"name":"uPrevious","type":"storage","kind":"1i","size":1,"unit":2,"textureBinding":3}],"uniformBlockSize":16},
  storageWritten: ["uVelocity","uPrevious"],
  hasCompute: true,

};

export default WaterproProbeVelocity;
