/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const WaterSurface: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uModel: 'mat4'; uSky: 'sampler2D'; uChoppy: 'float'; uOrigin: 'vec2'; uViewPos: 'vec3'; uSunDir: 'vec3'; uSkyHorizon: 'vec3'; uTime: 'float'; uSeabedY: 'float'; uSandColor: 'vec3'; uExtinction: 'vec3'; uCausticStrength: 'float'; uShallow: 'vec3'; uFoamColor: 'vec3'; uNormalStrength: 'float'; uFoamAmount: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uModel : mat4x4f,
  uChoppy : f32,
  uOrigin : vec2f,
  uViewPos : vec3f,
  uSunDir : vec3f,
  uSkyHorizon : vec3f,
  uTime : f32,
  uSeabedY : f32,
  uSandColor : vec3f,
  uExtinction : vec3f,
  uCausticStrength : f32,
  uShallow : vec3f,
  uFoamColor : vec3f,
  uNormalStrength : f32,
  uFoamAmount : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uSky : texture_2d<f32>;
@group(0) @binding(2) var uSky_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorldPos : vec3f,
  @location(1) vNormal : vec3f,
  @location(2) vHeight : f32,
}
fn fresnel(normal : vec3f, viewDir : vec3f, power : f32) -> f32 {
  let base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
fn blinnPhongSpec(normal : vec3f, lightDir : vec3f, viewDir : vec3f, shininess : f32) -> f32 {
  let halfway = normalize(normalize(lightDir) + normalize(viewDir));
  return pow(max(dot(normalize(normal), halfway), 0.0), shininess);
}
fn gerstnerWave(p : vec2f, dir : vec2f, steepness : f32, wavelength : f32, time : f32) -> vec3f {
  let k = 6.28318 / wavelength;
  let c = sqrt(9.8 / k);
  let d = normalize(dir);
  let f = k * (dot(d, p) - c * time);
  let a = steepness / k;
  return vec3f(d.x * a * cos(f), d.y * a * cos(f), a * sin(f));
}
fn hash21(p : vec2f) -> f32 {
  return fract(sin(dot(p, vec2f(127.1, 311.7))) * 43758.5453);
}
fn vnoise2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  let u = vec2f(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y));
  let a = hash21(cell);
  let b = hash21(cell + vec2f(1.0, 0.0));
  let c = hash21(cell + vec2f(0.0, 1.0));
  let d = hash21(cell + vec2f(1.0, 1.0));
  return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}
fn fbm2(p : vec2f, octaves : f32) -> f32 {
  var total = 0.0;
  var amplitude = 0.5;
  var frequency = 1.0;
  var norm = 0.0;
  for (var i = 0.0; i < octaves; i = i + 1.0) {
    total = total + amplitude * vnoise2(p * frequency);
    norm = norm + amplitude;
    amplitude = amplitude * 0.5;
    frequency = frequency * 2.0;
  }
  return total / norm;
}
fn hash22(p : vec2f) -> vec2f {
  let k = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return vec2f(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
fn worleyEdge2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  var f1 = 8.0;
  var f2 = 8.0;
  for (var i = -1.0; i <= 1.0; i = i + 1.0) {
    for (var j = -1.0; j <= 1.0; j = j + 1.0) {
      let neighbor = vec2f(i, j);
      let feature = hash22(cell + neighbor);
      let d = length(neighbor + feature - f);
      if (d < f1) {
        f2 = f1;
        f1 = d;
      } else {
        if (d < f2) {
          f2 = d;
        }
      }
    }
  }
  return f2 - f1;
}
fn waveOffset(p : vec2f, time : f32, choppy : f32) -> vec3f {
  let w1 = gerstnerWave(p, vec2f(1.0, 0.18), 0.2 * choppy, 71.0, time);
  let w2 = gerstnerWave(p, vec2f(0.62, -0.78), 0.16 * choppy, 47.0, time);
  let w3 = gerstnerWave(p, vec2f(-0.35, 0.94), 0.13 * choppy, 31.0, time);
  let w4 = gerstnerWave(p, vec2f(0.88, 0.47), 0.1 * choppy, 23.0, time);
  let w5 = gerstnerWave(p, vec2f(-0.72, -0.69), 0.085 * choppy, 17.0, time);
  let w6 = gerstnerWave(p, vec2f(0.15, -0.99), 0.07 * choppy, 12.5, time);
  let w7 = gerstnerWave(p, vec2f(-0.95, 0.31), 0.055 * choppy, 8.3, time);
  let w8 = gerstnerWave(p, vec2f(0.44, 0.9), 0.04 * choppy, 5.7, time);
  let sum = w1 + w2 + w3 + w4 + w5 + w6 + w7 + w8;
  let local = 0.55 + fbm2(p * 0.004 + vec2f(time * 0.006, 0.0), 2.0) * 0.95;
  return sum * local;
}
fn refractRay(incident : vec3f, normal : vec3f, eta : f32) -> vec3f {
  let cosi = dot(normal, incident);
  let k = 1.0 - eta * eta * (1.0 - cosi * cosi);
  return incident * eta - normal * (eta * cosi + sqrt(max(k, 0.0)));
}
fn caustics(p : vec2f, time : f32) -> f32 {
  let a = 1.0 - worleyEdge2(p * 0.28 + vec2f(time * 0.06, time * 0.04));
  let b = 1.0 - worleyEdge2(p * 0.41 - vec2f(time * 0.05, time * 0.075));
  return pow(max(a, 0.0), 7.0) + pow(max(b, 0.0), 7.0) * 0.7;
}
fn skyTap(map : texture_2d<f32>, map_sampler : sampler, cx : f32, cy : f32) -> vec3f {
  let w = 512.0;
  let h = 256.0;
  let u = (((cx) - (w) * floor((cx) / (w))) + 0.5) / w;
  let raw = (clamp(cy, 0.0, h - 1.0) + 0.5) / h;
  return textureSampleLevel(map, map_sampler, vec2f(u, 1.0 - raw), 0.0).xyz;
}
fn equirectSky(map : texture_2d<f32>, map_sampler : sampler, direction : vec3f) -> vec3f {
  let w = 512.0;
  let h = 256.0;
  let twoPi = 6.283185307179586;
  let pi = 3.141592653589793;
  let gx = (atan2(direction.x, direction.z) / twoPi + 0.5) * w - 0.5;
  let gy = (asin(clamp(direction.y, -1.0, 1.0)) / pi + 0.5) * h - 0.5;
  let bx = floor(gx);
  let by = floor(gy);
  let fx = gx - bx;
  let fy = gy - by;
  let s00 = skyTap(map, map_sampler, bx, by);
  let s10 = skyTap(map, map_sampler, bx + 1.0, by);
  let s01 = skyTap(map, map_sampler, bx, by + 1.0);
  let s11 = skyTap(map, map_sampler, bx + 1.0, by + 1.0);
  return mix(mix(s00, s10, fx), mix(s01, s11, fx), fy);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let p = vec2f(bm_in.aPosition.x + bm_u.uOrigin.x, bm_in.aPosition.z + bm_u.uOrigin.y);
  let offset = waveOffset(p, bm_u.uTime, bm_u.uChoppy);
  let step = 0.35;
  let alongX = vec2f(p.x + step, p.y);
  let alongZ = vec2f(p.x, p.y + step);
  let offsetX = waveOffset(alongX, bm_u.uTime, bm_u.uChoppy);
  let offsetZ = waveOffset(alongZ, bm_u.uTime, bm_u.uChoppy);
  let base = vec3f(p.x + offset.x, offset.z, p.y + offset.y);
  let pointX = vec3f(alongX.x + offsetX.x, offsetX.z, alongX.y + offsetX.y);
  let pointZ = vec3f(alongZ.x + offsetZ.x, offsetZ.z, alongZ.y + offsetZ.y);
  let normal = normalize(cross(pointZ - base, pointX - base));
  let displaced = vec3f(bm_in.aPosition.x + offset.x, offset.z, bm_in.aPosition.z + offset.y);
  let world = bm_u.uModel * vec4f(displaced, 1.0);
  bm_out.vWorldPos = world.xyz;
  bm_out.vNormal = (bm_u.uModel * vec4f(normal, 0.0)).xyz;
  bm_out.vHeight = offset.z;
  bm_out.bm_position = bm_u.uViewProj * world;
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let ripple = vec2f(bm_in.vWorldPos.x, bm_in.vWorldPos.z) * 0.35 + vec2f(bm_u.uTime * 0.35, bm_u.uTime * 0.2);
  let rippleStep = 0.5;
  let h0 = fbm2(ripple, 3.0);
  let hx = fbm2(ripple + vec2f(rippleStep, 0.0), 3.0);
  let hz = fbm2(ripple + vec2f(0.0, rippleStep), 3.0);
  let detail = vec3f((h0 - hx) * bm_u.uNormalStrength, 0.0, (h0 - hz) * bm_u.uNormalStrength);
  let normal = normalize(normalize(bm_in.vNormal) + detail);
  let viewDir = normalize(bm_u.uViewPos - bm_in.vWorldPos);
  let sun = normalize(bm_u.uSunDir);
  let facing = max(dot(normal, viewDir), 0.0);
  let rim = mix(0.02, 0.86, fresnel(normal, viewDir, 5.0));
  let reflectDir = reflect(vec3f(0.0 - viewDir.x, 0.0 - viewDir.y, 0.0 - viewDir.z), normal);
  let bounced = vec3f(reflectDir.x, max(reflectDir.y, 0.02), reflectDir.z);
  let reflection = equirectSky(uSky, uSky_sampler, normalize(bounced));
  let intoWater = refractRay(vec3f(0.0 - viewDir.x, 0.0 - viewDir.y, 0.0 - viewDir.z), normal, 0.75);
  let descent = max(0.0 - intoWater.y, 0.02);
  let relief = fbm2(vec2f(bm_in.vWorldPos.x, bm_in.vWorldPos.z) * 0.012, 3.0);
  let bedY = bm_u.uSeabedY - relief * 7.0;
  let pathLength = min((bm_in.vWorldPos.y - bedY) / descent, 260.0);
  let floorPos = bm_in.vWorldPos + intoWater * pathLength;
  let grain = fbm2(vec2f(floorPos.x, floorPos.z) * 0.09, 3.0);
  let lit = 1.0 + caustics(vec2f(floorPos.x, floorPos.z), bm_u.uTime) * bm_u.uCausticStrength;
  let seabed = bm_u.uSandColor * ((0.72 + grain * 0.55) * lit);
  let travel = pathLength * 1.6;
  let transmit = vec3f(exp(0.0 - bm_u.uExtinction.x * travel), exp(0.0 - bm_u.uExtinction.y * travel), exp(0.0 - bm_u.uExtinction.z * travel));
  let body = vec3f(seabed.x * transmit.x + bm_u.uShallow.x * (1.0 - transmit.x), seabed.y * transmit.y + bm_u.uShallow.y * (1.0 - transmit.y), seabed.z * transmit.z + bm_u.uShallow.z * (1.0 - transmit.z));
  let lift = clamp(bm_in.vHeight * 0.35 + 0.3, 0.0, 1.0);
  let backlight = pow(max(dot(viewDir, vec3f(0.0 - sun.x, 0.0 - sun.y, 0.0 - sun.z)), 0.0), 4.0);
  let scatter = vec3f(0.05, 0.35, 0.3) * (backlight * lift * 1.6);
  var color = mix(body + scatter, reflection, rim);
  let glint = blinnPhongSpec(normal, sun, viewDir, 900.0);
  let sheen = blinnPhongSpec(normal, sun, viewDir, 24.0);
  let sunlight = vec3f(1.0, 0.96, 0.88);
  color = color + sunlight * (glint * 2.4) + sunlight * (sheen * 0.1);
  let steep = clamp((1.0 - normal.y) * 4.5, 0.0, 1.0);
  let raised = clamp((bm_in.vHeight - 0.5) * 0.8, 0.0, 1.0);
  let patchy = fbm2(vec2f(bm_in.vWorldPos.x, bm_in.vWorldPos.z) * 0.2 + vec2f(bm_u.uTime * 0.12, 0.0), 3.0);
  let foam = clamp(steep * raised * (0.25 + patchy * 1.3) * bm_u.uFoamAmount * 4.0, 0.0, 1.0);
  let foamMask = smoothstep(0.3, 0.85, foam);
  color = mix(color, bm_u.uFoamColor, foamMask);
  let distance = length(bm_u.uViewPos - bm_in.vWorldPos);
  let haze = 1.0 - exp(0.0 - distance * 0.0009);
  color = mix(color, bm_u.uSkyHorizon, clamp(haze, 0.0, 1.0));
  return vec4f(color, 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uModel: 'mat4', uSky: 'sampler2D', uChoppy: 'float', uOrigin: 'vec2', uViewPos: 'vec3', uSunDir: 'vec3', uSkyHorizon: 'vec3', uTime: 'float', uSeabedY: 'float', uSandColor: 'vec3', uExtinction: 'vec3', uCausticStrength: 'float', uShallow: 'vec3', uFoamColor: 'vec3', uNormalStrength: 'float', uFoamAmount: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uModel","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uSky","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uChoppy","type":"float","kind":"1f","size":1,"offset":128},{"name":"uOrigin","type":"vec2","kind":"2fv","size":2,"offset":136},{"name":"uViewPos","type":"vec3","kind":"3fv","size":3,"offset":144},{"name":"uSunDir","type":"vec3","kind":"3fv","size":3,"offset":160},{"name":"uSkyHorizon","type":"vec3","kind":"3fv","size":3,"offset":176},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":188},{"name":"uSeabedY","type":"float","kind":"1f","size":1,"offset":192},{"name":"uSandColor","type":"vec3","kind":"3fv","size":3,"offset":208},{"name":"uExtinction","type":"vec3","kind":"3fv","size":3,"offset":224},{"name":"uCausticStrength","type":"float","kind":"1f","size":1,"offset":236},{"name":"uShallow","type":"vec3","kind":"3fv","size":3,"offset":240},{"name":"uFoamColor","type":"vec3","kind":"3fv","size":3,"offset":256},{"name":"uNormalStrength","type":"float","kind":"1f","size":1,"offset":268},{"name":"uFoamAmount","type":"float","kind":"1f","size":1,"offset":272}],"uniformBlockSize":288},

};

export default WaterSurface;
