/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const waterEvolveShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uSpectrum: 'sampler2D'; uPatchSize: 'float'; uTime: 'float' }> = {
  vertexSrc: `#version 300 es
precision highp float;
precision highp int;
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition.x, aPosition.y, 0.0, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp sampler3D;
uniform sampler2D uSpectrum;
uniform float uPatchSize;
uniform float uTime;
in vec2 vUv;
out vec4 fragColor;
vec2 complexMul(vec2 a, vec2 b) {
  return vec2(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x);
}
void main() {
  float size = 128.0;
  float twoPi = 6.283185307179586;
  float gravity = 9.81;
  float x = floor(vUv.x * size);
  float y = floor(vUv.y * size);
  float n = x - size * 0.5;
  float m = y - size * 0.5;
  float delta = twoPi / uPatchSize;
  vec2 k = vec2(n * delta, m * delta);
  float kLength = length(k);
  float alive = step(0.0001, kLength);
  float safeLength = max(kLength, 0.0001);
  vec4 seed = texture(uSpectrum, vUv);
  vec2 positive = vec2(seed.x, seed.y);
  vec2 negative = vec2(seed.z, 0.0 - seed.w);
  float omega = sqrt(gravity * safeLength) * uTime;
  vec2 phase = vec2(cos(omega), sin(omega));
  vec2 conjugatePhase = vec2(phase.x, 0.0 - phase.y);
  vec2 height = complexMul(positive, phase) + complexMul(negative, conjugatePhase);
  vec2 unit = vec2(k.x / safeLength * alive, k.y / safeLength * alive);
  vec2 displaceX = vec2(height.y * unit.x, 0.0 - height.x * unit.x);
  vec2 displaceZ = vec2(height.y * unit.y, 0.0 - height.x * unit.y);
  fragColor = vec4(displaceX.x - height.y, displaceX.y + height.x, displaceZ.x, displaceZ.y);
}
`,
  wgslSrc: `struct BmUniforms {
  uPatchSize : f32,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uSpectrum : texture_2d<f32>;
@group(0) @binding(2) var uSpectrum_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn complexMul(a : vec2f, b : vec2f) -> vec2f {
  return vec2f(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let size = 128.0;
  let twoPi = 6.283185307179586;
  let gravity = 9.81;
  let x = floor(bm_in.vUv.x * size);
  let y = floor(bm_in.vUv.y * size);
  let n = x - size * 0.5;
  let m = y - size * 0.5;
  let delta = twoPi / bm_u.uPatchSize;
  let k = vec2f(n * delta, m * delta);
  let kLength = length(k);
  let alive = step(0.0001, kLength);
  let safeLength = max(kLength, 0.0001);
  let seed = textureSample(uSpectrum, uSpectrum_sampler, bm_in.vUv);
  let positive = vec2f(seed.x, seed.y);
  let negative = vec2f(seed.z, 0.0 - seed.w);
  let omega = sqrt(gravity * safeLength) * bm_u.uTime;
  let phase = vec2f(cos(omega), sin(omega));
  let conjugatePhase = vec2f(phase.x, 0.0 - phase.y);
  let height = complexMul(positive, phase) + complexMul(negative, conjugatePhase);
  let unit = vec2f(k.x / safeLength * alive, k.y / safeLength * alive);
  let displaceX = vec2f(height.y * unit.x, 0.0 - height.x * unit.x);
  let displaceZ = vec2f(height.y * unit.y, 0.0 - height.x * unit.y);
  return vec4f(displaceX.x - height.y, displaceX.y + height.x, displaceZ.x, displaceZ.y);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uSpectrum: 'sampler2D', uPatchSize: 'float', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uSpectrum","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uPatchSize","type":"float","kind":"1f","size":1,"offset":0},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},

};

export default waterEvolveShader;
