/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const waterSkyShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uZenith: 'vec3'; uHorizon: 'vec3' }> = {
  vertexSrc: `#version 300 es
precision highp float;
precision highp int;
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition.x, aPosition.y, 0.0, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
precision highp int;
uniform vec3 uZenith;
uniform vec3 uHorizon;
in vec2 vUv;
out vec4 fragColor;
void main() {
  float up = clamp((vUv.y - 0.5) * 2.0, 0.0, 1.0);
  fragColor = vec4(mix(uHorizon, uZenith, up), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uZenith : vec3f,
  uHorizon : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let up = clamp((bm_in.vUv.y - 0.5) * 2.0, 0.0, 1.0);
  return vec4f(mix(bm_u.uHorizon, bm_u.uZenith, up), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uZenith: 'vec3', uHorizon: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uZenith","type":"vec3","kind":"3fv","size":3,"offset":0},{"name":"uHorizon","type":"vec3","kind":"3fv","size":3,"offset":16}],"uniformBlockSize":32},

};

export default waterSkyShader;
