/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const WaterButterfly: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, Record<string, never>> = {
  wgslSrc: `struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn bitReverse(index : f32) -> f32 {
  let stages = 7.0;
  var value = index;
  var reversed = 0.0;
  for (var i = 0.0; i < stages; i = i + 1.0) {
    reversed = reversed * 2.0 + ((value) - (2.0) * floor((value) / (2.0)));
    value = floor(value / 2.0);
  }
  return reversed;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let size = 128.0;
  let stages = 7.0;
  let twoPi = 6.283185307179586;
  let linear = floor(bm_in.vUv.x * (stages * size));
  let stage = floor(linear / size);
  let index = ((linear) - (size) * floor((linear) / (size)));
  let span = pow(2.0, stage);
  let wing = step(((index) - (span * 2.0) * floor((index) / (span * 2.0))), span - 0.5);
  let k = ((index * (size / (span * 2.0))) - (size) * floor((index * (size / (span * 2.0))) / (size)));
  let angle = twoPi * k / size;
  let top = mix(index - span, index, wing);
  let bottom = mix(index, index + span, wing);
  let isFirst = step(stage, 0.5);
  return vec4f(cos(angle), sin(angle), mix(top, bitReverse(top), isFirst), mix(bottom, bitReverse(bottom), isFirst));
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: {},
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[],"uniformBlockSize":0},

};

export default WaterButterfly;
