/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const waterFftShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uButterfly: 'sampler2D'; uSource: 'sampler2D'; uStage: 'float'; uVertical: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uStage : f32,
  uVertical : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uButterfly : texture_2d<f32>;
@group(0) @binding(2) var uButterfly_sampler : sampler;
@group(0) @binding(3) var uSource : texture_2d<f32>;
@group(0) @binding(4) var uSource_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn complexMul(a : vec2f, b : vec2f) -> vec2f {
  return vec2f(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let size = 128.0;
  let stages = 7.0;
  let x = floor(bm_in.vUv.x * size);
  let y = floor(bm_in.vUv.y * size);
  let along = mix(x, y, bm_u.uVertical);
  let entry = textureSample(uButterfly, uButterfly_sampler, vec2f((bm_u.uStage * size + along + 0.5) / (stages * size), 0.5));
  let twiddle = vec2f(entry.x, entry.y);
  let topIndex = entry.z;
  let bottomIndex = entry.w;
  let topUv = vec2f((mix(topIndex, x, bm_u.uVertical) + 0.5) / size, (mix(y, topIndex, bm_u.uVertical) + 0.5) / size);
  let bottomUv = vec2f((mix(bottomIndex, x, bm_u.uVertical) + 0.5) / size, (mix(y, bottomIndex, bm_u.uVertical) + 0.5) / size);
  let top = textureSample(uSource, uSource_sampler, topUv);
  let bottom = textureSample(uSource, uSource_sampler, bottomUv);
  let first = vec2f(top.x, top.y) + complexMul(twiddle, vec2f(bottom.x, bottom.y));
  let second = vec2f(top.z, top.w) + complexMul(twiddle, vec2f(bottom.z, bottom.w));
  return vec4f(first.x, first.y, second.x, second.y);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uButterfly: 'sampler2D', uSource: 'sampler2D', uStage: 'float', uVertical: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uButterfly","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uSource","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uStage","type":"float","kind":"1f","size":1,"offset":0},{"name":"uVertical","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},

};

export default waterFftShader;
