/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const waterSkydomeShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uModel: 'mat4'; uZenith: 'vec3'; uHorizon: 'vec3' }> = {
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uModel : mat4x4f,
  uZenith : vec3f,
  uHorizon : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vDir : vec3f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vDir = normalize(bm_in.aPosition);
  bm_out.bm_position = bm_u.uViewProj * (bm_u.uModel * vec4f(bm_in.aPosition, 1.0));
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let direction = normalize(bm_in.vDir);
  return vec4f(bm_u.uHorizon + (bm_u.uZenith - bm_u.uHorizon) * clamp(direction.y, 0.0, 1.0), 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uModel: 'mat4', uZenith: 'vec3', uHorizon: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uModel","type":"mat4","kind":"m4fv","size":16,"offset":64},{"name":"uZenith","type":"vec3","kind":"3fv","size":3,"offset":128},{"name":"uHorizon","type":"vec3","kind":"3fv","size":3,"offset":144}],"uniformBlockSize":160},

};

export default waterSkydomeShader;
