/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const waterSpectrumShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uPatchSize: 'float'; uWindDir: 'vec2'; uWindSpeed: 'float'; uPeakWavelength: 'float'; uAmplitude: 'float'; uSpread: 'float'; uBand: 'vec2'; uSeed: 'float' }> = {
  wgslSrc: `struct BmUniforms {
  uPatchSize : f32,
  uWindDir : vec2f,
  uWindSpeed : f32,
  uPeakWavelength : f32,
  uAmplitude : f32,
  uSpread : f32,
  uBand : vec2f,
  uSeed : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn hash22(p : vec2f) -> vec2f {
  let k = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return vec2f(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
fn gaussian(seed : vec2f) -> vec2f {
  let twoPi = 6.283185307179586;
  let u = hash22(seed);
  let radius = sqrt(0.0 - 2.0 * log(max(u.x, 0.000001)));
  let angle = twoPi * u.y;
  return vec2f(radius * cos(angle), radius * sin(angle));
}
fn jonswap(omega : f32, peak : f32) -> f32 {
  let gravity = 9.81;
  let gamma = 3.3;
  let sigma = mix(0.07, 0.09, step(peak, omega));
  let relative = (omega - peak) / (sigma * peak);
  let enhancement = pow(gamma, exp(-0.5 * relative * relative));
  let shape = exp(-1.25 * pow(peak / omega, 4.0));
  return 0.0081 * gravity * gravity * shape * enhancement / pow(omega, 5.0);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let size = 128.0;
  let twoPi = 6.283185307179586;
  let gravity = 9.81;
  let x = floor(bm_in.vUv.x * size);
  let y = floor(bm_in.vUv.y * size);
  let n = x - size * 0.5;
  let m = y - size * 0.5;
  let delta = twoPi / bm_u.uPatchSize;
  let k = vec2f(n * delta, m * delta);
  let kLength = length(k);
  let alive = step(0.0001, kLength);
  let safeLength = max(kLength, 0.0001);
  let direction = normalize(vec2f(k.x + 0.000001, k.y));
  let omega = sqrt(gravity * safeLength);
  let peak = sqrt(gravity * twoPi / max(bm_u.uPeakWavelength, 0.5));
  let energy = jonswap(max(omega, 0.001), peak);
  let dOmegaDk = gravity / (2.0 * omega);
  let alignment = dot(direction, normalize(bm_u.uWindDir));
  let forward = pow(max(alignment, 0.0), bm_u.uSpread);
  let backward = 0.25 * pow(max(0.0 - alignment, 0.0), bm_u.uSpread);
  let spread = forward + backward;
  let smallest = 0.002 * bm_u.uWindSpeed * bm_u.uWindSpeed;
  let cutoff = exp(-safeLength * safeLength * smallest * smallest);
  let band = step(bm_u.uBand.x, kLength) * step(kLength, bm_u.uBand.y);
  let windScale = pow(max(bm_u.uWindSpeed, 0.1) / 10.0, 2.0);
  let variance = 2.0 * energy * spread * dOmegaDk * delta * delta * windScale * bm_u.uAmplitude * cutoff / safeLength;
  let scale = sqrt(max(variance, 0.0)) * 0.7071067811865476 * alive * band;
  let positive = gaussian(vec2f(x + bm_u.uSeed, y + bm_u.uSeed * 1.7));
  let negative = gaussian(vec2f(size - x + bm_u.uSeed * 3.1, size - y + bm_u.uSeed * 2.3));
  return vec4f(positive.x * scale, positive.y * scale, negative.x * scale, negative.y * scale);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uPatchSize: 'float', uWindDir: 'vec2', uWindSpeed: 'float', uPeakWavelength: 'float', uAmplitude: 'float', uSpread: 'float', uBand: 'vec2', uSeed: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uPatchSize","type":"float","kind":"1f","size":1,"offset":0},{"name":"uWindDir","type":"vec2","kind":"2fv","size":2,"offset":8},{"name":"uWindSpeed","type":"float","kind":"1f","size":1,"offset":16},{"name":"uPeakWavelength","type":"float","kind":"1f","size":1,"offset":20},{"name":"uAmplitude","type":"float","kind":"1f","size":1,"offset":24},{"name":"uSpread","type":"float","kind":"1f","size":1,"offset":28},{"name":"uBand","type":"vec2","kind":"2fv","size":2,"offset":32},{"name":"uSeed","type":"float","kind":"1f","size":1,"offset":40}],"uniformBlockSize":48},

};

export default waterSpectrumShader;
