import type { GpuRecord } from '../dsl/types.js';
import type { CompiledShaderModule } from './compile.js';

export function buildGeneratedModule(shaderName: string, compiled: CompiledShaderModule): string {
  const attributeType = recordTypeLiteral(compiled.attributes);
  const instanceAttributeType = recordTypeLiteral(compiled.instanceAttributes);
  const uniformType = recordTypeLiteral(compiled.uniforms);
  return `/* Generated by BroMetal. Do not edit — recompile with \`npx brometal dev\`. */
import type { CompiledShader } from 'brometal';

const ${shaderName}: CompiledShader<${attributeType}, ${instanceAttributeType}, ${uniformType}> = {
  vertexSrc: \`${escapeTemplate(compiled.vertexSrc)}\`,
  fragmentSrc: \`${escapeTemplate(compiled.fragmentSrc)}\`,
  attributes: ${recordValueLiteral(compiled.attributes)},
  instanceAttributes: ${recordValueLiteral(compiled.instanceAttributes)},
  uniforms: ${recordValueLiteral(compiled.uniforms)},
};

export default ${shaderName};
`;
}

export function shaderNameFromFile(fileName: string): string {
  const base = fileName.replace(/\.shader\.ts$/, '').replace(/^.*[/\\]/, '');
  const camel = base
    .split(/[^A-Za-z0-9]+/)
    .filter((part) => part.length > 0)
    .map((part, index) => (index === 0 ? part : part[0]!.toUpperCase() + part.slice(1)))
    .join('');
  const safe = /^[A-Za-z_]/.test(camel) ? camel : `_${camel}`;
  return `${safe}Shader`;
}

function recordTypeLiteral(record: GpuRecord): string {
  const entries = Object.entries(record).map(([name, type]) => `${name}: '${type}'`);
  return entries.length === 0 ? 'Record<string, never>' : `{ ${entries.join('; ')} }`;
}

function recordValueLiteral(record: GpuRecord): string {
  const entries = Object.entries(record).map(([name, type]) => `${name}: '${type}'`);
  return entries.length === 0 ? '{}' : `{ ${entries.join(', ')} }`;
}

function escapeTemplate(source: string): string {
  return source.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}
