/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const fnBlendOverlayShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
in vec2 vUv;
out vec4 fragColor;
float blendOverlayChannel(float base, float blend) {
  float result = 2.0 * base * blend;
  if (base >= 0.5) {
    result = 1.0 - 2.0 * (1.0 - base) * (1.0 - blend);
  }
  return result;
}
vec3 blendOverlay(vec3 base, vec3 blend) {
  return vec3(blendOverlayChannel(base.x, blend.x), blendOverlayChannel(base.y, blend.y), blendOverlayChannel(base.z, blend.z));
}
vec3 hsv2rgb(vec3 hsv) {
  float h = hsv.x * 6.0;
  float r = clamp(abs(h - 3.0) - 1.0, 0.0, 1.0);
  float g = clamp(2.0 - abs(h - 2.0), 0.0, 1.0);
  float b = clamp(2.0 - abs(h - 4.0), 0.0, 1.0);
  return mix(vec3(1.0, 1.0, 1.0), vec3(r, g, b), hsv.y) * hsv.z;
}
void main() {
  vec3 base = hsv2rgb(vec3(vUv.x, 0.7, 0.8));
  fragColor = vec4(blendOverlay(base, vec3(vUv.y, vUv.y, vUv.y)), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn blendOverlayChannel(base : f32, blend : f32) -> f32 {
  var result = 2.0 * base * blend;
  if (base >= 0.5) {
    result = 1.0 - 2.0 * (1.0 - base) * (1.0 - blend);
  }
  return result;
}
fn blendOverlay(base : vec3f, blend : vec3f) -> vec3f {
  return vec3f(blendOverlayChannel(base.x, blend.x), blendOverlayChannel(base.y, blend.y), blendOverlayChannel(base.z, blend.z));
}
fn hsv2rgb(hsv : vec3f) -> vec3f {
  let h = hsv.x * 6.0;
  let r = clamp(abs(h - 3.0) - 1.0, 0.0, 1.0);
  let g = clamp(2.0 - abs(h - 2.0), 0.0, 1.0);
  let b = clamp(2.0 - abs(h - 4.0), 0.0, 1.0);
  return mix(vec3f(1.0, 1.0, 1.0), vec3f(r, g, b), hsv.y) * hsv.z;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let base = hsv2rgb(vec3f(bm_in.vUv.x, 0.7, 0.8));
  return vec4f(blendOverlay(base, vec3f(bm_in.vUv.y, bm_in.vUv.y, bm_in.vUv.y)), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default fnBlendOverlayShader;
