/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const fnBlendOverlayChannelShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
in vec2 vUv;
out vec4 fragColor;
float blendOverlayChannel(float base, float blend) {
  float result = 2.0 * base * blend;
  if (base >= 0.5) {
    result = 1.0 - 2.0 * (1.0 - base) * (1.0 - blend);
  }
  return result;
}
void main() {
  float v = blendOverlayChannel(vUv.x, vUv.y);
  fragColor = vec4(v, v, v, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn blendOverlayChannel(base : f32, blend : f32) -> f32 {
  var result = 2.0 * base * blend;
  if (base >= 0.5) {
    result = 1.0 - 2.0 * (1.0 - base) * (1.0 - blend);
  }
  return result;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let v = blendOverlayChannel(bm_in.vUv.x, bm_in.vUv.y);
  return vec4f(v, v, v, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default fnBlendOverlayChannelShader;
