/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const fnCurl2Shader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform float uAspect;
in vec2 vUv;
out vec4 fragColor;
vec2 hash22(vec2 p) {
  vec2 k = vec2(dot(p, vec2(127.1, 311.7)), dot(p, vec2(269.5, 183.3)));
  return vec2(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
float gnoise2(vec2 p) {
  vec2 cell = vec2(floor(p.x), floor(p.y));
  vec2 f = p - cell;
  vec2 u = vec2(f.x * f.x * f.x * (f.x * (f.x * 6.0 - 15.0) + 10.0), f.y * f.y * f.y * (f.y * (f.y * 6.0 - 15.0) + 10.0));
  vec2 ga = hash22(cell) * 2.0 - vec2(1.0, 1.0);
  vec2 gb = hash22(cell + vec2(1.0, 0.0)) * 2.0 - vec2(1.0, 1.0);
  vec2 gc = hash22(cell + vec2(0.0, 1.0)) * 2.0 - vec2(1.0, 1.0);
  vec2 gd = hash22(cell + vec2(1.0, 1.0)) * 2.0 - vec2(1.0, 1.0);
  float va = dot(ga, f);
  float vb = dot(gb, f - vec2(1.0, 0.0));
  float vc = dot(gc, f - vec2(0.0, 1.0));
  float vd = dot(gd, f - vec2(1.0, 1.0));
  return mix(mix(va, vb, u.x), mix(vc, vd, u.x), u.y) * 0.7 + 0.5;
}
vec2 curl2(vec2 p) {
  float e = 0.01;
  float dx = gnoise2(p + vec2(e, 0.0)) - gnoise2(p - vec2(e, 0.0));
  float dy = gnoise2(p + vec2(0.0, e)) - gnoise2(p - vec2(0.0, e));
  return vec2(dy, -dx) * (1.0 / (2.0 * e));
}
void main() {
  vec2 p = vec2(vUv.x * uAspect, vUv.y) * 3.0 + vec2(uTime * 0.2, 0.0);
  vec2 v = curl2(p);
  fragColor = vec4(v.x * 0.04 + 0.5, v.y * 0.04 + 0.5, 0.8, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn hash22(p : vec2f) -> vec2f {
  let k = vec2f(dot(p, vec2f(127.1, 311.7)), dot(p, vec2f(269.5, 183.3)));
  return vec2f(fract(sin(k.x) * 43758.5453), fract(sin(k.y) * 43758.5453));
}
fn gnoise2(p : vec2f) -> f32 {
  let cell = vec2f(floor(p.x), floor(p.y));
  let f = p - cell;
  let u = vec2f(f.x * f.x * f.x * (f.x * (f.x * 6.0 - 15.0) + 10.0), f.y * f.y * f.y * (f.y * (f.y * 6.0 - 15.0) + 10.0));
  let ga = hash22(cell) * 2.0 - vec2f(1.0, 1.0);
  let gb = hash22(cell + vec2f(1.0, 0.0)) * 2.0 - vec2f(1.0, 1.0);
  let gc = hash22(cell + vec2f(0.0, 1.0)) * 2.0 - vec2f(1.0, 1.0);
  let gd = hash22(cell + vec2f(1.0, 1.0)) * 2.0 - vec2f(1.0, 1.0);
  let va = dot(ga, f);
  let vb = dot(gb, f - vec2f(1.0, 0.0));
  let vc = dot(gc, f - vec2f(0.0, 1.0));
  let vd = dot(gd, f - vec2f(1.0, 1.0));
  return mix(mix(va, vb, u.x), mix(vc, vd, u.x), u.y) * 0.7 + 0.5;
}
fn curl2(p : vec2f) -> vec2f {
  let e = 0.01;
  let dx = gnoise2(p + vec2f(e, 0.0)) - gnoise2(p - vec2f(e, 0.0));
  let dy = gnoise2(p + vec2f(0.0, e)) - gnoise2(p - vec2f(0.0, e));
  return vec2f(dy, -dx) * (1.0 / (2.0 * e));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = vec2f(bm_in.vUv.x * bm_u.uAspect, bm_in.vUv.y) * 3.0 + vec2f(bm_u.uTime * 0.2, 0.0);
  let v = curl2(p);
  return vec4f(v.x * 0.04 + 0.5, v.y * 0.04 + 0.5, 0.8, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default fnCurl2Shader;
