/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const fnEaseOutBounceShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
in vec2 vUv;
out vec4 fragColor;
float easeOutBounce(float t) {
  float n1 = 7.5625;
  float d1 = 2.75;
  float result = 0.0;
  if (t < 0.36363636) {
    result = n1 * t * t;
  } else {
    if (t < 0.72727272) {
      float t2 = t - 0.54545454;
      result = n1 * t2 * t2 + 0.75;
    } else {
      if (t < 0.9090909) {
        float t3 = t - 0.81818181;
        result = n1 * t3 * t3 + 0.9375;
      } else {
        float t4 = t - 0.95454545;
        result = n1 * t4 * t4 + 0.984375;
      }
    }
  }
  return result;
}
void main() {
  float mx = (vUv.x - 0.1) / 0.8;
  float my = (vUv.y - 0.2) / 0.6;
  vec3 color = vec3(0.08, 0.08, 0.12);
  if (mx >= 0.0 && mx <= 1.0) {
    float yv = easeOutBounce(clamp(mx, 0.0, 1.0));
    float d = abs(my - yv);
    color = mix(color, vec3(0.55, 0.6, 1.0), 1.0 - smoothstep(0.01, 0.03, d));
    float tt = fract(uTime * 0.45);
    vec2 dotVec = vec2((mx - tt) * 1.2, (my - easeOutBounce(tt)) * 1.2);
    color = mix(color, vec3(1.0, 0.7, 0.3), 1.0 - smoothstep(0.035, 0.055, length(dotVec)));
  }
  fragColor = vec4(color, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn easeOutBounce(t : f32) -> f32 {
  let n1 = 7.5625;
  let d1 = 2.75;
  var result = 0.0;
  if (t < 0.36363636) {
    result = n1 * t * t;
  } else {
    if (t < 0.72727272) {
      let t2 = t - 0.54545454;
      result = n1 * t2 * t2 + 0.75;
    } else {
      if (t < 0.9090909) {
        let t3 = t - 0.81818181;
        result = n1 * t3 * t3 + 0.9375;
      } else {
        let t4 = t - 0.95454545;
        result = n1 * t4 * t4 + 0.984375;
      }
    }
  }
  return result;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let mx = (bm_in.vUv.x - 0.1) / 0.8;
  let my = (bm_in.vUv.y - 0.2) / 0.6;
  var color = vec3f(0.08, 0.08, 0.12);
  if (mx >= 0.0 && mx <= 1.0) {
    let yv = easeOutBounce(clamp(mx, 0.0, 1.0));
    let d = abs(my - yv);
    color = mix(color, vec3f(0.55, 0.6, 1.0), 1.0 - smoothstep(0.01, 0.03, d));
    let tt = fract(bm_u.uTime * 0.45);
    let dotVec = vec2f((mx - tt) * 1.2, (my - easeOutBounce(tt)) * 1.2);
    color = mix(color, vec3f(1.0, 0.7, 0.3), 1.0 - smoothstep(0.035, 0.055, length(dotVec)));
  }
  return vec4f(color, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default fnEaseOutBounceShader;
