/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const fnFillAAShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform float uAspect;
in vec2 vUv;
out vec4 fragColor;
float fillAA(float d, float softness) {
  return 1.0 - smoothstep(0.0, softness, d);
}
float sdHexagon(vec2 p, float radius) {
  float kx = -0.866025404;
  float ky = 0.5;
  float kz = 0.577350269;
  vec2 q = vec2(abs(p.x), abs(p.y));
  float shift = 2.0 * min(dot(vec2(kx, ky), q), 0.0);
  vec2 q2 = q - vec2(kx, ky) * shift;
  vec2 q3 = vec2(q2.x - clamp(q2.x, -kz * radius, kz * radius), q2.y - radius);
  return length(q3) * sign(q3.y);
}
vec2 rotate2(vec2 p, float angle) {
  float c = cos(angle);
  float s = sin(angle);
  return vec2(p.x * c - p.y * s, p.x * s + p.y * c);
}
void main() {
  vec2 p = rotate2(vec2((vUv.x - 0.5) * uAspect, vUv.y - 0.5), uTime * 0.3);
  float a = fillAA(sdHexagon(p, 0.28), 0.006);
  fragColor = vec4(vec3(0.95, 0.6, 0.25) * a + vec3(0.08, 0.08, 0.12) * (1.0 - a), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn fillAA(d : f32, softness : f32) -> f32 {
  return 1.0 - smoothstep(0.0, softness, d);
}
fn sdHexagon(p : vec2f, radius : f32) -> f32 {
  let kx = -0.866025404;
  let ky = 0.5;
  let kz = 0.577350269;
  let q = vec2f(abs(p.x), abs(p.y));
  let shift = 2.0 * min(dot(vec2f(kx, ky), q), 0.0);
  let q2 = q - vec2f(kx, ky) * shift;
  let q3 = vec2f(q2.x - clamp(q2.x, -kz * radius, kz * radius), q2.y - radius);
  return length(q3) * sign(q3.y);
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = rotate2(vec2f((bm_in.vUv.x - 0.5) * bm_u.uAspect, bm_in.vUv.y - 0.5), bm_u.uTime * 0.3);
  let a = fillAA(sdHexagon(p, 0.28), 0.006);
  return vec4f(vec3f(0.95, 0.6, 0.25) * a + vec3f(0.08, 0.08, 0.12) * (1.0 - a), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default fnFillAAShader;
