/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const fnFresnelShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform float uAspect;
in vec2 vUv;
out vec4 fragColor;
float fresnel(vec3 normal, vec3 viewDir, float power) {
  float base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
void main() {
  vec2 p = vec2((vUv.x - 0.5) * uAspect, vUv.y - 0.5) * 2.3;
  float r = length(p);
  vec3 lightDir = vec3(cos(uTime * 0.9), 0.6, sin(uTime * 0.9));
  vec3 color = vec3(0.07, 0.07, 0.11);
  if (r < 1.0) {
    vec3 normal = vec3(p.x, p.y, sqrt(1.0 - r * r));
    float v = fresnel(normal, vec3(0.0, 0.0, 1.0), 3.0);
    color = vec3(v, v, v);
  }
  fragColor = vec4(color, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn fresnel(normal : vec3f, viewDir : vec3f, power : f32) -> f32 {
  let base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = vec2f((bm_in.vUv.x - 0.5) * bm_u.uAspect, bm_in.vUv.y - 0.5) * 2.3;
  let r = length(p);
  let lightDir = vec3f(cos(bm_u.uTime * 0.9), 0.6, sin(bm_u.uTime * 0.9));
  var color = vec3f(0.07, 0.07, 0.11);
  if (r < 1.0) {
    let normal = vec3f(p.x, p.y, sqrt(1.0 - r * r));
    let v = fresnel(normal, vec3f(0.0, 0.0, 1.0), 3.0);
    color = vec3f(v, v, v);
  }
  return vec4f(color, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default fnFresnelShader;
