/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const fnGerstnerWaveShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform float uAspect;
in vec2 vUv;
out vec4 fragColor;
vec3 gerstnerWave(vec2 p, vec2 dir, float steepness, float wavelength, float time) {
  float k = 6.28318 / wavelength;
  float c = sqrt(9.8 / k);
  vec2 d = normalize(dir);
  float f = k * (dot(d, p) - c * time);
  float a = steepness / k;
  return vec3(d.x * a * cos(f), d.y * a * cos(f), a * sin(f));
}
void main() {
  vec2 p = vec2(vUv.x * uAspect, vUv.y) * 6.0;
  vec3 w1 = gerstnerWave(p, vec2(1.0, 0.4), 0.9, 2.2, uTime);
  vec3 w2 = gerstnerWave(p, vec2(-0.6, 1.0), 0.7, 1.3, uTime);
  float h = (w1.z + w2.z) * 1.6 + 0.5;
  vec3 deep = vec3(0.05, 0.15, 0.3);
  vec3 crest = vec3(0.75, 0.9, 1.0);
  fragColor = vec4(mix(deep, crest, clamp(h, 0.0, 1.0)), 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn gerstnerWave(p : vec2f, dir : vec2f, steepness : f32, wavelength : f32, time : f32) -> vec3f {
  let k = 6.28318 / wavelength;
  let c = sqrt(9.8 / k);
  let d = normalize(dir);
  let f = k * (dot(d, p) - c * time);
  let a = steepness / k;
  return vec3f(d.x * a * cos(f), d.y * a * cos(f), a * sin(f));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = vec2f(bm_in.vUv.x * bm_u.uAspect, bm_in.vUv.y) * 6.0;
  let w1 = gerstnerWave(p, vec2f(1.0, 0.4), 0.9, 2.2, bm_u.uTime);
  let w2 = gerstnerWave(p, vec2f(-0.6, 1.0), 0.7, 1.3, bm_u.uTime);
  let h = (w1.z + w2.z) * 1.6 + 0.5;
  let deep = vec3f(0.05, 0.15, 0.3);
  let crest = vec3f(0.75, 0.9, 1.0);
  return vec4f(mix(deep, crest, clamp(h, 0.0, 1.0)), 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default fnGerstnerWaveShader;
