/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const fnRotate3Shader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform float uAspect;
in vec2 vUv;
out vec4 fragColor;
vec3 rotate3(vec3 p, vec3 axis, float angle) {
  vec3 a = normalize(axis);
  float c = cos(angle);
  float s = sin(angle);
  return p * c + cross(a, p) * s + a * (dot(a, p) * (1.0 - c));
}
void main() {
  vec2 q = vec2((vUv.x - 0.5) * uAspect, vUv.y - 0.5);
  float r = length(q);
  float z = sqrt(max(0.2025 - r * r, 0.0));
  vec3 n = normalize(vec3(q.x, q.y, z));
  vec3 rn = rotate3(n, normalize(vec3(0.5, 1.0, 0.3)), uTime * 0.8);
  float c = mod(floor(rn.x * 3.0 + 3.0) + floor(rn.y * 3.0 + 3.0) + floor(rn.z * 3.0 + 3.0), 2.0);
  float shade = mix(0.2, 1.0, c) * (n.z * 0.75 + 0.25);
  float mask = 1.0 - smoothstep(0.44, 0.45, r);
  float tone = shade * mask + 0.08 * (1.0 - mask);
  fragColor = vec4(tone, tone, tone, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn rotate3(p : vec3f, axis : vec3f, angle : f32) -> vec3f {
  let a = normalize(axis);
  let c = cos(angle);
  let s = sin(angle);
  return p * c + cross(a, p) * s + a * (dot(a, p) * (1.0 - c));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let q = vec2f((bm_in.vUv.x - 0.5) * bm_u.uAspect, bm_in.vUv.y - 0.5);
  let r = length(q);
  let z = sqrt(max(0.2025 - r * r, 0.0));
  let n = normalize(vec3f(q.x, q.y, z));
  let rn = rotate3(n, normalize(vec3f(0.5, 1.0, 0.3)), bm_u.uTime * 0.8);
  let c = ((floor(rn.x * 3.0 + 3.0) + floor(rn.y * 3.0 + 3.0) + floor(rn.z * 3.0 + 3.0)) - (2.0) * floor((floor(rn.x * 3.0 + 3.0) + floor(rn.y * 3.0 + 3.0) + floor(rn.z * 3.0 + 3.0)) / (2.0)));
  let shade = mix(0.2, 1.0, c) * (n.z * 0.75 + 0.25);
  let mask = 1.0 - smoothstep(0.44, 0.45, r);
  let tone = shade * mask + 0.08 * (1.0 - mask);
  return vec4f(tone, tone, tone, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default fnRotate3Shader;
