/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const fnRemapShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
in vec2 vUv;
out vec4 fragColor;
float remap(float value, float inLow, float inHigh, float outLow, float outHigh) {
  return outLow + (value - inLow) / (inHigh - inLow) * (outHigh - outLow);
}
void main() {
  float n = vUv.x;
  if (vUv.y < 0.5) {
    n = clamp(remap(vUv.x, 0.3, 0.7, 0.0, 1.0), 0.0, 1.0);
  }
  fragColor = vec4(n, n, n, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn remap(value : f32, inLow : f32, inHigh : f32, outLow : f32, outHigh : f32) -> f32 {
  return outLow + (value - inLow) / (inHigh - inLow) * (outHigh - outLow);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  var n = bm_in.vUv.x;
  if (bm_in.vUv.y < 0.5) {
    n = clamp(remap(bm_in.vUv.x, 0.3, 0.7, 0.0, 1.0), 0.0, 1.0);
  }
  return vec4f(n, n, n, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default fnRemapShader;
