/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const fnRgb2hsvShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
in vec2 vUv;
out vec4 fragColor;
vec3 rgb2hsv(vec3 color) {
  float maxc = max(color.x, max(color.y, color.z));
  float minc = min(color.x, min(color.y, color.z));
  float delta = maxc - minc;
  float h = 0.0;
  if (delta > 0.00001) {
    if (color.x >= maxc - 0.00001) {
      h = (color.y - color.z) / delta;
      h = (h - floor(h / 6.0) * 6.0) / 6.0;
    } else {
      if (color.y >= maxc - 0.00001) {
        h = ((color.z - color.x) / delta + 2.0) / 6.0;
      } else {
        h = ((color.x - color.y) / delta + 4.0) / 6.0;
      }
    }
  }
  float s = 0.0;
  if (maxc > 0.00001) {
    s = delta / maxc;
  }
  return vec3(h, s, maxc);
}
vec3 cosinePalette(float t, vec3 a, vec3 b, vec3 c, vec3 d) {
  vec3 phase = (c * t + d) * 6.28318;
  return a + vec3(cos(phase.x), cos(phase.y), cos(phase.z)) * b;
}
void main() {
  vec3 src = cosinePalette(vUv.x + uTime * 0.05, vec3(0.5, 0.5, 0.5), vec3(0.5, 0.5, 0.5), vec3(1.0, 1.0, 1.0), vec3(0.0, 0.33, 0.67));
  vec3 shown = src;
  if (vUv.y < 0.5) {
    shown = rgb2hsv(src);
  }
  fragColor = vec4(shown, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn rgb2hsv(color : vec3f) -> vec3f {
  let maxc = max(color.x, max(color.y, color.z));
  let minc = min(color.x, min(color.y, color.z));
  let delta = maxc - minc;
  var h = 0.0;
  if (delta > 0.00001) {
    if (color.x >= maxc - 0.00001) {
      h = (color.y - color.z) / delta;
      h = (h - floor(h / 6.0) * 6.0) / 6.0;
    } else {
      if (color.y >= maxc - 0.00001) {
        h = ((color.z - color.x) / delta + 2.0) / 6.0;
      } else {
        h = ((color.x - color.y) / delta + 4.0) / 6.0;
      }
    }
  }
  var s = 0.0;
  if (maxc > 0.00001) {
    s = delta / maxc;
  }
  return vec3f(h, s, maxc);
}
fn cosinePalette(t : f32, a : vec3f, b : vec3f, c : vec3f, d : vec3f) -> vec3f {
  let phase = (c * t + d) * 6.28318;
  return a + vec3f(cos(phase.x), cos(phase.y), cos(phase.z)) * b;
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let src = cosinePalette(bm_in.vUv.x + bm_u.uTime * 0.05, vec3f(0.5, 0.5, 0.5), vec3f(0.5, 0.5, 0.5), vec3f(1.0, 1.0, 1.0), vec3f(0.0, 0.33, 0.67));
  var shown = src;
  if (bm_in.vUv.y < 0.5) {
    shown = rgb2hsv(src);
  }
  return vec4f(shown, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default fnRgb2hsvShader;
