/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const fnSdTorus3Shader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform float uTime;
uniform float uAspect;
in vec2 vUv;
out vec4 fragColor;
float sdTorus3(vec3 p, vec2 radii) {
  vec2 q = vec2(length(p.xz) - radii.x, p.y);
  return length(q) - radii.y;
}
vec2 rotate2(vec2 p, float angle) {
  float c = cos(angle);
  float s = sin(angle);
  return vec2(p.x * c - p.y * s, p.x * s + p.y * c);
}
float lambert(vec3 normal, vec3 lightDir) {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
float fresnel(vec3 normal, vec3 viewDir, float power) {
  float base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
float scene(vec3 q, float time) {
  vec2 r = rotate2(q.yz, time * 0.6);
  return sdTorus3(vec3(q.x, r.x, r.y), vec2(0.5, 0.16));
}
void main() {
  vec2 p = vec2((vUv.x - 0.5) * uAspect, vUv.y - 0.5);
  vec3 ro = vec3(0.0, 0.3, 2.2);
  vec3 rd = normalize(vec3(p.x, p.y - 0.1, -1.3));
  float t = 0.0;
  for (float i = 0.0; i < 64.0; i = i + 1.0) {
    t = t + clamp(scene(ro + rd * t, uTime), 0.001, 0.3);
  }
  vec3 hit = ro + rd * t;
  vec3 color = vec3(0.07, 0.07, 0.11);
  if (scene(hit, uTime) < 0.01) {
    float e = 0.002;
    vec3 n = normalize(vec3(scene(hit + vec3(e, 0.0, 0.0), uTime) - scene(hit - vec3(e, 0.0, 0.0), uTime), scene(hit + vec3(0.0, e, 0.0), uTime) - scene(hit - vec3(0.0, e, 0.0), uTime), scene(hit + vec3(0.0, 0.0, e), uTime) - scene(hit - vec3(0.0, 0.0, e), uTime)));
    float diffuse = lambert(n, vec3(0.6, 0.8, 0.4));
    float rim = fresnel(n, vec3(0.0, 0.0, 1.0), 3.0);
    color = vec3(0.85, 0.5, 0.3) * (0.2 + diffuse * 0.8) + vec3(0.5, 0.6, 1.0) * (rim * 0.4);
  }
  fragColor = vec4(color, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn sdTorus3(p : vec3f, radii : vec2f) -> f32 {
  let q = vec2f(length(p.xz) - radii.x, p.y);
  return length(q) - radii.y;
}
fn rotate2(p : vec2f, angle : f32) -> vec2f {
  let c = cos(angle);
  let s = sin(angle);
  return vec2f(p.x * c - p.y * s, p.x * s + p.y * c);
}
fn lambert(normal : vec3f, lightDir : vec3f) -> f32 {
  return max(dot(normalize(normal), normalize(lightDir)), 0.0);
}
fn fresnel(normal : vec3f, viewDir : vec3f, power : f32) -> f32 {
  let base = 1.0 - max(dot(normalize(normal), normalize(viewDir)), 0.0);
  return pow(base, power);
}
fn scene(q : vec3f, time : f32) -> f32 {
  let r = rotate2(q.yz, time * 0.6);
  return sdTorus3(vec3f(q.x, r.x, r.y), vec2f(0.5, 0.16));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let p = vec2f((bm_in.vUv.x - 0.5) * bm_u.uAspect, bm_in.vUv.y - 0.5);
  let ro = vec3f(0.0, 0.3, 2.2);
  let rd = normalize(vec3f(p.x, p.y - 0.1, -1.3));
  var t = 0.0;
  for (var i = 0.0; i < 64.0; i = i + 1.0) {
    t = t + clamp(scene(ro + rd * t, bm_u.uTime), 0.001, 0.3);
  }
  let hit = ro + rd * t;
  var color = vec3f(0.07, 0.07, 0.11);
  if (scene(hit, bm_u.uTime) < 0.01) {
    let e = 0.002;
    let n = normalize(vec3f(scene(hit + vec3f(e, 0.0, 0.0), bm_u.uTime) - scene(hit - vec3f(e, 0.0, 0.0), bm_u.uTime), scene(hit + vec3f(0.0, e, 0.0), bm_u.uTime) - scene(hit - vec3f(0.0, e, 0.0), bm_u.uTime), scene(hit + vec3f(0.0, 0.0, e), bm_u.uTime) - scene(hit - vec3f(0.0, 0.0, e), bm_u.uTime)));
    let diffuse = lambert(n, vec3f(0.6, 0.8, 0.4));
    let rim = fresnel(n, vec3f(0.0, 0.0, 1.0), 3.0);
    color = vec3f(0.85, 0.5, 0.3) * (0.2 + diffuse * 0.8) + vec3f(0.5, 0.6, 1.0) * (rim * 0.4);
  }
  return vec4f(color, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default fnSdTorus3Shader;
