/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const fnSmootherstepShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uTime: 'float'; uAspect: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
out vec2 vUv;
void main() {
  vUv = aUv;
  gl_Position = vec4(aPosition, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
in vec2 vUv;
out vec4 fragColor;
float smootherstep(float edge0, float edge1, float x) {
  float t = clamp((x - edge0) / (edge1 - edge0), 0.0, 1.0);
  return t * t * t * (t * (t * 6.0 - 15.0) + 10.0);
}
void main() {
  float mx = (vUv.x - 0.1) / 0.8;
  float my = (vUv.y - 0.2) / 0.6;
  vec3 color = vec3(0.08, 0.08, 0.12);
  if (mx >= 0.0 && mx <= 1.0) {
    float quintic = smootherstep(0.0, 1.0, clamp(mx, 0.0, 1.0));
    float cubic = smoothstep(0.0, 1.0, clamp(mx, 0.0, 1.0));
    color = mix(color, vec3(0.4, 0.45, 0.6), 1.0 - smoothstep(0.008, 0.024, abs(my - cubic)));
    color = mix(color, vec3(1.0, 0.7, 0.3), 1.0 - smoothstep(0.008, 0.024, abs(my - quintic)));
  }
  fragColor = vec4(color, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTime : f32,
  uAspect : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn smootherstep(edge0 : f32, edge1 : f32, x : f32) -> f32 {
  let t = clamp((x - edge0) / (edge1 - edge0), 0.0, 1.0);
  return t * t * t * (t * (t * 6.0 - 15.0) + 10.0);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let mx = (bm_in.vUv.x - 0.1) / 0.8;
  let my = (bm_in.vUv.y - 0.2) / 0.6;
  var color = vec3f(0.08, 0.08, 0.12);
  if (mx >= 0.0 && mx <= 1.0) {
    let quintic = smootherstep(0.0, 1.0, clamp(mx, 0.0, 1.0));
    let cubic = smoothstep(0.0, 1.0, clamp(mx, 0.0, 1.0));
    color = mix(color, vec3f(0.4, 0.45, 0.6), 1.0 - smoothstep(0.008, 0.024, abs(my - cubic)));
    color = mix(color, vec3f(1.0, 0.7, 0.3), 1.0 - smoothstep(0.008, 0.024, abs(my - quintic)));
  }
  return vec4f(color, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uTime: 'float', uAspect: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uTime","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAspect","type":"float","kind":"1f","size":1,"offset":4}],"uniformBlockSize":16},
};

export default fnSmootherstepShader;
