import type { CompiledShaderModule } from '../compiler/compile.js';

/**
 * Serialises a compiled shader for the js13k runtime.
 *
 * The ordinary `.gen.ts` module carries typed records, a layout object and
 * per-uniform metadata so `createProgram` can give you `program.uniforms.uMvp`
 * with the right type. None of that survives a 13 kilobyte budget: names cost
 * bytes, and every one of them would ship.
 *
 * What is left is the smallest thing the runtime can build a pipeline from — an
 * array, positional, no keys:
 *
 *   [wgsl, vertexAttrSizes, instanceAttrSizes, uniformBytes, textureBindings]
 *
 * The uniform block becomes a flat `Float32Array` you fill yourself. The offsets
 * are emitted as a comment rather than data, so they cost nothing at runtime and
 * are still there when you are working out what goes where.
 */

export interface Js13kShader {
  /** Global constant name, e.g. `BM_CUBE`. */
  name: string;
  source: string;
}

/** `color-cube.shader.ts` → `BM_COLOR_CUBE`. */
export function js13kNameFromFile(filePath: string): string {
  const base = filePath.replace(/^.*[/\\]/, '').replace(/\.shader\.ts$/, '');
  return `BM_${base.replace(/[^A-Za-z0-9]+/g, '_').toUpperCase()}`;
}

export function buildJs13kShader(name: string, compiled: CompiledShaderModule): Js13kShader {
  const vertex: number[] = [];
  const instance: number[] = [];
  for (const entry of compiled.layout.attributes) {
    (entry.divisor === 1 ? instance : vertex).push(entry.size);
  }

  // Sampler bindings travel in pairs, in declaration order, because that is the
  // order the runtime walks when it binds textures.
  const textures: number[][] = [];
  const offsets: string[] = [];
  for (const entry of compiled.layout.uniforms) {
    if (entry.textureBinding !== undefined && entry.samplerBinding !== undefined) {
      textures.push([entry.textureBinding, entry.samplerBinding]);
    } else if (entry.offset !== undefined) {
      // Byte offset → float index, which is what you index a Float32Array by.
      offsets.push(`${entry.name} @${entry.offset / 4}${entry.size > 1 ? `..${entry.offset / 4 + entry.size - 1}` : ''}`);
    }
  }

  const parts = [
    JSON.stringify(compiled.wgslSrc),
    JSON.stringify(vertex),
    JSON.stringify(instance),
    String(compiled.layout.uniformBlockSize),
    JSON.stringify(textures),
  ];

  const header = offsets.length > 0 ? `// uniform floats: ${offsets.join(', ')}\n` : '';
  return { name, source: `${header}const ${name} = [${parts.join(',')}];\n` };
}

/** Joins every shader into the single file the game concatenates. */
export function buildJs13kShaderFile(shaders: Js13kShader[]): string {
  return [
    '// Generated by BroMetal --js13k. Concatenate with brometal.js and your game,',
    '// then minify the whole program together (terser --toplevel --mangle).',
    '//',
    '// Each entry is [wgsl, attrSizes, instanceAttrSizes, uniformBytes, textureBindings]',
    '// and goes straight into bmProgram(src[0], { a: src[1], i: src[2], u: src[3], t: src[4] }).',
    '',
    ...shaders.map((shader) => shader.source),
  ].join('\n');
}

/**
 * Turns the compiled core into the plain global-function source a js13k entry
 * concatenates.
 *
 * `tiny` is written as an ES module so `full` can import it and so it type
 * checks. A 13 kB game wants neither: it concatenates everything into one scope
 * and runs a single mangler over the lot. Dropping the module syntax is the
 * whole conversion — `export function bmDraw` becomes `function bmDraw`, which
 * is a top-level name terser can then rename.
 */
export function stripModuleSyntax(source: string): string {
  return source
    // Triple-slash references are a compiler instruction, meaningless here.
    .replace(/^\/\/\/\s*<reference[^\n]*\n/gm, '')
    // `export function f` / `export const x` / `export let y` → the declaration.
    .replace(/^export (?=(?:async )?function |const |let |var |class )/gm, '')
    // Imports between the core's own files: concatenation replaces them.
    .replace(/^import\s[^;]*;\n/gm, '')
    // Bare re-export or marker statements carry nothing into a script.
    .replace(/^export\s*\{[^}]*\};?\n/gm, '')
    .replace(/^export type[^\n]*\n/gm, '')
    .trimStart();
}

/**
 * What a reader sees first when they open the emitted runtime.
 *
 * The core's own comments are written for whoever maintains it — they discuss
 * tree-shaking, the split from the full runtime, why a constant is spelled as a
 * number. All true, none of it useful to someone who just wants to paste this
 * into a game, and it is the first thing they read. This goes above it.
 */
export const JS13K_RUNTIME_HEADER = `// BroMetal — WebGPU runtime for 13 kB games.  https://brometal.dev/js13k
//
// Drop this in your project as its own file. Everything is a global function,
// so concatenate it with your compiled shaders and your game, then minify the
// whole program in one pass:
//
//   cat brometal.js js13k/shaders.js game.js > out.js
//   terser out.js --compress --mangle --toplevel -o game.min.js
//
// --toplevel is the flag that pays: it renames these functions and deletes
// every one you never call. Comments cost nothing — they never reach the zip.
//
// Generated by \`brometal prod --js13k\`. Edit your shaders, not this file.

`;

/** The emitted runtime: the user-facing header, then the core as plain globals. */
export function buildJs13kRuntime(parts: string[]): string {
  return JS13K_RUNTIME_HEADER + parts.map(stripModuleSyntax).join('\n');
}
