/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const gpuReadbackShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, Record<string, never>, { uCount: 'float'; uData: 'storage' }> = {
  wgslSrc: `struct BmUniforms {
  uCount : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var<storage, read> uData : array<vec4f>;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = bm_in.aUv;
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let index = min(floor(bm_in.vUv.x * bm_u.uCount), bm_u.uCount - 1.0);
  let value = uData[u32(index)];
  return vec4f(value.x, value.y, value.z, f32(arrayLength(&uData)) / bm_u.uCount);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: {},
  uniforms: { uCount: 'float', uData: 'storage' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0}],"uniforms":[{"name":"uCount","type":"float","kind":"1f","size":1,"offset":0},{"name":"uData","type":"storage","kind":"1i","size":1,"unit":0,"textureBinding":1}],"uniformBlockSize":16},

};

export default gpuReadbackShader;
