/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const gpuComputeShader: CompiledShader<Record<string, never>, Record<string, never>, { uCount: 'float'; uOut: 'storage' }> = {
  vertexSrc: ``,
  fragmentSrc: ``,
  wgslSrc: `struct BmUniforms {
  uCount : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var<storage, read_write> uOut : array<vec4f>;
@compute @workgroup_size(64, 1, 1)
fn cs_main(@builtin(global_invocation_id) bm_gid : vec3u) {
  let id = vec3f(bm_gid);
  let index = min(floor(id.x), max(bm_u.uCount - 1.0, 0.0));
  uOut[u32(index)] = vec4f(index / bm_u.uCount, 0.5, 1.0 - index / bm_u.uCount, 1.0);
}
`,
  attributes: {},
  instanceAttributes: {},
  uniforms: { uCount: 'float', uOut: 'storage' },
  layout: {"attributes":[],"uniforms":[{"name":"uCount","type":"float","kind":"1f","size":1,"offset":0},{"name":"uOut","type":"storage","kind":"1i","size":1,"unit":0,"textureBinding":1}],"uniformBlockSize":16},
  storageWritten: ["uOut"],
  hasCompute: true,

};

export default gpuComputeShader;
