/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const cubesShader: CompiledShader<{ aPosition: 'vec3'; aColor: 'vec3' }, { iOffset: 'vec3'; iAxis: 'vec3'; iSpeed: 'float'; iScale: 'float'; iTint: 'vec3' }, { uViewProj: 'mat4'; uTime: 'float' }> = {
  vertexSrc: `#version 300 es
in vec3 aPosition;
in vec3 aColor;
in vec3 iOffset;
in vec3 iAxis;
in float iSpeed;
in float iScale;
in vec3 iTint;
uniform mat4 uViewProj;
uniform float uTime;
out vec3 vColor;
void main() {
  float angle = uTime * iSpeed;
  float c = cos(angle);
  float s = sin(angle);
  vec3 p = aPosition * iScale;
  vec3 rotated = p * c + cross(iAxis, p) * s + iAxis * (dot(iAxis, p) * (1.0 - c));
  vColor = aColor * iTint;
  gl_Position = uViewProj * vec4(rotated + iOffset, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
in vec3 vColor;
out vec4 fragColor;
void main() {
  fragColor = vec4(vColor, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aColor: 'vec3' },
  instanceAttributes: { iOffset: 'vec3', iAxis: 'vec3', iSpeed: 'float', iScale: 'float', iTint: 'vec3' },
  uniforms: { uViewProj: 'mat4', uTime: 'float' },
};

export default cubesShader;
